/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_SlidingButton
C Source
*/

#include "Ft_Esd_SlidingButton.h"

#include "Esd_Context.h"
#include "EVE_CoDl.h"
#include "Esd_BitmapHandle.h"
#include "Esd_Core.h"
#include "Esd_FontInfo.h"
#include "Ft_Esd_BitmapHandle.h"
#include "Ft_Esd_Dl.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
uint8_t Ft_Esd_SlidingButton_Font__Default(void *context) { return 29; }
ft_rgb32_t Ft_Esd_SlidingButton_TextColor__Default(void *context) { return 0x0UL; }
ft_argb32_t Ft_Esd_SlidingButton_BackgroundColor__Default(void *context) { return 0xffebecf0UL; }
ft_argb32_t Ft_Esd_SlidingButton_KnobColor__Default(void *context) { return 0xffffffffUL; }


static Ft_Esd_WidgetSlots s_Ft_Esd_SlidingButton__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_SlidingButton_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_SlidingButton_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_SlidingButton_End,
};

static void Ft_Esd_SlidingButton_TouchTag_Down__Signal(void *context);
static void Ft_Esd_SlidingButton_TouchTag_Up__Signal(void *context);
static void Ft_Esd_SlidingButton_ESD_Timer_Fired__Signal(void *context);
static void Ft_Esd_SlidingButton_Render_Forwarder_ForwardRender__Signal(void *context);

void Ft_Esd_SlidingButton__TouchTag__Initializer(Ft_Esd_SlidingButton *context)
{
	Esd_TouchTag *object = (Esd_TouchTag *)&context->TouchTag;
	Esd_TouchTag__Initializer(object);
	object->Owner = (void *)context;
	object->Down = Ft_Esd_SlidingButton_TouchTag_Down__Signal;
	object->Up = Ft_Esd_SlidingButton_TouchTag_Up__Signal;
}

void Ft_Esd_SlidingButton__ESD_Timer__Initializer(Ft_Esd_SlidingButton *context)
{
	Ft_Esd_Timer *object = (Ft_Esd_Timer *)&context->ESD_Timer;
	Ft_Esd_Timer__Initializer(object);
	object->Owner = (void *)context;
	object->TimeoutMs = 5L;
	object->Fired = Ft_Esd_SlidingButton_ESD_Timer_Fired__Signal;
}

void Ft_Esd_SlidingButton__Render_Forwarder__Initializer(Ft_Esd_SlidingButton *context)
{
	Ft_Esd_RenderForwarder *object = (Ft_Esd_RenderForwarder *)&context->Render_Forwarder;
	Ft_Esd_RenderForwarder__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->ForwardRender = Ft_Esd_SlidingButton_Render_Forwarder_ForwardRender__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Ft_Esd_SlidingButton__Initializer(Ft_Esd_SlidingButton *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_SlidingButton_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_SlidingButton__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 298;
	context->Widget.LocalHeight = 66;
	context->Font = Ft_Esd_SlidingButton_Font__Default;
	context->Text = "Display Text";
	context->TextColor = Ft_Esd_SlidingButton_TextColor__Default;
	context->TextPaddingX = 12L;
	context->TextPaddingY = 18L;
	context->Activated = Esd_Noop;
	context->BackgroundColor = Ft_Esd_SlidingButton_BackgroundColor__Default;
	context->KnobColor = Ft_Esd_SlidingButton_KnobColor__Default;
	context->Alpha = 0L;
	context->Direction = 1L;
	context->TempHolder = 0L;
	context->ControlActivated = 0;
	context->Knob_X = 0L;
	context->Variable = 0L;
	context->IsDown = 0;
	Ft_Esd_SlidingButton__TouchTag__Initializer(context);
	Ft_Esd_SlidingButton__ESD_Timer__Initializer(context);
	Ft_Esd_SlidingButton__Render_Forwarder__Initializer(context);
}

ESD_CORE_EXPORT Esd_FontInfo *Esd_GetRomFont(uint8_t);
void FT_Esd_Draw_Button(Ft_Esd_SlidingButton *context, int, int, int, int, const char *, int, int, ft_int16_t, ft_rgb32_t, ft_argb32_t);
void Button_Periodic_Update(Ft_Esd_SlidingButton *context, int, int, int, int, ft_argb32_t);

void Ft_Esd_SlidingButton_Start(Ft_Esd_SlidingButton *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context);
	Esd_TouchTag_Start(&context->TouchTag);
}

void Ft_Esd_SlidingButton_Update(Ft_Esd_SlidingButton *context)
{
	void *owner = context->Owner;
	int16_t left = Esd_TouchTag_TouchXDelta(&context->TouchTag);
	int right = context->Variable;
	int update_variable = left + right;
	context->Knob_X = update_variable;
	int update_variable_1 = context->Knob_X;
	context->Variable = update_variable_1;
	Esd_TouchTag_Update(&context->TouchTag);
	Ft_Esd_Timer_Update(&context->ESD_Timer);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void Ft_Esd_SlidingButton_End(Ft_Esd_SlidingButton *context)
{
	void *owner = context->Owner;
	Esd_TouchTag_End(&context->TouchTag);
	Ft_Esd_Timer_End(&context->ESD_Timer);
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Render_Forwarder); 
}

void Ft_Esd_SlidingButton_ResetKnobPosition(Ft_Esd_SlidingButton *context)
{
	void *owner = context->Owner;
	Ft_Esd_Timer_Run(&context->ESD_Timer);
}

void Ft_Esd_SlidingButton_TouchTag_Down__Signal(void *c)
{
	Ft_Esd_SlidingButton *context = (Ft_Esd_SlidingButton *)c;
	void *owner = context->Owner;
	bool set_variable_2 = 1;
	context->IsDown = (bool)set_variable_2;
}

void Ft_Esd_SlidingButton_TouchTag_Up__Signal(void *c)
{
	Ft_Esd_SlidingButton *context = (Ft_Esd_SlidingButton *)c;
	void *owner = context->Owner;
	int left_1 = context->Knob_X;
	int right_1 = context->TempHolder;
	int if_1 = left_1 >= right_1;
	if (if_1)
	{
		bool if_2 = context->ControlActivated;
		if (if_2)
		{
		}
		else
		{
			context->Activated(owner);
		}
		bool set_variable_3 = 0;
		context->IsDown = (bool)set_variable_3;
		bool set_variable_5 = 1;
		context->ControlActivated = set_variable_5;
	}
	else
	{
		bool set_variable_3_1 = 0;
		context->IsDown = (bool)set_variable_3_1;
	}
}

void Ft_Esd_SlidingButton_ESD_Timer_Fired__Signal(void *c)
{
	Ft_Esd_SlidingButton *context = (Ft_Esd_SlidingButton *)c;
	void *owner = context->Owner;
	bool set_variable_4 = 0;
	context->ControlActivated = set_variable_4;
}

void Ft_Esd_SlidingButton_Render_Forwarder_ForwardRender__Signal(void *c)
{
	Ft_Esd_SlidingButton *context = (Ft_Esd_SlidingButton *)c;
	void *owner = context->Owner;
	ft_int16_t x = context->Widget.GlobalX;
	ft_int16_t y = context->Widget.GlobalY;
	ft_int16_t width = context->Widget.GlobalWidth;
	ft_int16_t height = context->Widget.GlobalHeight;
	const char * s = context->Text;
	int paddingX = context->TextPaddingX;
	int paddingY = context->TextPaddingY;
	uint8_t i = context->Font(owner);
	Esd_FontInfo * fontInfo = Esd_GetRomFont(i);
	uint8_t font = Ft_Esd_Dl_Font_Setup(fontInfo);
	ft_rgb32_t textColor = context->TextColor(owner);
	ft_argb32_t backgroundColor = context->BackgroundColor(owner);
	FT_Esd_Draw_Button(context, x, y, width, height, s, paddingX, paddingY, font, textColor, backgroundColor);
	uint8_t s_1 = Esd_TouchTag_Tag(&context->TouchTag);
	Ft_Esd_Dl_TAG(s_1);
	ft_int16_t x_1 = context->Widget.GlobalX;
	ft_int16_t y_1 = context->Widget.GlobalY;
	ft_int16_t width_1 = context->Widget.GlobalWidth;
	ft_int16_t height_1 = context->Widget.GlobalHeight;
	ft_argb32_t knobColor = context->KnobColor(owner);
	Button_Periodic_Update(context, x_1, y_1, width_1, height_1, knobColor);
	EVE_HalContext * phost = Esd_GetHost();
	eve_tag_t s_2 = 255UL;
	EVE_CoDl_tag(phost, s_2);
	ft_bool_t if_3 = context->IsDown;
	if (if_3)
	{
	}
	else
	{
		bool if_4 = context->ControlActivated;
		if (if_4)
		{
		}
		else
		{
			ft_int16_t set_variable = context->Widget.GlobalX;
			context->Variable = set_variable;
		}
	}
}


/* end of file */
