/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_TextBox
C Source
*/

#include "Ft_Esd_TextBox.h"

#include "Esd_Context.h"
#include "Esd_BitmapHandle.h"
#include "Ft_Esd_BitmapHandle.h"
#include "Ft_Esd_CoCmd.h"
#include "Ft_Esd_Dl.h"
#include "Ft_Esd_Elements.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
uint8_t Ft_Esd_TextBox_Font__Default(void *context) { return 27; }
Ft_Esd_Theme * Ft_Esd_TextBox_Theme__Default(void *context) { return Ft_Esd_Theme_GetCurrent(); }
cstring Ft_Esd_TextBox_Text__Default(void *context) { return "TextBox"; }
Esd_FontInfo * Ft_Esd_TextBox_FontResource__Default(void *context) { return 0; }
ft_uint16_t Ft_Esd_TextBox_AlignX__Default(void *context) { return OPT_ALIGN_LEFT; }
ft_uint16_t Ft_Esd_TextBox_AlignY__Default(void *context) { return OPT_ALIGN_TOP; }


static Ft_Esd_WidgetSlots s_Ft_Esd_TextBox__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_TextBox_Update,
	(void(*)(void *))Ft_Esd_TextBox_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Widget_End,
};


void Ft_Esd_TextBox__Initializer(Ft_Esd_TextBox *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_TextBox_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_TextBox__Slots;
	context->Widget.LocalX = 248;
	context->Widget.LocalY = -141;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->Font = Ft_Esd_TextBox_Font__Default;
	context->Theme = Ft_Esd_TextBox_Theme__Default;
	context->Text = Ft_Esd_TextBox_Text__Default;
	context->FontResource = Ft_Esd_TextBox_FontResource__Default;
	context->Radius = 0L;
	context->Raised = 0;
	context->AlignX = Ft_Esd_TextBox_AlignX__Default;
	context->isCenterX = 0;
	context->AlignY = Ft_Esd_TextBox_AlignY__Default;
	context->AdjustX = 0L;
	context->AdjustY = 0L;
}

static uint16_t Ft_Esd_TextBox_Get_Font_Height__return(Ft_Esd_TextBox *context);

void Ft_Esd_TextBox_Set_Fill_Width(Ft_Esd_TextBox *context);
void Ft_Esd_Elements_Panel(Ft_Esd_Theme *, ft_int16_t, ft_int16_t, ft_int16_t, ft_int16_t, ft_int16_t, ft_bool_t);
ESD_CORE_EXPORT uint16_t Esd_GetFontHeight(Esd_FontInfo *);
ESD_CORE_EXPORT Esd_FontInfo *Esd_GetRomFont(uint8_t);
ESD_CORE_EXPORT uint16_t Esd_GetFontBaseLine(Esd_FontInfo *);
ESD_CORE_EXPORT uint16_t Esd_GetFontCapsHeight(Esd_FontInfo *);
ESD_CORE_EXPORT uint16_t Esd_GetFontXOffset(Esd_FontInfo *);

static int Ft_Esd_TextBox_RadiusValue(Ft_Esd_TextBox *context, ft_int32_t inputRadius);
static int Ft_Esd_TextBox_GetLineNumber(Ft_Esd_TextBox *context, const char *s);

void Ft_Esd_TextBox_Update(Ft_Esd_TextBox *context)
{
	void *owner = context->Owner;
	ft_uint16_t left = context->AlignX(owner);
	ft_uint16_t right = OPT_ALIGN_CENTER;
	int update_variable = left == right;
	context->isCenterX = update_variable;
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void Ft_Esd_TextBox_Render(Ft_Esd_TextBox *context)
{
	void *owner = context->Owner;
	Ft_Esd_Theme * theme = context->Theme(owner);
	ft_int16_t x = context->Widget.GlobalX;
	ft_int16_t y = context->Widget.GlobalY;
	ft_int16_t width = context->Widget.GlobalWidth;
	ft_int16_t height = context->Widget.GlobalHeight;
	int inputRadius = context->Radius;
	int radius = Ft_Esd_TextBox_RadiusValue(context, inputRadius);
	ft_bool_t raised = context->Raised;
	Ft_Esd_Elements_Panel(theme, x, y, width, height, radius, raised);
	ft_argb32_t c_1 = 0xffffffffUL;
	Ft_Esd_Dl_COLOR_ARGB(c_1);
	Ft_Esd_TextBox_Set_Fill_Width(context);
	EVE_HalContext * phost = Ft_Esd_GetHost();
	ft_uint16_t value = context->AlignX(owner);
	ft_int16_t left_1;
	switch (value)
	{
		case 0L:
		{
			left_1 = context->Widget.GlobalX;
			break;
		}
		case 1L:
		{
			ft_int16_t left_2 = context->Widget.GlobalX;
			ft_int16_t left_3 = context->Widget.GlobalWidth;
			int right_2 = 2L;
			int right_1 = left_3 / right_2;
			left_1 = left_2 + right_1;
			break;
		}
		case 2L:
		{
			ft_int16_t left_4 = context->Widget.GlobalX;
			ft_int16_t right_3 = context->Widget.GlobalWidth;
			left_1 = left_4 + right_3;
			break;
		}
		default:
		{
			left_1 = 0;
			break;
		}
	}
	int right_4 = context->AdjustX;
	int x_1 = left_1 + right_4;
	ft_uint16_t value_1 = context->AlignY(owner);
	ft_int16_t left_5;
	switch (value_1)
	{
		case 0L:
		{
			left_5 = context->Widget.GlobalY;
			break;
		}
		case 1L:
		{
			ft_int16_t left_8 = context->Widget.GlobalY;
			ft_int16_t left_9 = context->Widget.GlobalHeight;
			int right_6 = 2L;
			int right_5 = left_9 / right_6;
			int left_7 = left_8 + right_5;
			uint16_t left_11 = Ft_Esd_TextBox_Get_Font_Height__return(context);
			cstring s = context->Text(owner);
			int right_8 = Ft_Esd_TextBox_GetLineNumber(context, s);
			int left_10 = left_11 * right_8;
			int right_9 = 2L;
			int right_7 = left_10 / right_9;
			int left_6 = left_7 - right_7;
			uint16_t left_12 = Ft_Esd_TextBox_Get_Font_Height__return(context);
			int right_11 = 2L;
			int right_10 = left_12 / right_11;
			left_5 = left_6 + right_10;
			break;
		}
		case 2L:
		{
			ft_int16_t left_14 = context->Widget.GlobalY;
			ft_int16_t right_12 = context->Widget.GlobalHeight;
			int left_13 = left_14 + right_12;
			uint16_t left_16 = Ft_Esd_TextBox_Get_Font_Height__return(context);
			cstring s_1 = context->Text(owner);
			int right_14 = Ft_Esd_TextBox_GetLineNumber(context, s_1);
			int left_15 = left_16 * right_14;
			uint16_t right_15 = Ft_Esd_TextBox_Get_Font_Height__return(context);
			int right_13 = left_15 - right_15;
			left_5 = left_13 - right_13;
			break;
		}
		default:
		{
			left_5 = 0;
			break;
		}
	}
	int right_16 = context->AdjustY;
	int y_1 = left_5 + right_16;
	Esd_FontInfo * if_1 = context->FontResource(owner);
	Esd_FontInfo *fontInfo;
	if (if_1)
	{
		fontInfo = context->FontResource(owner);
	}
	else
	{
		uint8_t i = context->Font(owner);
		fontInfo = Esd_GetRomFont(i);
	}
	uint8_t font = Ft_Esd_Dl_Font_Setup(fontInfo);
	ft_uint16_t left_19 = context->AlignX(owner);
	ft_uint16_t right_17 = OPT_ALIGN_LEFT;
	int if_2 = left_19 == right_17;
	uint16_t left_18;
	if (if_2)
	{
		left_18 = 0;
	}
	else
	{
		ft_uint16_t left_20 = context->AlignX(owner);
		ft_uint16_t right_18 = OPT_ALIGN_RIGHT;
		int if_3 = left_20 == right_18;
		if (if_3)
		{
			left_18 = OPT_RIGHTX;
		}
		else
		{
			left_18 = OPT_CENTERX;
		}
	}
	ft_uint16_t left_21 = context->AlignY(owner);
	ft_uint16_t right_20 = OPT_ALIGN_CENTER;
	int if_4 = left_21 == right_20;
	uint16_t right_19;
	if (if_4)
	{
		right_19 = OPT_CENTERY;
	}
	else
	{
		right_19 = 0;
	}
	uint16_t left_17 = left_18 | right_19;
	uint16_t right_21 = OPT_FILL;
	uint16_t options = left_17 | right_21;
	ft_uint16_t left_22 = context->AlignY(owner);
	ft_uint16_t right_22 = OPT_ALIGN_BOTTOM;
	int bottom = left_22 == right_22;
	Esd_FontInfo * if_5 = context->FontResource(owner);
	Esd_FontInfo *fontInfo_1;
	if (if_5)
	{
		fontInfo_1 = context->FontResource(owner);
	}
	else
	{
		uint8_t i_1 = context->Font(owner);
		fontInfo_1 = Esd_GetRomFont(i_1);
	}
	uint16_t baseLine = Esd_GetFontBaseLine(fontInfo_1);
	Esd_FontInfo * if_6 = context->FontResource(owner);
	Esd_FontInfo *fontInfo_2;
	if (if_6)
	{
		fontInfo_2 = context->FontResource(owner);
	}
	else
	{
		uint8_t i_2 = context->Font(owner);
		fontInfo_2 = Esd_GetRomFont(i_2);
	}
	uint16_t capsHeight = Esd_GetFontCapsHeight(fontInfo_2);
	Esd_FontInfo * if_7 = context->FontResource(owner);
	Esd_FontInfo *fontInfo_3;
	if (if_7)
	{
		fontInfo_3 = context->FontResource(owner);
	}
	else
	{
		uint8_t i_3 = context->Font(owner);
		fontInfo_3 = Esd_GetRomFont(i_3);
	}
	uint16_t xOffset = Esd_GetFontXOffset(fontInfo_3);
	cstring s_2 = context->Text(owner);
	Ft_Gpu_CoCmd_Text_Ex(phost, x_1, y_1, font, options, bottom, baseLine, capsHeight, xOffset, s_2);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

uint16_t Ft_Esd_TextBox_Get_Font_Height__return(Ft_Esd_TextBox *context)
{
	void *owner = context->Owner;
	Esd_FontInfo * if_8 = context->FontResource(owner);
	Esd_FontInfo *fontInfo_4;
	if (if_8)
	{
		fontInfo_4 = context->FontResource(owner);
	}
	else
	{
		uint8_t i_4 = context->Font(owner);
		fontInfo_4 = Esd_GetRomFont(i_4);
	}
	return Esd_GetFontHeight(fontInfo_4);
}

static int Ft_Esd_TextBox_RadiusValue(Ft_Esd_TextBox *context, ft_int32_t inputRadius)
{
	void *owner = context->Owner;
	if (inputRadius == 0)
	return 1;
	else
	return inputRadius;
}

static int Ft_Esd_TextBox_GetLineNumber(Ft_Esd_TextBox *context, const char *s)
{
	void *owner = context->Owner;
	int line = 1;
	while(*s)
	{
	    if(*s == '\n')
	   {
	        line++;
	   }
	   s++;
	}
	return line;
}


/* end of file */
