/*
This file is automatically generated
Ft_Esd_Theme_DarkOrange
C Source
*/

#include "Ft_Esd_Theme_DarkOrange.h"

static Ft_Esd_Theme Ft_Esd_Theme_DarkOrange__Instance = {
	.ClearColor = 0xff212121,
	.BackColor = 0x151515,
	.TextColor = 0xffffffff,
	.ButtonTextColor = 0xffffffff,
	.DefaultColor = 0xff6b6b6b,
	.PrimaryColor = 0xffff7f3f,
};

Ft_Esd_Theme *Ft_Esd_Theme_DarkOrange()
{
	return &Ft_Esd_Theme_DarkOrange__Instance;
}

/* end of file */
