/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_RingSlider
C Source
*/

/*
Comment :
Introduction:
This widget acts the same as a Slider Bar. But instead of sliding in a bar, it slides in a arc line.
Arc Slider supports touch input.
*/

/*
Comment 2 :
Partial Ring is used as a widget base.
*/

#include "Ft_Esd_RingSlider.h"

#include "Esd_Context.h"
#include "EVE_CoDl.h"
#include "Esd_Core.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
ft_bool_t Ft_Esd_RingSlider_Clockwise__Default(void *context) { return 1; }
int Ft_Esd_RingSlider_Origin__Default(void *context) { return 135L; }
int Ft_Esd_RingSlider_RingWidth__Default(void *context) { return 50L; }
int Ft_Esd_RingSlider_InnerBorder__Default(void *context) { return 1L; }
int Ft_Esd_RingSlider_OuterBorder__Default(void *context) { return 1L; }
ft_argb32_t Ft_Esd_RingSlider_BorderColor__Default(void *context) { return 0xffd0cec6UL; }
ft_argb32_t Ft_Esd_RingSlider_SelectionColor__Default(void *context) { return 0xff0055ffUL; }
ft_argb32_t Ft_Esd_RingSlider_BackgroundColor__Default(void *context) { return 0xff646464UL; }
ft_argb32_t Ft_Esd_RingSlider_KnobColor__Default(void *context) { return 0xfff7f7f7UL; }
int Ft_Esd_RingSlider_KnobRadius__Default(void *context) { return 25L; }

static ft_int16_t Ft_Esd_RingSlider_ESD_Partial_Ring_Angle__Property(void *context);
static ft_int16_t Ft_Esd_RingSlider_ESD_Partial_Ring_MaxAngle__Property(void *context);
static ft_bool_t Ft_Esd_RingSlider_ESD_Partial_Ring_Clockwise__Property(void *context);
static int Ft_Esd_RingSlider_ESD_Partial_Ring_Origin__Property(void *context);
static int Ft_Esd_RingSlider_ESD_Partial_Ring_RingWidth__Property(void *context);
static int Ft_Esd_RingSlider_ESD_Partial_Ring_InnerBorder__Property(void *context);
static int Ft_Esd_RingSlider_ESD_Partial_Ring_OuterBorder__Property(void *context);
static ft_argb32_t Ft_Esd_RingSlider_ESD_Partial_Ring_BorderColor__Property(void *context);
static ft_argb32_t Ft_Esd_RingSlider_ESD_Partial_Ring_SelectionColor__Property(void *context);
static ft_argb32_t Ft_Esd_RingSlider_ESD_Partial_Ring_BackgroundColor__Property(void *context);

static Ft_Esd_WidgetSlots s_Ft_Esd_RingSlider__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_RingSlider_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_RingSlider_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_RingSlider_End,
};

static void Ft_Esd_RingSlider_Touch_Tag_2_Down__Signal(void *context);
static void Ft_Esd_RingSlider_Touch_Tag_2_Up__Signal(void *context);
static void Ft_Esd_RingSlider_Render_Forwarder_ForwardUpdate__Signal(void *context);
static void Ft_Esd_RingSlider_Render_Forwarder_ForwardRender__Signal(void *context);

void Ft_Esd_RingSlider__Touch_Tag_2__Initializer(Ft_Esd_RingSlider *context)
{
	Esd_TouchTag *object = (Esd_TouchTag *)&context->Touch_Tag_2;
	Esd_TouchTag__Initializer(object);
	object->Owner = (void *)context;
	object->Down = Ft_Esd_RingSlider_Touch_Tag_2_Down__Signal;
	object->Up = Ft_Esd_RingSlider_Touch_Tag_2_Up__Signal;
}

void Ft_Esd_RingSlider__Render_Forwarder__Initializer(Ft_Esd_RingSlider *context)
{
	Ft_Esd_RenderForwarder *object = (Ft_Esd_RenderForwarder *)&context->Render_Forwarder;
	Ft_Esd_RenderForwarder__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->ForwardUpdate = Ft_Esd_RingSlider_Render_Forwarder_ForwardUpdate__Signal;
	object->ForwardRender = Ft_Esd_RingSlider_Render_Forwarder_ForwardRender__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Ft_Esd_RingSlider__Fixed_Positioning__Initializer(Ft_Esd_RingSlider *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Positioning;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 344;
	object->Widget.LocalY = 212;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Ft_Esd_RingSlider__ESD_Partial_Ring__Initializer(Ft_Esd_RingSlider *context)
{
	Ft_Esd_PartialRing *object = (Ft_Esd_PartialRing *)&context->ESD_Partial_Ring;
	Ft_Esd_PartialRing__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 579;
	object->Widget.LocalHeight = 469;
	object->Angle = Ft_Esd_RingSlider_ESD_Partial_Ring_Angle__Property;
	object->MaxAngle = Ft_Esd_RingSlider_ESD_Partial_Ring_MaxAngle__Property;
	object->Clockwise = Ft_Esd_RingSlider_ESD_Partial_Ring_Clockwise__Property;
	object->Origin = Ft_Esd_RingSlider_ESD_Partial_Ring_Origin__Property;
	object->RingWidth = Ft_Esd_RingSlider_ESD_Partial_Ring_RingWidth__Property;
	object->InnerBorder = Ft_Esd_RingSlider_ESD_Partial_Ring_InnerBorder__Property;
	object->OuterBorder = Ft_Esd_RingSlider_ESD_Partial_Ring_OuterBorder__Property;
	object->BorderColor = Ft_Esd_RingSlider_ESD_Partial_Ring_BorderColor__Property;
	object->SelectionColor = Ft_Esd_RingSlider_ESD_Partial_Ring_SelectionColor__Property;
	object->BackgroundColor = Ft_Esd_RingSlider_ESD_Partial_Ring_BackgroundColor__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Positioning);
}

void Ft_Esd_RingSlider__Initializer(Ft_Esd_RingSlider *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_RingSlider_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_RingSlider__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->Angle = 90;
	context->Max_Angle = 270;
	context->Clockwise = Ft_Esd_RingSlider_Clockwise__Default;
	context->Origin = Ft_Esd_RingSlider_Origin__Default;
	context->RingWidth = Ft_Esd_RingSlider_RingWidth__Default;
	context->InnerBorder = Ft_Esd_RingSlider_InnerBorder__Default;
	context->OuterBorder = Ft_Esd_RingSlider_OuterBorder__Default;
	context->StartAngle = 0L;
	context->BorderColor = Ft_Esd_RingSlider_BorderColor__Default;
	context->ClampedNewAngle = 50L;
	context->NewAngle = 0L;
	context->SelectionColor = Ft_Esd_RingSlider_SelectionColor__Default;
	context->TrackAngle = 0L;
	context->BackgroundColor = Ft_Esd_RingSlider_BackgroundColor__Default;
	context->StartTrackAngle = 0L;
	context->IsTracking = 0;
	context->Value = 10;
	context->MaxValue = 100;
	context->KnobColor = Ft_Esd_RingSlider_KnobColor__Default;
	context->IsOutOfBound = 0;
	context->KnobRadius = Ft_Esd_RingSlider_KnobRadius__Default;
	Ft_Esd_RingSlider__Touch_Tag_2__Initializer(context);
	Ft_Esd_RingSlider__Render_Forwarder__Initializer(context);
	Ft_Esd_RingSlider__Fixed_Positioning__Initializer(context);
	Ft_Esd_RingSlider__ESD_Partial_Ring__Initializer(context);
}

void Ft_Esd_Circle_Render_Func(Ft_Esd_RingSlider *context, int, int, int, int, int, int, int, int, bool, ft_argb32_t);
void Ft_Esd_RingSlider_Update_TouchTracker(Ft_Esd_RingSlider *context, ft_int16_t);

void Ft_Esd_RingSlider_Start(Ft_Esd_RingSlider *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context);
	Esd_TouchTag_Start(&context->Touch_Tag_2);
}

void Ft_Esd_RingSlider_Update(Ft_Esd_RingSlider *context)
{
	void *owner = context->Owner;
	ft_int16_t update_variable = context->ESD_Partial_Ring.Angle(context->ESD_Partial_Ring.Owner);
	context->Angle = update_variable;
	Esd_TouchTag_Update(&context->Touch_Tag_2);
	ft_int16_t update_variable_1 = Ft_Esd_RenderForwarder_GlobalWidth(&context->Render_Forwarder);
	Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)&context->Fixed_Positioning, update_variable_1);
	ft_int16_t update_variable_2 = Ft_Esd_RenderForwarder_GlobalHeight(&context->Render_Forwarder);
	Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)&context->Fixed_Positioning, update_variable_2);
	ft_int16_t update_variable_3 = Ft_Esd_RenderForwarder_GlobalWidth(&context->Render_Forwarder);
	Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)&context->ESD_Partial_Ring, update_variable_3);
	ft_int16_t update_variable_4 = Ft_Esd_RenderForwarder_GlobalHeight(&context->Render_Forwarder);
	Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)&context->ESD_Partial_Ring, update_variable_4);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void Ft_Esd_RingSlider_End(Ft_Esd_RingSlider *context)
{
	void *owner = context->Owner;
	Esd_TouchTag_End(&context->Touch_Tag_2);
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Render_Forwarder); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Positioning); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Partial_Ring); 
}

void Ft_Esd_RingSlider_Touch_Tag_2_Down__Signal(void *c)
{
	Ft_Esd_RingSlider *context = (Ft_Esd_RingSlider *)c;
	void *owner = context->Owner;
	ft_bool_t reset_variable = 0;
	context->IsTracking = reset_variable;
	context->IsOutOfBound = reset_variable;
	int reset_variable_2 = context->ClampedNewAngle;
	context->NewAngle = reset_variable_2;
}

void Ft_Esd_RingSlider_Touch_Tag_2_Up__Signal(void *c)
{
	Ft_Esd_RingSlider *context = (Ft_Esd_RingSlider *)c;
	void *owner = context->Owner;
	ft_bool_t reset_variable_1 = 0;
	context->IsTracking = reset_variable_1;
	context->IsOutOfBound = reset_variable_1;
	int reset_variable_2_1 = context->ClampedNewAngle;
	context->NewAngle = reset_variable_2_1;
}

void Ft_Esd_RingSlider_Render_Forwarder_ForwardUpdate__Signal(void *c)
{
	Ft_Esd_RingSlider *context = (Ft_Esd_RingSlider *)c;
	void *owner = context->Owner;
	bool if_1 = Esd_TouchTag_Touching(&context->Touch_Tag_2);
	if (if_1)
	{
		ft_int16_t left_1 = context->Angle;
		ft_int16_t right = context->MaxValue;
		int left = left_1 * right;
		ft_int16_t right_1 = context->Max_Angle;
		int set_value_from_angle = left / right_1;
		context->Value = (int)set_value_from_angle;
	}
	else
	{
		ft_int16_t left_3 = context->Max_Angle;
		ft_int16_t right_2 = context->Value;
		int left_2 = left_3 * right_2;
		ft_int16_t right_3 = context->MaxValue;
		int set_intial_angle = left_2 / right_3;
		context->ClampedNewAngle = set_intial_angle;
	}
}

void Ft_Esd_RingSlider_Render_Forwarder_ForwardRender__Signal(void *c)
{
	Ft_Esd_RingSlider *context = (Ft_Esd_RingSlider *)c;
	void *owner = context->Owner;
	bool if_2 = Esd_TouchTag_Touching(&context->Touch_Tag_2);
	if (if_2)
	{
		uint8_t tag = Esd_TouchTag_Tag(&context->Touch_Tag_2);
		Ft_Esd_RingSlider_Update_TouchTracker(context, tag);
	}
	else
	{
	}
	EVE_HalContext * phost = Esd_GetHost();
	uint8_t s = Esd_TouchTag_Tag(&context->Touch_Tag_2);
	EVE_CoDl_tag(phost, s);
	ft_int16_t x = Ft_Esd_RenderForwarder_GlobalX(&context->Render_Forwarder);
	ft_int16_t y = Ft_Esd_RenderForwarder_GlobalY(&context->Render_Forwarder);
	ft_int16_t width = Ft_Esd_RenderForwarder_GlobalWidth(&context->Render_Forwarder);
	ft_int16_t height = Ft_Esd_RenderForwarder_GlobalHeight(&context->Render_Forwarder);
	int radius = context->KnobRadius(owner);
	int origin = context->Origin(owner);
	ft_int16_t angle = context->ESD_Partial_Ring.Angle(context->ESD_Partial_Ring.Owner);
	int ringWidth = context->RingWidth(owner);
	ft_bool_t clockwise = context->Clockwise(owner);
	ft_argb32_t color = context->KnobColor(owner);
	Ft_Esd_Circle_Render_Func(context, x, y, width, height, radius, origin, angle, ringWidth, clockwise, color);
}

ft_int16_t Ft_Esd_RingSlider_ESD_Partial_Ring_Angle__Property(void *c)
{
	Ft_Esd_RingSlider *context = (Ft_Esd_RingSlider *)c;
	void *owner = context->Owner;
	return context->ClampedNewAngle;
}

ft_int16_t Ft_Esd_RingSlider_ESD_Partial_Ring_MaxAngle__Property(void *c)
{
	Ft_Esd_RingSlider *context = (Ft_Esd_RingSlider *)c;
	void *owner = context->Owner;
	return context->Max_Angle;
}

ft_bool_t Ft_Esd_RingSlider_ESD_Partial_Ring_Clockwise__Property(void *c)
{
	Ft_Esd_RingSlider *context = (Ft_Esd_RingSlider *)c;
	void *owner = context->Owner;
	return context->Clockwise(owner);
}

int Ft_Esd_RingSlider_ESD_Partial_Ring_Origin__Property(void *c)
{
	Ft_Esd_RingSlider *context = (Ft_Esd_RingSlider *)c;
	void *owner = context->Owner;
	return context->Origin(owner);
}

int Ft_Esd_RingSlider_ESD_Partial_Ring_RingWidth__Property(void *c)
{
	Ft_Esd_RingSlider *context = (Ft_Esd_RingSlider *)c;
	void *owner = context->Owner;
	return context->RingWidth(owner);
}

int Ft_Esd_RingSlider_ESD_Partial_Ring_InnerBorder__Property(void *c)
{
	Ft_Esd_RingSlider *context = (Ft_Esd_RingSlider *)c;
	void *owner = context->Owner;
	return context->InnerBorder(owner);
}

int Ft_Esd_RingSlider_ESD_Partial_Ring_OuterBorder__Property(void *c)
{
	Ft_Esd_RingSlider *context = (Ft_Esd_RingSlider *)c;
	void *owner = context->Owner;
	return context->OuterBorder(owner);
}

ft_argb32_t Ft_Esd_RingSlider_ESD_Partial_Ring_BorderColor__Property(void *c)
{
	Ft_Esd_RingSlider *context = (Ft_Esd_RingSlider *)c;
	void *owner = context->Owner;
	ft_bool_t value = context->IsOutOfBound;
	switch (value)
	{
		case 0L:
		{
			bool value_1 = Esd_TouchTag_Touching(&context->Touch_Tag_2);
			switch (value_1)
			{
				case 0L:
				{
					return context->BorderColor(owner);
				}
				case 1L:
				{
					ft_argb32_t left_4 = context->ESD_Partial_Ring.SelectionColor(context->ESD_Partial_Ring.Owner);
					ft_argb32_t right_4 = 0xff212121UL;
					ft_argb32_t color_1 = ((left_4 >> 8) & 0x00ff00ff) + ((right_4 >> 8) & 0x00ff00ff);
					ft_argb32_t color_2 = (left_4 & 0x00ff00ff) + (right_4 & 0x00ff00ff);
					return (((color_1 & 0x00ff00ff) << 8) | ((color_1 & 0x01000100) * 0xff)) | ((color_2 & 0x00ff00ff) | (((color_2 & 0x01000100) * 0xff) >> 8));
				}
				default:
				{
					return context->BorderColor(owner);
				}
			}
		}
		case 1L:
		{
			ft_argb32_t left_5 = context->ESD_Partial_Ring.SelectionColor(context->ESD_Partial_Ring.Owner);
			ft_argb32_t right_5 = 0xff141414UL;
			ft_argb32_t color_3 = (((left_5 >> 8) & 0x00ff00ff) | 0x01000100) - ((right_5 >> 8) & 0x00ff00ff);
			ft_argb32_t color_4 = ((left_5 & 0x00ff00ff) | 0x01000100) - (right_5 & 0x00ff00ff);
			return (((color_3 & 0x00ff00ff) << 8) & ((color_3 & 0x01000100) * 0xff)) | ((color_4 & 0x00ff00ff) & (((color_4 & 0x01000100) * 0xff) >> 8));
		}
		default:
		{
			bool value_2 = Esd_TouchTag_Touching(&context->Touch_Tag_2);
			switch (value_2)
			{
				case 0L:
				{
					return context->BorderColor(owner);
				}
				case 1L:
				{
					ft_argb32_t left_6 = context->ESD_Partial_Ring.SelectionColor(context->ESD_Partial_Ring.Owner);
					ft_argb32_t right_6 = 0xff212121UL;
					ft_argb32_t color_5 = ((left_6 >> 8) & 0x00ff00ff) + ((right_6 >> 8) & 0x00ff00ff);
					ft_argb32_t color_6 = (left_6 & 0x00ff00ff) + (right_6 & 0x00ff00ff);
					return (((color_5 & 0x00ff00ff) << 8) | ((color_5 & 0x01000100) * 0xff)) | ((color_6 & 0x00ff00ff) | (((color_6 & 0x01000100) * 0xff) >> 8));
				}
				default:
				{
					return context->BorderColor(owner);
				}
			}
		}
	}
}

ft_argb32_t Ft_Esd_RingSlider_ESD_Partial_Ring_SelectionColor__Property(void *c)
{
	Ft_Esd_RingSlider *context = (Ft_Esd_RingSlider *)c;
	void *owner = context->Owner;
	return context->SelectionColor(owner);
}

ft_argb32_t Ft_Esd_RingSlider_ESD_Partial_Ring_BackgroundColor__Property(void *c)
{
	Ft_Esd_RingSlider *context = (Ft_Esd_RingSlider *)c;
	void *owner = context->Owner;
	return context->BackgroundColor(owner);
}


/* end of file */
