/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_PosSizeToRadius
C Source
*/

#include "Ft_Esd_PosSizeToRadius.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
ft_int16_t Ft_Esd_PosSizeToRadius_X__Default(void *context) { return 0; }
ft_int16_t Ft_Esd_PosSizeToRadius_Y__Default(void *context) { return 0; }
ft_int16_t Ft_Esd_PosSizeToRadius_Width__Default(void *context) { return 0; }
ft_int16_t Ft_Esd_PosSizeToRadius_Height__Default(void *context) { return 0; }



void Ft_Esd_PosSizeToRadius__Initializer(Ft_Esd_PosSizeToRadius *context)
{
	context->Owner = 0;
	context->X = Ft_Esd_PosSizeToRadius_X__Default;
	context->Y = Ft_Esd_PosSizeToRadius_Y__Default;
	context->Width = Ft_Esd_PosSizeToRadius_Width__Default;
	context->Height = Ft_Esd_PosSizeToRadius_Height__Default;
}

ft_int16_t Ft_Esd_PosSizeToRadius_Radius(Ft_Esd_PosSizeToRadius *context)
{
	void *owner = context->Owner;
	ft_int16_t left_1 = context->Width(owner);
	ft_int16_t right = 2;
	ft_int16_t left = left_1 / right;
	ft_int16_t left_2 = context->Height(owner);
	ft_int16_t right_2 = 2;
	ft_int16_t right_1 = left_2 / right_2;
	int if_1 = left > right_1;
	if (if_1)
	{
		ft_int16_t left_3 = context->Height(owner);
		ft_int16_t right_3 = 2;
		return left_3 / right_3;
	}
	else
	{
		ft_int16_t left_4 = context->Width(owner);
		ft_int16_t right_4 = 2;
		return left_4 / right_4;
	}
}

ft_int16_t Ft_Esd_PosSizeToRadius_CenterX(Ft_Esd_PosSizeToRadius *context)
{
	void *owner = context->Owner;
	ft_int16_t left_5 = context->X(owner);
	ft_int16_t left_6 = context->Width(owner);
	ft_int16_t right_6 = 2;
	ft_int16_t right_5 = left_6 / right_6;
	return left_5 + right_5;
}

ft_int16_t Ft_Esd_PosSizeToRadius_CenterY(Ft_Esd_PosSizeToRadius *context)
{
	void *owner = context->Owner;
	ft_int16_t left_7 = context->Y(owner);
	ft_int16_t left_8 = context->Height(owner);
	ft_int16_t right_8 = 2;
	ft_int16_t right_7 = left_8 / right_8;
	return left_7 + right_7;
}


/* end of file */
