/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_Clock
C Source
*/

/*
Comment :
Introduction:
This widget draws a analog clock.
All of its hands can be set.
Co-processor command CMD_CLOCK is used internally.
*/

#include "Ft_Esd_Clock.h"

#include "Esd_Context.h"
#include "Ft_Esd_CoCmd.h"
#include "Ft_Esd_Dl.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
Ft_Esd_Theme * Ft_Esd_Clock_Theme__Default(void *context) { return Ft_Esd_Theme_GetCurrent(); }
ft_uint8_t Ft_Esd_Clock_Alpha__Default(void *context) { return 255; }
ft_uint16_t Ft_Esd_Clock_H__Default(void *context) { return 0U; }
ft_uint16_t Ft_Esd_Clock_M__Default(void *context) { return 0U; }
ft_uint16_t Ft_Esd_Clock_S__Default(void *context) { return 0U; }
ft_uint32_t Ft_Esd_Clock_Ms__Default(void *context) { return 0UL; }
ft_bool_t Ft_Esd_Clock_Interactive__Default(void *context) { return 0; }
ft_bool_t Ft_Esd_Clock_ShowBackground__Default(void *context) { return 1; }

static ft_int16_t Ft_Esd_Clock_Ft_Esd_PosSizeToRadius_X__Property(void *context);
static ft_int16_t Ft_Esd_Clock_Ft_Esd_PosSizeToRadius_Y__Property(void *context);
static ft_int16_t Ft_Esd_Clock_Ft_Esd_PosSizeToRadius_Width__Property(void *context);
static ft_int16_t Ft_Esd_Clock_Ft_Esd_PosSizeToRadius_Height__Property(void *context);

static Ft_Esd_WidgetSlots s_Ft_Esd_Clock__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Clock_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Clock_Update,
	(void(*)(void *))Ft_Esd_Clock_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Clock_End,
};


void Ft_Esd_Clock__Ft_Esd_PosSizeToRadius__Initializer(Ft_Esd_Clock *context)
{
	Ft_Esd_PosSizeToRadius *object = (Ft_Esd_PosSizeToRadius *)&context->Ft_Esd_PosSizeToRadius;
	Ft_Esd_PosSizeToRadius__Initializer(object);
	object->Owner = (void *)context;
	object->X = Ft_Esd_Clock_Ft_Esd_PosSizeToRadius_X__Property;
	object->Y = Ft_Esd_Clock_Ft_Esd_PosSizeToRadius_Y__Property;
	object->Width = Ft_Esd_Clock_Ft_Esd_PosSizeToRadius_Width__Property;
	object->Height = Ft_Esd_Clock_Ft_Esd_PosSizeToRadius_Height__Property;
}

void Ft_Esd_Clock__Touch_Tag__Initializer(Ft_Esd_Clock *context)
{
	Ft_Esd_TouchTag *object = (Ft_Esd_TouchTag *)&context->Touch_Tag;
	Ft_Esd_TouchTag__Initializer(object);
	object->Owner = (void *)context;
}

void Ft_Esd_Clock__Initializer(Ft_Esd_Clock *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_Clock_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_Clock__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 80;
	context->Widget.LocalHeight = 80;
	context->Theme = Ft_Esd_Clock_Theme__Default;
	Ft_Esd_Clock__Ft_Esd_PosSizeToRadius__Initializer(context);
	context->Alpha = Ft_Esd_Clock_Alpha__Default;
	context->H = Ft_Esd_Clock_H__Default;
	context->M = Ft_Esd_Clock_M__Default;
	context->S = Ft_Esd_Clock_S__Default;
	context->Ms = Ft_Esd_Clock_Ms__Default;
	context->Interactive = Ft_Esd_Clock_Interactive__Default;
	context->AutoResize = ESD_AUTORESIZE_NONE;
	context->ShowBackground = Ft_Esd_Clock_ShowBackground__Default;
	Ft_Esd_Clock__Touch_Tag__Initializer(context);
}


void Ft_Esd_Clock_Start(Ft_Esd_Clock *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context);
	Ft_Esd_TouchTag_Start(&context->Touch_Tag);
}

void Ft_Esd_Clock_End(Ft_Esd_Clock *context)
{
	void *owner = context->Owner;
	Ft_Esd_TouchTag_End(&context->Touch_Tag);
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
}

void Ft_Esd_Clock_Render(Ft_Esd_Clock *context)
{
	void *owner = context->Owner;
	ft_uint8_t alpha = context->Alpha(owner);
	Ft_Esd_Dl_COLOR_A(alpha);
	EVE_HalContext * phost = Ft_Esd_GetHost();
	Ft_Esd_Theme * theme = context->Theme(owner);
	ft_argb32_t c_1 = Ft_Esd_Theme_GetBackColor(theme);
	Ft_Gpu_CoCmd_BgColor(phost, c_1);
	ft_bool_t left = Ft_Esd_TouchTag_Touching(&context->Touch_Tag);
	ft_bool_t right = context->Interactive(owner);
	ft_bool_t if_1 = left & right;
	ft_uint32_t c_2;
	if (if_1)
	{
		Ft_Esd_Theme * theme_1 = context->Theme(owner);
		c_2 = Ft_Esd_Theme_GetPrimaryColor(theme_1);
	}
	else
	{
		Ft_Esd_Theme * theme_2 = context->Theme(owner);
		c_2 = Ft_Esd_Theme_GetTextColor(theme_2);
	}
	Ft_Esd_Dl_COLOR_RGB(c_2);
	ft_uint8_t s = Ft_Esd_TouchTag_Tag(&context->Touch_Tag);
	Ft_Esd_Dl_TAG(s);
	EVE_HalContext * phost_1 = Ft_Esd_GetHost();
	ft_int16_t x = Ft_Esd_PosSizeToRadius_CenterX(&context->Ft_Esd_PosSizeToRadius);
	ft_int16_t y = Ft_Esd_PosSizeToRadius_CenterY(&context->Ft_Esd_PosSizeToRadius);
	ft_int16_t r = Ft_Esd_PosSizeToRadius_Radius(&context->Ft_Esd_PosSizeToRadius);
	ft_bool_t if_2 = context->ShowBackground(owner);
	uint16_t options;
	if (if_2)
	{
		options = 0;
	}
	else
	{
		options = OPT_NOBACK;
	}
	ft_uint16_t height = context->H(owner);
	ft_uint16_t m = context->M(owner);
	ft_uint16_t left_1 = context->S(owner);
	ft_uint32_t left_2 = context->Ms(owner);
	ft_uint32_t right_2 = 1000UL;
	ft_uint32_t right_1 = left_2 / right_2;
	ft_uint32_t s_1 = left_1 + right_1;
	ft_uint32_t left_3 = context->Ms(owner);
	ft_uint32_t right_3 = 1000UL;
	ft_uint32_t ms = left_3 % right_3;
	Ft_Gpu_CoCmd_Clock(phost_1, x, y, r, options, height, m, s_1, ms);
	ft_uint8_t s_2 = 255;
	Ft_Esd_Dl_TAG(s_2);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

ft_int16_t Ft_Esd_Clock_Ft_Esd_PosSizeToRadius_X__Property(void *c)
{
	Ft_Esd_Clock *context = (Ft_Esd_Clock *)c;
	void *owner = context->Owner;
	return context->Widget.GlobalX;
}

ft_int16_t Ft_Esd_Clock_Ft_Esd_PosSizeToRadius_Y__Property(void *c)
{
	Ft_Esd_Clock *context = (Ft_Esd_Clock *)c;
	void *owner = context->Owner;
	return context->Widget.GlobalY;
}

ft_int16_t Ft_Esd_Clock_Ft_Esd_PosSizeToRadius_Width__Property(void *c)
{
	Ft_Esd_Clock *context = (Ft_Esd_Clock *)c;
	void *owner = context->Owner;
	return context->Widget.GlobalWidth;
}

ft_int16_t Ft_Esd_Clock_Ft_Esd_PosSizeToRadius_Height__Property(void *c)
{
	Ft_Esd_Clock *context = (Ft_Esd_Clock *)c;
	void *owner = context->Owner;
	return context->Widget.GlobalHeight;
}

void Ft_Esd_Clock_Update(Ft_Esd_Clock *context)
{
	void *owner = context->Owner;
	ft_uint8_t left_4 = context->AutoResize;
	ft_uint8_t right_4 = ESD_AUTORESIZE_HEIGHT;
	ft_uint8_t if_3 = left_4 & right_4;
	if (if_3)
	{
		ft_int16_t left_5 = context->Widget.GlobalHeight;
		ft_int16_t right_5 = context->Widget.GlobalWidth;
		int if_4 = left_5 > right_5;
		if (if_4)
		{
			ft_int16_t set_height_to_width = context->Widget.GlobalWidth;
			Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)context, set_height_to_width);
		}
		else
		{
		}
	}
	else
	{
	}
	ft_uint8_t left_6 = context->AutoResize;
	ft_uint8_t right_6 = ESD_AUTORESIZE_WIDTH;
	ft_uint8_t if_5 = left_6 & right_6;
	if (if_5)
	{
		ft_int16_t left_7 = context->Widget.GlobalWidth;
		ft_int16_t right_7 = context->Widget.GlobalHeight;
		int if_6 = (left_7 << 2) > (right_7 << 2);
		if (if_6)
		{
			ft_int16_t set_width_to_height = context->Widget.GlobalHeight;
			Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)context, set_width_to_height);
		}
		else
		{
		}
	}
	else
	{
	}
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context); 
}


/* end of file */
