/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_Label
C Source
*/

/*
Comment :
Introduction:
This widget shows a text.
Font type and font size can be changed.
The content is taken from "Text" property.
*/

#include "Ft_Esd_Label.h"

#include "Esd_Context.h"
#include "Esd_BitmapHandle.h"
#include "Esd_Core.h"
#include "Ft_Esd_BitmapHandle.h"
#include "Ft_Esd_CoCmd.h"
#include "Ft_Esd_Dl.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
ft_uint8_t Ft_Esd_Label_Alpha__Default(void *context) { return 255; }
Ft_Esd_Theme * Ft_Esd_Label_Theme__Default(void *context) { return Ft_Esd_Theme_GetCurrent(); }
uint8_t Ft_Esd_Label_Font__Default(void *context) { return 27; }
Esd_FontInfo * Ft_Esd_Label_FontResource__Default(void *context) { return 0; }
const char * Ft_Esd_Label_Text__Default(void *context) { return "Label"; }
ft_uint16_t Ft_Esd_Label_AlignX__Default(void *context) { return OPT_ALIGN_LEFT; }
ft_uint16_t Ft_Esd_Label_AlignY__Default(void *context) { return OPT_ALIGN_TOP; }


static Ft_Esd_WidgetSlots s_Ft_Esd_Label__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Label_Update,
	(void(*)(void *))Ft_Esd_Label_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Widget_End,
};


void Ft_Esd_Label__Initializer(Ft_Esd_Label *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_Label_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_Label__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 120;
	context->Widget.LocalHeight = 36;
	context->AutoResize = ESD_AUTORESIZE_HEIGHT;
	context->BackGroundAlpha = 0;
	context->Alpha = Ft_Esd_Label_Alpha__Default;
	context->Theme = Ft_Esd_Label_Theme__Default;
	context->Font = Ft_Esd_Label_Font__Default;
	context->FontResource = Ft_Esd_Label_FontResource__Default;
	context->Text = Ft_Esd_Label_Text__Default;
	context->AlignX = Ft_Esd_Label_AlignX__Default;
	context->AlignY = Ft_Esd_Label_AlignY__Default;
}

static uint16_t Ft_Esd_Label_Get_Font_Caps_Height__return(Ft_Esd_Label *context);

ESD_CORE_EXPORT Esd_FontInfo *Esd_GetRomFont(uint8_t);
ESD_CORE_EXPORT uint16_t Esd_GetFontBaseLine(Esd_FontInfo *);
ESD_CORE_EXPORT uint16_t Esd_GetFontCapsHeight(Esd_FontInfo *);
ESD_CORE_EXPORT uint16_t Esd_GetFontXOffset(Esd_FontInfo *);

static ft_rgb32_t Ft_Esd_Label_Local_Method(Ft_Esd_Label *context, ft_argb32_t x);

void Ft_Esd_Label_Update(Ft_Esd_Label *context)
{
	void *owner = context->Owner;
	ft_uint8_t left = context->AutoResize;
	ft_uint8_t right = ESD_AUTORESIZE_HEIGHT;
	ft_uint8_t if_1 = left & right;
	if (if_1)
	{
		uint16_t set_variable = Ft_Esd_Label_Get_Font_Caps_Height__return(context);
		Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)context, set_variable);
	}
	else
	{
	}
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context); 
}

void Ft_Esd_Label_Render(Ft_Esd_Label *context)
{
	void *owner = context->Owner;
	ft_int16_t x = context->Widget.GlobalX;
	ft_int16_t y = context->Widget.GlobalY;
	ft_int16_t width = context->Widget.GlobalWidth;
	ft_int16_t height = context->Widget.GlobalHeight;
	int32_t radius = 1L;
	Ft_Esd_Theme * theme = context->Theme(owner);
	ft_argb32_t rgb = Ft_Esd_Theme_GetBackColor(theme);
	ft_uint8_t a = context->BackGroundAlpha;
	esd_argb32_t color = ESD_COMPOSE_RGB_ALPHA(rgb, a);
	Esd_Render_Rect(x, y, width, height, radius, color);
	ft_uint8_t alpha = context->Alpha(owner);
	Ft_Esd_Dl_COLOR_A(alpha);
	Ft_Esd_Theme * theme_1 = context->Theme(owner);
	ft_argb32_t x_1 = Ft_Esd_Theme_GetTextColor(theme_1);
	ft_rgb32_t c_1 = Ft_Esd_Label_Local_Method(context, x_1);
	Ft_Esd_Dl_COLOR_RGB(c_1);
	EVE_HalContext * phost = Ft_Esd_GetHost();
	ft_uint16_t value = context->AlignX(owner);
	ft_int16_t x_2;
	switch (value)
	{
		case 0L:
		{
			x_2 = context->Widget.GlobalX;
			break;
		}
		case 1L:
		{
			ft_int16_t left_1 = context->Widget.GlobalX;
			ft_int16_t left_2 = context->Widget.GlobalWidth;
			int right_2 = 2L;
			int right_1 = left_2 / right_2;
			x_2 = left_1 + right_1;
			break;
		}
		case 2L:
		{
			ft_int16_t left_3 = context->Widget.GlobalX;
			ft_int16_t right_3 = context->Widget.GlobalWidth;
			x_2 = left_3 + right_3;
			break;
		}
		default:
		{
			x_2 = 0;
			break;
		}
	}
	ft_uint16_t value_1 = context->AlignY(owner);
	ft_int16_t y_1;
	switch (value_1)
	{
		case 0L:
		{
			y_1 = context->Widget.GlobalY;
			break;
		}
		case 1L:
		{
			ft_int16_t left_4 = context->Widget.GlobalY;
			ft_int16_t left_5 = context->Widget.GlobalHeight;
			int right_5 = 2L;
			int right_4 = left_5 / right_5;
			y_1 = left_4 + right_4;
			break;
		}
		case 2L:
		{
			ft_int16_t left_6 = context->Widget.GlobalY;
			ft_int16_t right_6 = context->Widget.GlobalHeight;
			y_1 = left_6 + right_6;
			break;
		}
		default:
		{
			y_1 = 0;
			break;
		}
	}
	Esd_FontInfo * if_2 = context->FontResource(owner);
	Esd_FontInfo *fontInfo;
	if (if_2)
	{
		fontInfo = context->FontResource(owner);
	}
	else
	{
		uint8_t i = context->Font(owner);
		fontInfo = Esd_GetRomFont(i);
	}
	uint8_t font = Ft_Esd_Dl_Font_Setup(fontInfo);
	ft_uint16_t left_8 = context->AlignX(owner);
	ft_uint16_t right_7 = OPT_ALIGN_LEFT;
	int if_3 = left_8 == right_7;
	uint16_t left_7;
	if (if_3)
	{
		left_7 = 0;
	}
	else
	{
		ft_uint16_t left_9 = context->AlignX(owner);
		ft_uint16_t right_8 = OPT_ALIGN_RIGHT;
		int if_4 = left_9 == right_8;
		if (if_4)
		{
			left_7 = OPT_RIGHTX;
		}
		else
		{
			left_7 = OPT_CENTERX;
		}
	}
	ft_uint16_t left_10 = context->AlignY(owner);
	ft_uint16_t right_10 = OPT_ALIGN_CENTER;
	int if_5 = left_10 == right_10;
	uint16_t right_9;
	if (if_5)
	{
		right_9 = OPT_CENTERY;
	}
	else
	{
		right_9 = 0;
	}
	uint16_t options = left_7 | right_9;
	ft_uint16_t left_11 = context->AlignY(owner);
	ft_uint16_t right_11 = OPT_ALIGN_BOTTOM;
	int bottom = left_11 == right_11;
	Esd_FontInfo * if_6 = context->FontResource(owner);
	Esd_FontInfo *fontInfo_1;
	if (if_6)
	{
		fontInfo_1 = context->FontResource(owner);
	}
	else
	{
		uint8_t i_1 = context->Font(owner);
		fontInfo_1 = Esd_GetRomFont(i_1);
	}
	uint16_t baseLine = Esd_GetFontBaseLine(fontInfo_1);
	uint16_t capsHeight = Ft_Esd_Label_Get_Font_Caps_Height__return(context);
	Esd_FontInfo * if_7 = context->FontResource(owner);
	Esd_FontInfo *fontInfo_2;
	if (if_7)
	{
		fontInfo_2 = context->FontResource(owner);
	}
	else
	{
		uint8_t i_2 = context->Font(owner);
		fontInfo_2 = Esd_GetRomFont(i_2);
	}
	uint16_t xOffset = Esd_GetFontXOffset(fontInfo_2);
	const char * s = context->Text(owner);
	Ft_Gpu_CoCmd_Text_Ex(phost, x_2, y_1, font, options, bottom, baseLine, capsHeight, xOffset, s);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

static ft_rgb32_t Ft_Esd_Label_Local_Method(Ft_Esd_Label *context, ft_argb32_t x)
{
	void *owner = context->Owner;
	x &=0xffffff;
	return x;
}

uint16_t Ft_Esd_Label_Get_Font_Caps_Height__return(Ft_Esd_Label *context)
{
	void *owner = context->Owner;
	Esd_FontInfo * if_8 = context->FontResource(owner);
	Esd_FontInfo *fontInfo_3;
	if (if_8)
	{
		fontInfo_3 = context->FontResource(owner);
	}
	else
	{
		uint8_t i_3 = context->Font(owner);
		fontInfo_3 = Esd_GetRomFont(i_3);
	}
	return Esd_GetFontCapsHeight(fontInfo_3);
}


/* end of file */
