/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_Panel_Raised
C Source
*/

#include "Ft_Esd_Panel_Raised.h"

#include "Esd_Context.h"
#include "Ft_Esd_Elements.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
int Ft_Esd_Panel_Raised_radius__Default(void *context) { return 36L; }
ft_argb32_t Ft_Esd_Panel_Raised_color__Default(void *context) { return 0xfffafafaUL; }


static Ft_Esd_WidgetSlots s_Ft_Esd_Panel_Raised__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Panel_Raised_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Widget_End,
};


void Ft_Esd_Panel_Raised__Initializer(Ft_Esd_Panel_Raised *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_Panel_Raised_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_Panel_Raised__Slots;
	context->Widget.LocalX = 107;
	context->Widget.LocalY = 64;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->radius = Ft_Esd_Panel_Raised_radius__Default;
	context->color = Ft_Esd_Panel_Raised_color__Default;
}

void Ft_Esd_Elements_PanelRaised(ft_rgb32_t, ft_int16_t, ft_int16_t, ft_int16_t, ft_int16_t, ft_int16_t);

void Ft_Esd_Panel_Raised_Render(Ft_Esd_Panel_Raised *context)
{
	void *owner = context->Owner;
	ft_argb32_t color_1 = context->color(owner);
	ft_int16_t x = context->Widget.GlobalX;
	ft_int16_t y = context->Widget.GlobalY;
	ft_int16_t width = context->Widget.GlobalWidth;
	ft_int16_t height = context->Widget.GlobalHeight;
	int radius_1 = context->radius(owner);
	Ft_Esd_Elements_PanelRaised(color_1, x, y, width, height, radius_1);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context);
}


/* end of file */
