/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_LabelButton
C Source
*/

/*
Comment :
Introduction:
This widget act like a combination of Button and Label.
Font type and font size can be changed.
The label content is taken from "Text" property.
*/

#include "Ft_Esd_LabelButton.h"

#include "Esd_Context.h"
#include "EVE_Hal.h"
#include "Esd_BitmapHandle.h"
#include "Ft_Esd_BitmapHandle.h"
#include "Ft_Esd_CoCmd.h"
#include "Ft_Esd_Dl.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
bool Ft_Esd_LabelButton_PressNHold__Default(void *context) { return 0; }
Ft_Esd_Theme * Ft_Esd_LabelButton_Theme__Default(void *context) { return Ft_Esd_Theme_GetCurrent(); }
uint8_t Ft_Esd_LabelButton_Font__Default(void *context) { return 27; }
Esd_FontInfo * Ft_Esd_LabelButton_FontResource__Default(void *context) { return 0; }
const char * Ft_Esd_LabelButton_Text__Default(void *context) { return "Label Button"; }
ft_bool_t Ft_Esd_LabelButton_Primary__Default(void *context) { return 1; }
ft_uint16_t Ft_Esd_LabelButton_AlignX__Default(void *context) { return OPT_ALIGN_LEFT; }
ft_uint16_t Ft_Esd_LabelButton_AlignY__Default(void *context) { return OPT_ALIGN_CENTER; }
ft_uint8_t Ft_Esd_LabelButton_AutoResize__Default(void *context) { return ESD_AUTORESIZE_HEIGHT; }


static Ft_Esd_WidgetSlots s_Ft_Esd_LabelButton__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_LabelButton_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_LabelButton_Update,
	(void(*)(void *))Ft_Esd_LabelButton_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_LabelButton_End,
};

static void Ft_Esd_LabelButton_Touch_Tag_Tap__Signal(void *context);

void Ft_Esd_LabelButton__Touch_Tag__Initializer(Ft_Esd_LabelButton *context)
{
	Ft_Esd_TouchTag *object = (Ft_Esd_TouchTag *)&context->Touch_Tag;
	Ft_Esd_TouchTag__Initializer(object);
	object->Owner = (void *)context;
	object->Tap = Ft_Esd_LabelButton_Touch_Tag_Tap__Signal;
}

void Ft_Esd_LabelButton__Initializer(Ft_Esd_LabelButton *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_LabelButton_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_LabelButton__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 120;
	context->Widget.LocalHeight = 36;
	context->PressNHold = Ft_Esd_LabelButton_PressNHold__Default;
	context->Pushed = Esd_Noop;
	context->State = 0;
	context->Theme = Ft_Esd_LabelButton_Theme__Default;
	context->X = 0L;
	context->Y = 0L;
	context->Font = Ft_Esd_LabelButton_Font__Default;
	context->FontResource = Ft_Esd_LabelButton_FontResource__Default;
	context->Text = Ft_Esd_LabelButton_Text__Default;
	context->Primary = Ft_Esd_LabelButton_Primary__Default;
	context->AlignX = Ft_Esd_LabelButton_AlignX__Default;
	context->AlignY = Ft_Esd_LabelButton_AlignY__Default;
	context->FontHeight = 0;
	context->AutoResize = Ft_Esd_LabelButton_AutoResize__Default;
	Ft_Esd_LabelButton__Touch_Tag__Initializer(context);
}

static uint16_t Ft_Esd_LabelButton_Get_Font_Caps_Height__return(Ft_Esd_LabelButton *context);

ESD_CORE_EXPORT Esd_FontInfo *Esd_GetRomFont(uint8_t);
ESD_CORE_EXPORT uint16_t Esd_GetFontCapsHeight(Esd_FontInfo *);
ESD_CORE_EXPORT uint16_t Esd_GetFontBaseLine(Esd_FontInfo *);
ESD_CORE_EXPORT uint16_t Esd_GetFontXOffset(Esd_FontInfo *);
uint16_t Ft_Esd_LabelButton_GetOptionUpdatePosition(Ft_Esd_LabelButton *context);

void Ft_Esd_LabelButton_Start(Ft_Esd_LabelButton *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context);
	Ft_Esd_TouchTag_Start(&context->Touch_Tag);
}

void Ft_Esd_LabelButton_Update__Builtin(Ft_Esd_LabelButton *context)
{
	void *owner = context->Owner;
	uint16_t update_variable = Ft_Esd_LabelButton_Get_Font_Caps_Height__return(context);
	context->FontHeight = update_variable;
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void Ft_Esd_LabelButton_End__Builtin(Ft_Esd_LabelButton *context)
{
	void *owner = context->Owner;
	Ft_Esd_TouchTag_End(&context->Touch_Tag);
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
}

void Ft_Esd_LabelButton_Update(Ft_Esd_LabelButton *context)
{
	void *owner = context->Owner;
	Ft_Esd_TouchTag_Update(&context->Touch_Tag);
	bool if_1 = context->PressNHold(owner);
	if (if_1)
	{
	}
	else
	{
		bool set_variable = 0;
		context->State = set_variable;
	}
	ft_uint8_t left = context->AutoResize(owner);
	ft_uint8_t right = ESD_AUTORESIZE_HEIGHT;
	int if_2 = left == right;
	if (if_2)
	{
		ft_int16_t set_fontheight_to_local = context->FontHeight;
		Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)context, set_fontheight_to_local);
	}
	else
	{
	}
	Ft_Esd_LabelButton_Update__Builtin(context);
}

void Ft_Esd_LabelButton_End(Ft_Esd_LabelButton *context)
{
	void *owner = context->Owner;
	Ft_Esd_LabelButton_End__Builtin(context);
}

void Ft_Esd_LabelButton_Render(Ft_Esd_LabelButton *context)
{
	void *owner = context->Owner;
	ft_uint8_t alpha = 255;
	Ft_Esd_Dl_COLOR_A(alpha);
	ft_uint8_t s = Ft_Esd_TouchTag_Tag(&context->Touch_Tag);
	Ft_Esd_Dl_TAG(s);
	bool if_4 = context->PressNHold(owner);
	bool if_3;
	if (if_4)
	{
		if_3 = context->State;
	}
	else
	{
		if_3 = Ft_Esd_TouchTag_Inside(&context->Touch_Tag);
	}
	ft_rgb32_t c_1;
	if (if_3)
	{
		Ft_Esd_Theme * theme = context->Theme(owner);
		c_1 = Ft_Esd_Theme_GetTextColor(theme);
	}
	else
	{
		ft_bool_t if_5 = context->Primary(owner);
		if (if_5)
		{
			Ft_Esd_Theme * theme_1 = context->Theme(owner);
			c_1 = Ft_Esd_Theme_GetPrimaryColor(theme_1);
		}
		else
		{
			Ft_Esd_Theme * theme_2 = context->Theme(owner);
			c_1 = Ft_Esd_Theme_GetCurrentColor(theme_2);
		}
	}
	Ft_Esd_Dl_COLOR_RGB(c_1);
	EVE_HalContext * phost = Ft_Esd_GetHost();
	int x = context->X;
	int y = context->Y;
	Esd_FontInfo * if_6 = context->FontResource(owner);
	Esd_FontInfo *fontInfo;
	if (if_6)
	{
		fontInfo = context->FontResource(owner);
	}
	else
	{
		uint8_t i = context->Font(owner);
		fontInfo = Esd_GetRomFont(i);
	}
	uint8_t font = Ft_Esd_Dl_Font_Setup(fontInfo);
	uint16_t options = Ft_Esd_LabelButton_GetOptionUpdatePosition(context);
	ft_uint16_t left_1 = context->AlignY(owner);
	ft_uint16_t right_1 = OPT_ALIGN_BOTTOM;
	int bottom = left_1 == right_1;
	Esd_FontInfo * if_7 = context->FontResource(owner);
	Esd_FontInfo *fontInfo_1;
	if (if_7)
	{
		fontInfo_1 = context->FontResource(owner);
	}
	else
	{
		uint8_t i_1 = context->Font(owner);
		fontInfo_1 = Esd_GetRomFont(i_1);
	}
	uint16_t baseLine = Esd_GetFontBaseLine(fontInfo_1);
	uint16_t capsHeight = Ft_Esd_LabelButton_Get_Font_Caps_Height__return(context);
	Esd_FontInfo * if_8 = context->FontResource(owner);
	Esd_FontInfo *fontInfo_2;
	if (if_8)
	{
		fontInfo_2 = context->FontResource(owner);
	}
	else
	{
		uint8_t i_2 = context->Font(owner);
		fontInfo_2 = Esd_GetRomFont(i_2);
	}
	uint16_t xOffset = Esd_GetFontXOffset(fontInfo_2);
	const char * s_1 = context->Text(owner);
	Ft_Gpu_CoCmd_Text_Ex(phost, x, y, font, options, bottom, baseLine, capsHeight, xOffset, s_1);
	ft_uint8_t s_2 = 255;
	Ft_Esd_Dl_TAG(s_2);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

uint16_t Ft_Esd_LabelButton_Get_Font_Caps_Height__return(Ft_Esd_LabelButton *context)
{
	void *owner = context->Owner;
	Esd_FontInfo * if_9 = context->FontResource(owner);
	Esd_FontInfo *fontInfo_3;
	if (if_9)
	{
		fontInfo_3 = context->FontResource(owner);
	}
	else
	{
		uint8_t i_3 = context->Font(owner);
		fontInfo_3 = Esd_GetRomFont(i_3);
	}
	return Esd_GetFontCapsHeight(fontInfo_3);
}

void Ft_Esd_LabelButton_Touch_Tag_Tap__Signal(void *c)
{
	Ft_Esd_LabelButton *context = (Ft_Esd_LabelButton *)c;
	void *owner = context->Owner;
	bool if_10 = context->PressNHold(owner);
	if (if_10)
	{
		bool if_11 = context->State;
		if (if_11)
		{
			bool set_variable_1 = 0;
			context->State = set_variable_1;
		}
		else
		{
			bool set_variable_2 = 1;
			context->State = set_variable_2;
		}
	}
	else
	{
	}
	context->Pushed(owner);
}


/* end of file */
