/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_Glow
C Source
*/

#include "Ft_Esd_Glow.h"

#include "Esd_Context.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);


static Ft_Esd_WidgetSlots s_Ft_Esd_Glow__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Glow_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Glow_Update,
	(void(*)(void *))Ft_Esd_Glow_Render,
	(void(*)(void *))Ft_Esd_Glow_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Glow_End,
};


void Ft_Esd_Glow__Initializer(Ft_Esd_Glow *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_Glow_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_Glow__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 100;
	context->Widget.LocalHeight = 100;
	context->Color = 0xffffffffUL;
}

void Ft_Esd_Glow_Render_Signal(Ft_Esd_Glow *context, int, int, int, int, ft_argb32_t);

void Ft_Esd_Glow_Start(Ft_Esd_Glow *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context); 
}

void Ft_Esd_Glow_Update(Ft_Esd_Glow *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context); 
}

void Ft_Esd_Glow_Render(Ft_Esd_Glow *context)
{
	void *owner = context->Owner;
	ft_int16_t x = context->Widget.GlobalX;
	ft_int16_t y = context->Widget.GlobalY;
	ft_int16_t w = context->Widget.GlobalWidth;
	ft_int16_t h = context->Widget.GlobalHeight;
	esd_argb32_t color = context->Color;
	Ft_Esd_Glow_Render_Signal(context, x, y, w, h, color);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

void Ft_Esd_Glow_Idle(Ft_Esd_Glow *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Idle((Ft_Esd_Widget *)context); 
}

void Ft_Esd_Glow_End(Ft_Esd_Glow *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context); 
}


/* end of file */
