/*
This file is automatically generated
Ft_Esd_Theme_LightBlue
C Source
*/

#include "Ft_Esd_Theme_LightBlue.h"

static Ft_Esd_Theme Ft_Esd_Theme_LightBlue__Instance = {
	.ClearColor = 0xffebebeb,
	.BackColor = 0xffffff,
	.TextColor = 0xff000000,
	.ButtonTextColor = 0xfffafafa,
	.DefaultColor = 0xff717171,
	.PrimaryColor = 0xff2277c7,
};

Ft_Esd_Theme *Ft_Esd_Theme_LightBlue()
{
	return &Ft_Esd_Theme_LightBlue__Instance;
}

/* end of file */
