/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_PartialRing
C Source
*/

/*
Comment :
Introduction:
This widget is as same as Arc Slider, except it does not support touch input.

*/

#include "Ft_Esd_PartialRing.h"

#include "Esd_Context.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
ft_int16_t Ft_Esd_PartialRing_Angle__Default(void *context) { return 50; }
ft_int16_t Ft_Esd_PartialRing_MaxAngle__Default(void *context) { return 270; }
ft_bool_t Ft_Esd_PartialRing_Clockwise__Default(void *context) { return 1; }
int Ft_Esd_PartialRing_Origin__Default(void *context) { return 135L; }
int Ft_Esd_PartialRing_RingWidth__Default(void *context) { return 30L; }
int Ft_Esd_PartialRing_InnerBorder__Default(void *context) { return 3L; }
int Ft_Esd_PartialRing_OuterBorder__Default(void *context) { return 3L; }
ft_bool_t Ft_Esd_PartialRing_StartPoint__Default(void *context) { return 1; }
ft_bool_t Ft_Esd_PartialRing_EndPoint__Default(void *context) { return 1; }
ft_argb32_t Ft_Esd_PartialRing_BorderColor__Default(void *context) { return 0xffd0cec6UL; }
ft_argb32_t Ft_Esd_PartialRing_SelectionColor__Default(void *context) { return 0xffc55a11UL; }
ft_argb32_t Ft_Esd_PartialRing_BackgroundColor__Default(void *context) { return 0xff060504UL; }


static Ft_Esd_WidgetSlots s_Ft_Esd_PartialRing__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_PartialRing_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_PartialRing_End,
};


void Ft_Esd_PartialRing__Fixed_Positioning__Initializer(Ft_Esd_PartialRing *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Positioning;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Ft_Esd_PartialRing__ArcLine__Initializer(Ft_Esd_PartialRing *context)
{
	Ft_Esd_ArcLine *object = (Ft_Esd_ArcLine *)&context->ArcLine;
	Ft_Esd_ArcLine__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 302;
	object->Widget.LocalHeight = 285;
	object->Border = 19L;
	object->Color = 0xff35ac39UL;
	object->ShowPointShadow = 1;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Positioning);
}

void Ft_Esd_PartialRing__ArcLine_BG__Initializer(Ft_Esd_PartialRing *context)
{
	Ft_Esd_ArcLine *object = (Ft_Esd_ArcLine *)&context->ArcLine_BG;
	Ft_Esd_ArcLine__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 302;
	object->Widget.LocalHeight = 285;
	object->Border = 19L;
	object->Color = 0x7d113b13UL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Positioning);
}

void Ft_Esd_PartialRing__ArcLineBorder__Initializer(Ft_Esd_PartialRing *context)
{
	Ft_Esd_ArcLine *object = (Ft_Esd_ArcLine *)&context->ArcLineBorder;
	Ft_Esd_ArcLine__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 302;
	object->Widget.LocalHeight = 285;
	object->Border = 21L;
	object->Color = 0x7dffffffUL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Positioning);
}

void Ft_Esd_PartialRing__Initializer(Ft_Esd_PartialRing *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_PartialRing_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_PartialRing__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 320;
	context->Widget.LocalHeight = 310;
	context->Angle = Ft_Esd_PartialRing_Angle__Default;
	context->MaxAngle = Ft_Esd_PartialRing_MaxAngle__Default;
	context->Clockwise = Ft_Esd_PartialRing_Clockwise__Default;
	context->Origin = Ft_Esd_PartialRing_Origin__Default;
	context->RingWidth = Ft_Esd_PartialRing_RingWidth__Default;
	context->InnerBorder = Ft_Esd_PartialRing_InnerBorder__Default;
	context->OuterBorder = Ft_Esd_PartialRing_OuterBorder__Default;
	context->StartPoint = Ft_Esd_PartialRing_StartPoint__Default;
	context->EndPoint = Ft_Esd_PartialRing_EndPoint__Default;
	context->BorderColor = Ft_Esd_PartialRing_BorderColor__Default;
	context->SelectionColor = Ft_Esd_PartialRing_SelectionColor__Default;
	context->BackgroundColor = Ft_Esd_PartialRing_BackgroundColor__Default;
	Ft_Esd_PartialRing__Fixed_Positioning__Initializer(context);
	Ft_Esd_PartialRing__ArcLine__Initializer(context);
	Ft_Esd_PartialRing__ArcLine_BG__Initializer(context);
	Ft_Esd_PartialRing__ArcLineBorder__Initializer(context);
}


void Ft_Esd_PartialRing_Update(Ft_Esd_PartialRing *context)
{
	void *owner = context->Owner;
	int update_variable = context->OuterBorder(owner);
	Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->ArcLine, update_variable);
	int update_variable_1 = context->OuterBorder(owner);
	Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->ArcLine, update_variable_1);
	ft_int16_t left = context->Widget.GlobalWidth;
	int left_1 = context->OuterBorder(owner);
	int right_1 = context->OuterBorder(owner);
	int right = left_1 + right_1;
	int update_variable_2 = left - right;
	Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)&context->ArcLine, update_variable_2);
	ft_int16_t left_2 = context->Widget.GlobalHeight;
	int left_3 = context->OuterBorder(owner);
	int right_3 = context->OuterBorder(owner);
	int right_2 = left_3 + right_3;
	int update_variable_3 = left_2 - right_2;
	Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)&context->ArcLine, update_variable_3);
	int update_variable_4 = context->RingWidth(owner);
	context->ArcLine.Border = update_variable_4;
	ft_argb32_t update_variable_5 = context->SelectionColor(owner);
	context->ArcLine.Color = update_variable_5;
	int update_variable_6 = context->Origin(owner);
	context->ArcLine.Origin = update_variable_6;
	ft_int16_t value = context->Angle(owner);
	ft_int16_t min = 0;
	ft_int16_t max = context->MaxAngle(owner);
	ft_int16_t update_variable_7 = Ft_Esd_Int16_ClampedValue(value, min, max);
	context->ArcLine.Angle = update_variable_7;
	ft_bool_t update_variable_8 = context->Clockwise(owner);
	context->ArcLine.IsClockwise = update_variable_8;
	ft_bool_t update_variable_9 = context->StartPoint(owner);
	context->ArcLine.ShowStartPoint = update_variable_9;
	ft_bool_t update_variable_10 = context->EndPoint(owner);
	context->ArcLine.ShowEndPoint = update_variable_10;
	int left_6 = context->InnerBorder(owner);
	int right_4 = 0L;
	int left_5 = left_6 > right_4;
	int left_7 = context->OuterBorder(owner);
	int right_6 = 0L;
	int right_5 = left_7 > right_6;
	int value_1 = left_5 || right_5;
	int left_4 = !value_1;
	ft_argb32_t left_8 = context->BorderColor(owner);
	ft_argb32_t right_8 = context->ArcLine_BG.Color;
	int right_7 = left_8 != right_8;
	int update_variable_11 = left_4 || right_7;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->ArcLine_BG, update_variable_11);
	int update_variable_12 = context->OuterBorder(owner);
	Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->ArcLine_BG, update_variable_12);
	int update_variable_13 = context->OuterBorder(owner);
	Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->ArcLine_BG, update_variable_13);
	ft_int16_t left_9 = context->Widget.GlobalWidth;
	int left_10 = context->OuterBorder(owner);
	int right_10 = context->OuterBorder(owner);
	int right_9 = left_10 + right_10;
	int update_variable_14 = left_9 - right_9;
	Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)&context->ArcLine_BG, update_variable_14);
	ft_int16_t left_11 = context->Widget.GlobalHeight;
	int left_12 = context->OuterBorder(owner);
	int right_12 = context->OuterBorder(owner);
	int right_11 = left_12 + right_12;
	int update_variable_15 = left_11 - right_11;
	Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)&context->ArcLine_BG, update_variable_15);
	int update_variable_16 = context->RingWidth(owner);
	context->ArcLine_BG.Border = update_variable_16;
	ft_argb32_t update_variable_17 = context->BackgroundColor(owner);
	context->ArcLine_BG.Color = update_variable_17;
	int update_variable_18 = context->Origin(owner);
	context->ArcLine_BG.Origin = update_variable_18;
	ft_int16_t update_variable_19 = context->MaxAngle(owner);
	context->ArcLine_BG.Angle = update_variable_19;
	ft_bool_t update_variable_20 = context->Clockwise(owner);
	context->ArcLine_BG.IsClockwise = update_variable_20;
	int left_14 = context->InnerBorder(owner);
	int right_13 = 0L;
	int left_13 = left_14 > right_13;
	int left_15 = context->OuterBorder(owner);
	int right_15 = 0L;
	int right_14 = left_15 > right_15;
	int update_variable_21 = left_13 || right_14;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->ArcLineBorder, update_variable_21);
	ft_int16_t update_variable_22 = context->Widget.GlobalWidth;
	Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)&context->ArcLineBorder, update_variable_22);
	ft_int16_t update_variable_23 = context->Widget.GlobalHeight;
	Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)&context->ArcLineBorder, update_variable_23);
	int left_16 = context->RingWidth(owner);
	int left_17 = context->InnerBorder(owner);
	int right_17 = context->OuterBorder(owner);
	int right_16 = left_17 + right_17;
	int update_variable_24 = left_16 + right_16;
	context->ArcLineBorder.Border = update_variable_24;
	ft_argb32_t update_variable_25 = context->BorderColor(owner);
	context->ArcLineBorder.Color = update_variable_25;
	int update_variable_26 = context->Origin(owner);
	context->ArcLineBorder.Origin = update_variable_26;
	ft_int16_t update_variable_27 = context->MaxAngle(owner);
	context->ArcLineBorder.Angle = update_variable_27;
	ft_bool_t update_variable_28 = context->Clockwise(owner);
	context->ArcLineBorder.IsClockwise = update_variable_28;
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void Ft_Esd_PartialRing_End(Ft_Esd_PartialRing *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Positioning); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ArcLine); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ArcLine_BG); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ArcLineBorder); 
}


/* end of file */
