/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_Panel
C Source
*/

/*
Comment :
Introduction:
This widget purposely draws a background.
Panel can be in either normal or raised mode.
The four corners can be rounded by "Radius" property.
*/

#include "Ft_Esd_Panel.h"

#include "Esd_Context.h"
#include "Ft_Esd_Elements.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
Ft_Esd_Theme * Ft_Esd_Panel_Theme__Default(void *context) { return Ft_Esd_Theme_GetCurrent(); }
int Ft_Esd_Panel_Radius__Default(void *context) { return 4L; }
ft_bool_t Ft_Esd_Panel_Raised__Default(void *context) { return 0; }


static Ft_Esd_WidgetSlots s_Ft_Esd_Panel__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Panel_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Panel_End,
};


void Ft_Esd_Panel__Fixed_Positioning__Initializer(Ft_Esd_Panel *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Positioning;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 72;
	object->Widget.LocalY = 10;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Ft_Esd_Panel__Initializer(Ft_Esd_Panel *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_Panel_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_Panel__Slots;
	context->Widget.LocalX = 82;
	context->Widget.LocalY = 44;
	context->Widget.LocalWidth = 276;
	context->Widget.LocalHeight = 198;
	context->Theme = Ft_Esd_Panel_Theme__Default;
	context->Radius = Ft_Esd_Panel_Radius__Default;
	context->Raised = Ft_Esd_Panel_Raised__Default;
	Ft_Esd_Panel__Fixed_Positioning__Initializer(context);
}

void Ft_Esd_Elements_Panel(Ft_Esd_Theme *, ft_int16_t, ft_int16_t, ft_int16_t, ft_int16_t, ft_int16_t, ft_bool_t);

static int Ft_Esd_Panel_RadiusValue(Ft_Esd_Panel *context, ft_int32_t inputRadius);

void Ft_Esd_Panel_Render(Ft_Esd_Panel *context)
{
	void *owner = context->Owner;
	Ft_Esd_Theme * theme = context->Theme(owner);
	ft_int16_t x = context->Widget.GlobalX;
	ft_int16_t y = context->Widget.GlobalY;
	ft_int16_t width = context->Widget.GlobalWidth;
	ft_int16_t height = context->Widget.GlobalHeight;
	int inputRadius = context->Radius(owner);
	int radius = Ft_Esd_Panel_RadiusValue(context, inputRadius);
	ft_bool_t raised = context->Raised(owner);
	Ft_Esd_Elements_Panel(theme, x, y, width, height, radius, raised);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context);
}

void Ft_Esd_Panel_End(Ft_Esd_Panel *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Positioning); 
}

static int Ft_Esd_Panel_RadiusValue(Ft_Esd_Panel *context, ft_int32_t inputRadius)
{
	void *owner = context->Owner;
	if (inputRadius == 0)
	return 1;
	else
	return inputRadius;
}


/* end of file */
