/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_Spinner
C Source
*/

#include "Ft_Esd_Spinner.h"

#include "Esd_Context.h"
#include "Esd_Core.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);


static Ft_Esd_WidgetSlots s_Ft_Esd_Spinner__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Spinner_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Widget_End,
};


void Ft_Esd_Spinner__Initializer(Ft_Esd_Spinner *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_Spinner_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_Spinner__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->Started = 0;
	context->Style = ESD_SPINNER_CYCLE_DOT;
	context->Scale = ESD_SPINNER_SCALE_1X;
}

ESD_CORE_EXPORT void Esd_CoWidget_PopupSpinnerEx(int16_t, int16_t, uint16_t, uint16_t);

void Ft_Esd_Spinner_Render(Ft_Esd_Spinner *context)
{
	void *owner = context->Owner;
	ft_bool_t if_1 = context->Started;
	if (if_1)
	{
		ft_int16_t left = context->Widget.GlobalX;
		ft_int16_t left_1 = context->Widget.GlobalWidth;
		int right_1 = 2L;
		int right = left_1 / right_1;
		int x = left + right;
		ft_int16_t left_2 = context->Widget.GlobalY;
		ft_int16_t left_3 = context->Widget.GlobalHeight;
		int right_3 = 2L;
		int right_2 = left_3 / right_3;
		int y = left_2 + right_2;
		ft_uint8_t style = context->Style;
		ft_uint8_t scale = context->Scale;
		Esd_CoWidget_PopupSpinnerEx(x, y, style, scale);
	}
	else
	{
	}
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

void Ft_Esd_Spinner_StopSpinner(Ft_Esd_Spinner *context)
{
	void *owner = context->Owner;
	ft_bool_t if_2 = context->Started;
	if (if_2)
	{
		ft_bool_t set_variable_2 = 0;
		context->Started = set_variable_2;
	}
	else
	{
	}
}

void Ft_Esd_Spinner_StartSpinner(Ft_Esd_Spinner *context)
{
	void *owner = context->Owner;
	ft_bool_t if_3 = context->Started;
	if (if_3)
	{
	}
	else
	{
		ft_bool_t set_variable = 1;
		context->Started = set_variable;
	}
}


/* end of file */
