/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_CircularGradientSlider
C Source
*/

#include "Ft_Esd_CircularGradientSlider.h"

#include "Esd_Context.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);

static int Ft_Esd_CircularGradientSlider_Touch_Area_X__Property(void *context);
static int Ft_Esd_CircularGradientSlider_Touch_Area_Y__Property(void *context);
static int Ft_Esd_CircularGradientSlider_Touch_Area_Width__Property(void *context);
static int Ft_Esd_CircularGradientSlider_Touch_Area_Height__Property(void *context);

static Ft_Esd_WidgetSlots s_Ft_Esd_CircularGradientSlider__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_CircularGradientSlider_Update,
	(void(*)(void *))Ft_Esd_CircularGradientSlider_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_CircularGradientSlider_End,
};


void Ft_Esd_CircularGradientSlider__Touch_Area__Initializer(Ft_Esd_CircularGradientSlider *context)
{
	Ft_Esd_TouchArea *object = (Ft_Esd_TouchArea *)&context->Touch_Area;
	Ft_Esd_TouchArea__Initializer(object);
	object->Owner = (void *)context;
	object->X = Ft_Esd_CircularGradientSlider_Touch_Area_X__Property;
	object->Y = Ft_Esd_CircularGradientSlider_Touch_Area_Y__Property;
	object->Width = Ft_Esd_CircularGradientSlider_Touch_Area_Width__Property;
	object->Height = Ft_Esd_CircularGradientSlider_Touch_Area_Height__Property;
}

void Ft_Esd_CircularGradientSlider__ESD_Gradient_ArcLine__Initializer(Ft_Esd_CircularGradientSlider *context)
{
	Ft_Esd_Gradient_Arc_Line *object = (Ft_Esd_Gradient_Arc_Line *)&context->ESD_Gradient_ArcLine;
	Ft_Esd_Gradient_Arc_Line__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 84;
	object->Widget.LocalY = 139;
	object->Widget.LocalWidth = 300;
	object->Widget.LocalHeight = 300;
	object->Border = 40L;
	object->Start_Color = 0xffffffffUL;
	object->End_Color = 0xffffff00UL;
	object->Origin = 0L;
	object->Angle = 160L;
	object->IsClockwise = 0;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Ft_Esd_CircularGradientSlider__Initializer(Ft_Esd_CircularGradientSlider *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_CircularGradientSlider_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_CircularGradientSlider__Slots;
	context->Widget.LocalX = 9;
	context->Widget.LocalY = 12;
	context->Widget.LocalWidth = 414;
	context->Widget.LocalHeight = 317;
	context->CPX = 0L;
	context->GetA = 0L;
	context->CPY = 0L;
	context->isClock = 0;
	context->Border = 40L;
	context->Color1 = 0xffffffffUL;
	context->OriginA = 0L;
	context->Color2 = 0xffffff00UL;
	context->Origin = 0L;
	context->AngleA = 0L;
	context->Angle = 160L;
	Ft_Esd_CircularGradientSlider__Touch_Area__Initializer(context);
	Ft_Esd_CircularGradientSlider__ESD_Gradient_ArcLine__Initializer(context);
}

double getHue(int, int, int, int);
void Ft_Esd_CircularGradientSlider_Function(Ft_Esd_CircularGradientSlider *context, int, int, int, int, int, int, int);

void Ft_Esd_CircularGradientSlider_Update(Ft_Esd_CircularGradientSlider *context)
{
	void *owner = context->Owner;
	int x0 = context->CPX;
	int y0 = context->CPY;
	ft_int16_t x1 = Ft_Esd_TouchArea_TouchX(&context->Touch_Area);
	ft_int16_t y1 = Ft_Esd_TouchArea_TouchY(&context->Touch_Area);
	double update_variable = getHue(x0, y0, x1, y1);
	context->GetA = update_variable;
	int update_variable_1 = context->ESD_Gradient_ArcLine.Origin;
	context->OriginA = update_variable_1;
	int update_variable_2 = context->ESD_Gradient_ArcLine.Angle;
	context->AngleA = update_variable_2;
	Ft_Esd_TouchArea_Update(&context->Touch_Area);
	ft_int16_t update_variable_3 = context->Widget.GlobalX;
	Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->ESD_Gradient_ArcLine, update_variable_3);
	ft_int16_t update_variable_4 = context->Widget.GlobalY;
	Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->ESD_Gradient_ArcLine, update_variable_4);
	ft_int16_t update_variable_5 = context->Widget.GlobalWidth;
	Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)&context->ESD_Gradient_ArcLine, update_variable_5);
	ft_int16_t update_variable_6 = context->Widget.GlobalHeight;
	Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)&context->ESD_Gradient_ArcLine, update_variable_6);
	int update_variable_7 = context->Border;
	context->ESD_Gradient_ArcLine.Border = update_variable_7;
	esd_argb32_t update_variable_8 = context->Color1;
	context->ESD_Gradient_ArcLine.Start_Color = update_variable_8;
	esd_argb32_t update_variable_9 = context->Color2;
	context->ESD_Gradient_ArcLine.End_Color = update_variable_9;
	int update_variable_10 = context->Origin;
	context->ESD_Gradient_ArcLine.Origin = update_variable_10;
	int update_variable_11 = context->Angle;
	context->ESD_Gradient_ArcLine.Angle = update_variable_11;
	ft_bool_t update_variable_12 = context->isClock;
	context->ESD_Gradient_ArcLine.IsClockwise = update_variable_12;
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void Ft_Esd_CircularGradientSlider_End(Ft_Esd_CircularGradientSlider *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Gradient_ArcLine); 
}

void Ft_Esd_CircularGradientSlider_Render(Ft_Esd_CircularGradientSlider *context)
{
	void *owner = context->Owner;
	ft_bool_t if_1 = Ft_Esd_TouchArea_Inside(&context->Touch_Area);
	if (if_1)
	{
		ft_int16_t x = context->ESD_Gradient_ArcLine.Widget.LocalX;
		ft_int16_t y = context->ESD_Gradient_ArcLine.Widget.LocalY;
		ft_int16_t www = context->ESD_Gradient_ArcLine.Widget.LocalWidth;
		ft_int16_t hhh = context->ESD_Gradient_ArcLine.Widget.LocalHeight;
		ft_int16_t tx = Ft_Esd_TouchArea_TouchX(&context->Touch_Area);
		ft_int16_t ty = Ft_Esd_TouchArea_TouchY(&context->Touch_Area);
		int border = context->ESD_Gradient_ArcLine.Border;
		Ft_Esd_CircularGradientSlider_Function(context, x, y, www, hhh, tx, ty, border);
	}
	else
	{
	}
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

int Ft_Esd_CircularGradientSlider_Touch_Area_X__Property(void *c)
{
	Ft_Esd_CircularGradientSlider *context = (Ft_Esd_CircularGradientSlider *)c;
	void *owner = context->Owner;
	return context->ESD_Gradient_ArcLine.Widget.LocalX;
}

int Ft_Esd_CircularGradientSlider_Touch_Area_Y__Property(void *c)
{
	Ft_Esd_CircularGradientSlider *context = (Ft_Esd_CircularGradientSlider *)c;
	void *owner = context->Owner;
	return context->ESD_Gradient_ArcLine.Widget.LocalY;
}

int Ft_Esd_CircularGradientSlider_Touch_Area_Width__Property(void *c)
{
	Ft_Esd_CircularGradientSlider *context = (Ft_Esd_CircularGradientSlider *)c;
	void *owner = context->Owner;
	return context->ESD_Gradient_ArcLine.Widget.LocalWidth;
}

int Ft_Esd_CircularGradientSlider_Touch_Area_Height__Property(void *c)
{
	Ft_Esd_CircularGradientSlider *context = (Ft_Esd_CircularGradientSlider *)c;
	void *owner = context->Owner;
	return context->ESD_Gradient_ArcLine.Widget.LocalHeight;
}


/* end of file */
