/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_QRCode
C Source
*/

#include "Ft_Esd_QRCode.h"

#include "Esd_Context.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);


static Ft_Esd_WidgetSlots s_Ft_Esd_QRCode__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_QRCode_Update,
	(void(*)(void *))Ft_Esd_QRCode_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Widget_End,
};


void Ft_Esd_QRCode__Initializer(Ft_Esd_QRCode *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_QRCode_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_QRCode__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 100;
	context->Widget.LocalHeight = 100;
	context->BitmapCell = (Ft_Esd_BitmapCell){ 0 };
	context->URL = "URL";
	context->BitmapInfo = (Ft_Esd_BitmapInfo){ 0 };
	context->LastURL = "";
	context->Scale = 1;
}

void Ft_Esd_QRCode_Render_Signal(Ft_Esd_QRCode *context);
void Ft_Esd_QRCode_Update_Signal(Ft_Esd_QRCode *context);

void Ft_Esd_QRCode_Render(Ft_Esd_QRCode *context)
{
	void *owner = context->Owner;
	Ft_Esd_QRCode_Render_Signal(context);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

void Ft_Esd_QRCode_Update(Ft_Esd_QRCode *context)
{
	void *owner = context->Owner;
	Ft_Esd_QRCode_Update_Signal(context);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context); 
}


/* end of file */
