/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_Numberpad
C Source
*/

#include "Ft_Esd_Numberpad.h"

#include "Esd_Context.h"
#include "EVE_Hal.h"
#include "Esd_BitmapHandle.h"
#include "Ft_Esd_BitmapHandle.h"
#include "Ft_Esd_CoCmd.h"
#include "Ft_Esd_Dl.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
uint8_t Ft_Esd_Numberpad_Font__Default(void *context) { return 27; }
Esd_FontInfo * Ft_Esd_Numberpad_FontResource__Default(void *context) { return 0; }
Ft_Esd_Theme * Ft_Esd_Numberpad_Theme__Default(void *context) { return Ft_Esd_Theme_GetCurrent(); }


static Ft_Esd_WidgetSlots s_Ft_Esd_Numberpad__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Numberpad_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Numberpad_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Numberpad_End,
};

static void Ft_Esd_Numberpad_TouchTag_Down__Signal(void *context);
static void Ft_Esd_Numberpad_TouchTag_Up__Signal(void *context);
static void Ft_Esd_Numberpad_Render_Forwarder_ForwardRender__Signal(void *context);

void Ft_Esd_Numberpad__TouchTag__Initializer(Ft_Esd_Numberpad *context)
{
	Ft_Esd_TouchTag *object = (Ft_Esd_TouchTag *)&context->TouchTag;
	Ft_Esd_TouchTag__Initializer(object);
	object->Owner = (void *)context;
	object->Down = Ft_Esd_Numberpad_TouchTag_Down__Signal;
	object->Up = Ft_Esd_Numberpad_TouchTag_Up__Signal;
}

void Ft_Esd_Numberpad__Render_Forwarder__Initializer(Ft_Esd_Numberpad *context)
{
	Ft_Esd_RenderForwarder *object = (Ft_Esd_RenderForwarder *)&context->Render_Forwarder;
	Ft_Esd_RenderForwarder__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->ForwardRender = Ft_Esd_Numberpad_Render_Forwarder_ForwardRender__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Ft_Esd_Numberpad__Fixed_Positioning__Initializer(Ft_Esd_Numberpad *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Positioning;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Ft_Esd_Numberpad__Initializer(Ft_Esd_Numberpad *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_Numberpad_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_Numberpad__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 210;
	context->Widget.LocalHeight = 280;
	context->KeyReleased = Esd_Noop;
	context->isDown = 0;
	context->XValue = 0L;
	context->YValue = 0L;
	context->Radius = 0L;
	context->Alpha = 0L;
	context->Variable = 0;
	context->PointerIndex = 0L;
	context->Ft_Esd_Detect_KeyDepressed = 0L;
	context->Container = 0x0;
	context->Ft_Esd_CheckEmitPressedSignal = 0;
	context->lastSentValue = -1L;
	context->hasSent = 0;
	context->Keypressed = Esd_Noop;
	context->TouchPattern = 0;
	context->baseLine = 0U;
	context->capsHeight = 0U;
	context->Font = Ft_Esd_Numberpad_Font__Default;
	context->FontResource = Ft_Esd_Numberpad_FontResource__Default;
	context->xOffset = 0U;
	context->myFont = 0U;
	context->Theme = Ft_Esd_Numberpad_Theme__Default;
	Ft_Esd_Numberpad__TouchTag__Initializer(context);
	Ft_Esd_Numberpad__Render_Forwarder__Initializer(context);
	Ft_Esd_Numberpad__Fixed_Positioning__Initializer(context);
}

static uint16_t Ft_Esd_Numberpad_Get_Font_Base_Line__return(Ft_Esd_Numberpad *context);
static uint16_t Ft_Esd_Numberpad_Get_Font_Caps_Height__return(Ft_Esd_Numberpad *context);
static uint16_t Ft_Esd_Numberpad_Get_Font_X_Offset__return(Ft_Esd_Numberpad *context);
static uint8_t Ft_Esd_Numberpad_Setup_Font__return(Ft_Esd_Numberpad *context);

void Ft_Esd_Reset_PointerIndex(Ft_Esd_Numberpad *context);
void Ft_Esd_Draw_Display(Ft_Esd_Numberpad *context, int, int, int, int, int16_t, int16_t, int16_t, int16_t, bool, int);
void Ft_Esd_Connect_Lines(Ft_Esd_Numberpad *context, int, int);
void Ft_Esd_Highlight_Keypressed(Ft_Esd_Numberpad *context, int, int, int, int, int);
void Ft_Esd_Create_TouchArea(Ft_Esd_Numberpad *context, int, int, int, int);
int Ft_Esd_Detect_KeyDepressed(Ft_Esd_Numberpad *context, int, int, int, int, int, int, int, int);
void Ft_Esd_AddPoint(Ft_Esd_Numberpad *context, bool);
bool Ft_Esd_CheckEmitPressedSignal(Ft_Esd_Numberpad *context, bool, int);
void Ft_Esd_Free_Signal(Ft_Esd_Numberpad *context);
ESD_CORE_EXPORT uint16_t Esd_GetFontBaseLine(Esd_FontInfo *);
ESD_CORE_EXPORT Esd_FontInfo *Esd_GetRomFont(uint8_t);
ESD_CORE_EXPORT uint16_t Esd_GetFontCapsHeight(Esd_FontInfo *);
ESD_CORE_EXPORT uint16_t Esd_GetFontXOffset(Esd_FontInfo *);

static ft_rgb32_t Ft_Esd_Numberpad_Local_Method(Ft_Esd_Numberpad *context, ft_argb32_t x);

void Ft_Esd_Numberpad_Start(Ft_Esd_Numberpad *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context);
	Ft_Esd_TouchTag_Start(&context->TouchTag);
}

void Ft_Esd_Numberpad_Update(Ft_Esd_Numberpad *context)
{
	void *owner = context->Owner;
	uint16_t update_variable = Ft_Esd_Numberpad_Get_Font_Base_Line__return(context);
	context->baseLine = update_variable;
	uint16_t update_variable_1 = Ft_Esd_Numberpad_Get_Font_Caps_Height__return(context);
	context->capsHeight = update_variable_1;
	uint16_t update_variable_2 = Ft_Esd_Numberpad_Get_Font_X_Offset__return(context);
	context->xOffset = update_variable_2;
	uint8_t update_variable_3 = Ft_Esd_Numberpad_Setup_Font__return(context);
	context->myFont = update_variable_3;
	Ft_Esd_TouchTag_Update(&context->TouchTag);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void Ft_Esd_Numberpad_End__Builtin(Ft_Esd_Numberpad *context)
{
	void *owner = context->Owner;
	Ft_Esd_TouchTag_End(&context->TouchTag);
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Render_Forwarder); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Positioning); 
}

int Ft_Esd_Numberpad_InputKey(Ft_Esd_Numberpad *context)
{
	void *owner = context->Owner;
	return context->Ft_Esd_Detect_KeyDepressed;
}

void Ft_Esd_Numberpad_End(Ft_Esd_Numberpad *context)
{
	void *owner = context->Owner;
	Ft_Esd_Free_Signal(context);
	Ft_Esd_Numberpad_End__Builtin(context);
}

uint16_t Ft_Esd_Numberpad_Get_Font_Base_Line__return(Ft_Esd_Numberpad *context)
{
	void *owner = context->Owner;
	Esd_FontInfo * if_1 = context->FontResource(owner);
	Esd_FontInfo *fontInfo;
	if (if_1)
	{
		fontInfo = context->FontResource(owner);
	}
	else
	{
		uint8_t i = context->Font(owner);
		fontInfo = Esd_GetRomFont(i);
	}
	return Esd_GetFontBaseLine(fontInfo);
}

uint16_t Ft_Esd_Numberpad_Get_Font_Caps_Height__return(Ft_Esd_Numberpad *context)
{
	void *owner = context->Owner;
	Esd_FontInfo * if_2 = context->FontResource(owner);
	Esd_FontInfo *fontInfo_1;
	if (if_2)
	{
		fontInfo_1 = context->FontResource(owner);
	}
	else
	{
		uint8_t i_1 = context->Font(owner);
		fontInfo_1 = Esd_GetRomFont(i_1);
	}
	return Esd_GetFontCapsHeight(fontInfo_1);
}

uint16_t Ft_Esd_Numberpad_Get_Font_X_Offset__return(Ft_Esd_Numberpad *context)
{
	void *owner = context->Owner;
	Esd_FontInfo * if_3 = context->FontResource(owner);
	Esd_FontInfo *fontInfo_2;
	if (if_3)
	{
		fontInfo_2 = context->FontResource(owner);
	}
	else
	{
		uint8_t i_2 = context->Font(owner);
		fontInfo_2 = Esd_GetRomFont(i_2);
	}
	return Esd_GetFontXOffset(fontInfo_2);
}

uint8_t Ft_Esd_Numberpad_Setup_Font__return(Ft_Esd_Numberpad *context)
{
	void *owner = context->Owner;
	Esd_FontInfo * if_4 = context->FontResource(owner);
	Esd_FontInfo *fontInfo_3;
	if (if_4)
	{
		fontInfo_3 = context->FontResource(owner);
	}
	else
	{
		uint8_t i_3 = context->Font(owner);
		fontInfo_3 = Esd_GetRomFont(i_3);
	}
	return Ft_Esd_Dl_Font_Setup(fontInfo_3);
}

static ft_rgb32_t Ft_Esd_Numberpad_Local_Method(Ft_Esd_Numberpad *context, ft_argb32_t x)
{
	void *owner = context->Owner;
	x &=0xffffff;
	return x;
}

void Ft_Esd_Numberpad_TouchTag_Down__Signal(void *c)
{
	Ft_Esd_Numberpad *context = (Ft_Esd_Numberpad *)c;
	void *owner = context->Owner;
	bool set_variable = 1;
	context->isDown = set_variable;
	int set_variable_3 = 150L;
	context->Alpha = set_variable_3;
}

void Ft_Esd_Numberpad_TouchTag_Up__Signal(void *c)
{
	Ft_Esd_Numberpad *context = (Ft_Esd_Numberpad *)c;
	void *owner = context->Owner;
	context->KeyReleased(owner);
	Ft_Esd_Reset_PointerIndex(context);
	bool set_variable_2 = 0;
	context->isDown = set_variable_2;
	context->Variable = set_variable_2;
	context->hasSent = set_variable_2;
}

void Ft_Esd_Numberpad_Render_Forwarder_ForwardRender__Signal(void *c)
{
	Ft_Esd_Numberpad *context = (Ft_Esd_Numberpad *)c;
	void *owner = context->Owner;
	Ft_Esd_Theme * theme = context->Theme(owner);
	ft_argb32_t x = Ft_Esd_Theme_GetTextColor(theme);
	ft_rgb32_t c_1 = Ft_Esd_Numberpad_Local_Method(context, x);
	Ft_Esd_Dl_COLOR_RGB(c_1);
	EVE_HalContext * phost = Ft_Esd_GetHost();
	ft_int16_t x_1 = 0;
	ft_int16_t y = 0;
	uint8_t font = Ft_Esd_Numberpad_Setup_Font__return(context);
	uint16_t options = 0;
	ft_bool_t bottom = 0;
	ft_int16_t baseLine_1 = 0;
	ft_int16_t capsHeight_1 = 0;
	ft_int16_t xOffset_1 = 0;
	const ft_char8_t * s = "";
	Ft_Gpu_CoCmd_Text_Ex(phost, x_1, y, font, options, bottom, baseLine_1, capsHeight_1, xOffset_1, s);
	ft_int16_t x_2 = context->Widget.GlobalX;
	ft_int16_t y_1 = context->Widget.GlobalY;
	ft_int16_t width = context->Widget.GlobalWidth;
	ft_int16_t height = context->Widget.GlobalHeight;
	uint8_t font_1 = Ft_Esd_Numberpad_Setup_Font__return(context);
	uint16_t baseLine_2 = Ft_Esd_Numberpad_Get_Font_Base_Line__return(context);
	uint16_t capsHeight_2 = Ft_Esd_Numberpad_Get_Font_Caps_Height__return(context);
	uint16_t xOffset_2 = Ft_Esd_Numberpad_Get_Font_X_Offset__return(context);
	ft_bool_t touching = Ft_Esd_TouchTag_Touching(&context->TouchTag);
	ft_uint8_t ID = Ft_Esd_TouchTag_Tag(&context->TouchTag);
	Ft_Esd_Draw_Display(context, x_2, y_1, width, height, font_1, baseLine_2, capsHeight_2, xOffset_2, touching, ID);
	int Keypressed_1 = 0L;
	ft_int16_t x_3 = context->Widget.GlobalX;
	ft_int16_t y_2 = context->Widget.GlobalY;
	ft_int16_t width_1 = context->Widget.GlobalWidth;
	ft_int16_t height_1 = context->Widget.GlobalHeight;
	Ft_Esd_Highlight_Keypressed(context, Keypressed_1, x_3, y_2, width_1, height_1);
	ft_int16_t curX = Ft_Esd_TouchTag_TouchX(&context->TouchTag);
	ft_int16_t curY = Ft_Esd_TouchTag_TouchY(&context->TouchTag);
	Ft_Esd_Connect_Lines(context, curX, curY);
	ft_uint8_t s_1 = Ft_Esd_TouchTag_Tag(&context->TouchTag);
	Ft_Esd_Dl_TAG(s_1);
	ft_int16_t x_4 = context->Widget.GlobalX;
	ft_int16_t y_3 = context->Widget.GlobalY;
	ft_int16_t width_2 = context->Widget.GlobalWidth;
	ft_int16_t height_2 = context->Widget.GlobalHeight;
	Ft_Esd_Create_TouchArea(context, x_4, y_3, width_2, height_2);
	ft_uint8_t s_2 = 255;
	Ft_Esd_Dl_TAG(s_2);
	bool if_5 = context->isDown;
	if (if_5)
	{
		ft_int16_t X = context->Widget.GlobalX;
		ft_int16_t Y = context->Widget.GlobalY;
		ft_int16_t Width = context->Widget.GlobalWidth;
		ft_int16_t Height = context->Widget.GlobalHeight;
		ft_int16_t CurX = Ft_Esd_TouchTag_TouchX(&context->TouchTag);
		ft_int16_t CurY = Ft_Esd_TouchTag_TouchY(&context->TouchTag);
		ft_uint8_t Tag = Ft_Esd_TouchTag_Tag(&context->TouchTag);
		ft_uint8_t CurTag = Ft_Esd_TouchTag_CurrentTag(&context->TouchTag);
		context->Ft_Esd_Detect_KeyDepressed = Ft_Esd_Detect_KeyDepressed(context, X, Y, Width, Height, CurX, CurY, Tag, CurTag);
		ft_bool_t touched = Ft_Esd_TouchTag_Touching(&context->TouchTag);
		Ft_Esd_AddPoint(context, touched);
		bool isDown_1 = context->isDown;
		int keyPressed = context->Ft_Esd_Detect_KeyDepressed;
		context->Ft_Esd_CheckEmitPressedSignal = Ft_Esd_CheckEmitPressedSignal(context, isDown_1, keyPressed);
		bool if_6 = context->Ft_Esd_CheckEmitPressedSignal;
		if (if_6)
		{
			context->Keypressed(owner);
		}
		else
		{
		}
	}
	else
	{
	}
}


/* end of file */
