/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_PolygonWidget
C Source
*/

/*
Comment :
Introduction:
This widget draws a polygon with maximum of 20 vertices.
Border width, border color and fill color can be customized.
*/

#include "Ft_Esd_PolygonWidget.h"

#include "Esd_Context.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
int Ft_Esd_PolygonWidget_VertexsX__Default(void *context, size_t *size) { *size = 0; return NULL; }
int Ft_Esd_PolygonWidget_VertexsY__Default(void *context, size_t *size) { *size = 0; return NULL; }
ft_uint8_t Ft_Esd_PolygonWidget_Border_Width__Default(void *context) { return 10; }
ft_argb32_t Ft_Esd_PolygonWidget_Border_Color__Default(void *context) { return 0xff00007fUL; }
ft_argb32_t Ft_Esd_PolygonWidget_Fill_Color__Default(void *context) { return 0xffffff00UL; }


static Ft_Esd_WidgetSlots s_Ft_Esd_PolygonWidget__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_PolygonWidget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_PolygonWidget_Update,
	(void(*)(void *))Ft_Esd_PolygonWidget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Widget_End,
};


void Ft_Esd_PolygonWidget__Initializer(Ft_Esd_PolygonWidget *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_PolygonWidget_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_PolygonWidget__Slots;
	context->Widget.LocalX = 202;
	context->Widget.LocalY = 105;
	context->Widget.LocalWidth = 250;
	context->Widget.LocalHeight = 250;
	context->VertexsX = Ft_Esd_PolygonWidget_VertexsX__Default;
	context->VertexsY = Ft_Esd_PolygonWidget_VertexsY__Default;
	context->Border_Width = Ft_Esd_PolygonWidget_Border_Width__Default;
	context->Border_Color = Ft_Esd_PolygonWidget_Border_Color__Default;
	context->Fill_Color = Ft_Esd_PolygonWidget_Fill_Color__Default;
}

void Ft_Esd_PolygonWidget_DrawPolygon(Ft_Esd_PolygonWidget *context, ft_int32_t, ft_int32_t, ft_int32_t, ft_int32_t, ft_int16_t, ft_argb32_t, ft_argb32_t);

void Ft_Esd_PolygonWidget_Start(Ft_Esd_PolygonWidget *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context); 
	int set_width = 250L;
	Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)context, (int)set_width);
	int set_height = 250L;
	Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)context, (int)set_height);
	ft_int16_t xPos = context->Widget.GlobalX;
	ft_int16_t yPos = context->Widget.GlobalY;
	ft_int16_t width = context->Widget.GlobalWidth;
	ft_int16_t height = context->Widget.GlobalHeight;
	ft_uint8_t borderWidth = context->Border_Width(owner);
	ft_argb32_t borderColor = context->Border_Color(owner);
	ft_argb32_t fillColor = context->Fill_Color(owner);
	Ft_Esd_PolygonWidget_DrawPolygon(context, xPos, yPos, width, height, borderWidth, borderColor, fillColor);
}

void Ft_Esd_PolygonWidget_Render(Ft_Esd_PolygonWidget *context)
{
	void *owner = context->Owner;
	ft_int16_t xPos_1 = context->Widget.GlobalX;
	ft_int16_t yPos_1 = context->Widget.GlobalY;
	ft_int16_t width_1 = context->Widget.GlobalWidth;
	ft_int16_t height_1 = context->Widget.GlobalHeight;
	ft_uint8_t borderWidth_1 = context->Border_Width(owner);
	ft_argb32_t borderColor_1 = context->Border_Color(owner);
	ft_argb32_t fillColor_1 = context->Fill_Color(owner);
	Ft_Esd_PolygonWidget_DrawPolygon(context, xPos_1, yPos_1, width_1, height_1, borderWidth_1, borderColor_1, fillColor_1);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

void Ft_Esd_PolygonWidget_Update(Ft_Esd_PolygonWidget *context)
{
	void *owner = context->Owner;
	ft_int16_t xPos_2 = context->Widget.GlobalX;
	ft_int16_t yPos_2 = context->Widget.GlobalY;
	ft_int16_t width_2 = context->Widget.GlobalWidth;
	ft_int16_t height_2 = context->Widget.GlobalHeight;
	ft_uint8_t borderWidth_2 = context->Border_Width(owner);
	ft_argb32_t borderColor_2 = context->Border_Color(owner);
	ft_argb32_t fillColor_2 = context->Fill_Color(owner);
	Ft_Esd_PolygonWidget_DrawPolygon(context, xPos_2, yPos_2, width_2, height_2, borderWidth_2, borderColor_2, fillColor_2);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context); 
}


/* end of file */
