/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_Arc
C Source
*/

#include "Ft_Esd_Arc.h"

#include "Esd_Context.h"
#include "Ft_Esd_Dl.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);


static Ft_Esd_WidgetSlots s_Ft_Esd_Arc__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Arc_End,
};

static void Ft_Esd_Arc_Render_Forwarder_ForwardUpdate__Signal(void *context);
static void Ft_Esd_Arc_Render_Forwarder_ForwardRender__Signal(void *context);

void Ft_Esd_Arc__Render_Forwarder__Initializer(Ft_Esd_Arc *context)
{
	Ft_Esd_RenderForwarder *object = (Ft_Esd_RenderForwarder *)&context->Render_Forwarder;
	Ft_Esd_RenderForwarder__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 10;
	object->Widget.LocalY = 10;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->ForwardUpdate = Ft_Esd_Arc_Render_Forwarder_ForwardUpdate__Signal;
	object->ForwardRender = Ft_Esd_Arc_Render_Forwarder_ForwardRender__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Ft_Esd_Arc__Initializer(Ft_Esd_Arc *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_Arc_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_Arc__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->cX = 0L;
	context->cY = 0L;
	context->Color = 0xffffffffUL;
	context->Radius = 100L;
	context->Border = 20L;
	context->StartPoint = 0L;
	context->EndPoint = 26380L;
	Ft_Esd_Arc__Render_Forwarder__Initializer(context);
}

void Ft_Esd_Arc_Render_Signal(Ft_Esd_Arc *context, int, int, int, int, ft_argb32_t, int, int);

void Ft_Esd_Arc_End(Ft_Esd_Arc *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Render_Forwarder); 
}

void Ft_Esd_Arc_Render_Forwarder_ForwardUpdate__Signal(void *c)
{
	Ft_Esd_Arc *context = (Ft_Esd_Arc *)c;
	void *owner = context->Owner;
	ft_int16_t left_1 = Ft_Esd_RenderForwarder_GlobalWidth(&context->Render_Forwarder);
	int right = 1L;
	int left = left_1 >> right;
	ft_int16_t right_1 = Ft_Esd_RenderForwarder_GlobalX(&context->Render_Forwarder);
	int set_variable = left + right_1;
	context->cX = set_variable;
	ft_int16_t left_2 = Ft_Esd_RenderForwarder_GlobalY(&context->Render_Forwarder);
	ft_int16_t left_3 = Ft_Esd_RenderForwarder_GlobalHeight(&context->Render_Forwarder);
	int right_3 = 1L;
	int right_2 = left_3 >> right_3;
	int set_variable_2 = left_2 + right_2;
	context->cY = set_variable_2;
	ft_int16_t left_5 = Ft_Esd_RenderForwarder_GlobalWidth(&context->Render_Forwarder);
	int right_4 = 1L;
	int left_4 = left_5 >> right_4;
	ft_int16_t left_6 = Ft_Esd_RenderForwarder_GlobalHeight(&context->Render_Forwarder);
	int right_6 = 1L;
	int right_5 = left_6 >> right_6;
	int if_1 = left_4 <= right_5;
	int set_variable_3;
	if (if_1)
	{
		ft_int16_t left_7 = Ft_Esd_RenderForwarder_GlobalWidth(&context->Render_Forwarder);
		int right_7 = 1L;
		set_variable_3 = left_7 >> right_7;
	}
	else
	{
		ft_int16_t left_8 = Ft_Esd_RenderForwarder_GlobalHeight(&context->Render_Forwarder);
		int right_8 = 1L;
		set_variable_3 = left_8 >> right_8;
	}
	context->Radius = set_variable_3;
}

void Ft_Esd_Arc_Render_Forwarder_ForwardRender__Signal(void *c)
{
	Ft_Esd_Arc *context = (Ft_Esd_Arc *)c;
	void *owner = context->Owner;
	ft_bool_t left_9 = context->Render_Forwarder.Widget.Active;
	int left_10 = context->Radius;
	int right_10 = 0L;
	int right_9 = left_10 > right_10;
	int if_2 = left_9 && right_9;
	if (if_2)
	{
		ft_uint8_t alpha = 255;
		Ft_Esd_Dl_COLOR_A(alpha);
		int x = context->cX;
		int y = context->cY;
		int radius = context->Radius;
		int border = context->Border;
		ft_argb32_t color = context->Color;
		int start = context->StartPoint;
		int end = context->EndPoint;
		Ft_Esd_Arc_Render_Signal(context, x, y, radius, border, color, start, end);
	}
	else
	{
	}
}


/* end of file */
