/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_Ring
C Source
*/

/*
Comment :
Introduction:
This widget acts like Circular Slider.
It does not support touch input.
*/

#include "Ft_Esd_Ring.h"

#include "Esd_Context.h"
ESD_CORE_EXPORT void Esd_Noop(void *context);
ft_int16_t Ft_Esd_Ring_Angle__Default(void *context) { return 50; }
ft_bool_t Ft_Esd_Ring_Clockwise__Default(void *context) { return 1; }
int Ft_Esd_Ring_Origin__Default(void *context) { return 0L; }
int Ft_Esd_Ring_RingWidth__Default(void *context) { return 40L; }
int Ft_Esd_Ring_InnerBorder__Default(void *context) { return 5L; }
int Ft_Esd_Ring_OuterBorder__Default(void *context) { return 5L; }
ft_bool_t Ft_Esd_Ring_StartPoint__Default(void *context) { return 1; }
ft_bool_t Ft_Esd_Ring_EndPoint__Default(void *context) { return 1; }
ft_argb32_t Ft_Esd_Ring_BackgroundColor__Default(void *context) { return 0xff181412UL; }
ft_argb32_t Ft_Esd_Ring_SelectionColor__Default(void *context) { return 0xffc55a11UL; }
ft_argb32_t Ft_Esd_Ring_BorderColor__Default(void *context) { return 0xffc55a11UL; }


static Ft_Esd_WidgetSlots s_Ft_Esd_Ring__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Ring_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Ring_End,
};


void Ft_Esd_Ring__Fixed_Positioning__Initializer(Ft_Esd_Ring *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Positioning;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 212;
	object->Widget.LocalY = 379;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Ft_Esd_Ring__ArcLine__Initializer(Ft_Esd_Ring *context)
{
	Ft_Esd_ArcLine *object = (Ft_Esd_ArcLine *)&context->ArcLine;
	Ft_Esd_ArcLine__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 308;
	object->Widget.LocalHeight = 288;
	object->Color = 0xff35ac39UL;
	object->ShowPointShadow = 1;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Positioning);
}

void Ft_Esd_Ring__CircleLineBG__Initializer(Ft_Esd_Ring *context)
{
	Ft_Esd_CircleLine *object = (Ft_Esd_CircleLine *)&context->CircleLineBG;
	Ft_Esd_CircleLine__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 306;
	object->Widget.LocalHeight = 297;
	object->Color = 0xff061a06UL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Positioning);
}

void Ft_Esd_Ring__CircleLineBorder__Initializer(Ft_Esd_Ring *context)
{
	Ft_Esd_CircleLine *object = (Ft_Esd_CircleLine *)&context->CircleLineBorder;
	Ft_Esd_CircleLine__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 303;
	object->Widget.LocalHeight = 295;
	object->Color = 0xff061a06UL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Positioning);
}

void Ft_Esd_Ring__Initializer(Ft_Esd_Ring *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_Ring_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_Ring__Slots;
	context->Widget.LocalX = 1;
	context->Widget.LocalY = 3;
	context->Widget.LocalWidth = 311;
	context->Widget.LocalHeight = 284;
	context->Angle = Ft_Esd_Ring_Angle__Default;
	context->Clockwise = Ft_Esd_Ring_Clockwise__Default;
	context->Origin = Ft_Esd_Ring_Origin__Default;
	context->RingWidth = Ft_Esd_Ring_RingWidth__Default;
	context->InnerBorder = Ft_Esd_Ring_InnerBorder__Default;
	context->OuterBorder = Ft_Esd_Ring_OuterBorder__Default;
	context->StartPoint = Ft_Esd_Ring_StartPoint__Default;
	context->EndPoint = Ft_Esd_Ring_EndPoint__Default;
	context->BackgroundColor = Ft_Esd_Ring_BackgroundColor__Default;
	context->SelectionColor = Ft_Esd_Ring_SelectionColor__Default;
	context->BorderColor = Ft_Esd_Ring_BorderColor__Default;
	Ft_Esd_Ring__Fixed_Positioning__Initializer(context);
	Ft_Esd_Ring__ArcLine__Initializer(context);
	Ft_Esd_Ring__CircleLineBG__Initializer(context);
	Ft_Esd_Ring__CircleLineBorder__Initializer(context);
}

void Ft_Esd_Ring_Update(Ft_Esd_Ring *context)
{
	void *owner = context->Owner;
	int update_variable = context->OuterBorder(owner);
	Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->ArcLine, update_variable);
	int update_variable_1 = context->OuterBorder(owner);
	Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->ArcLine, update_variable_1);
	ft_int16_t left = context->Widget.GlobalWidth;
	int left_1 = context->OuterBorder(owner);
	int right_1 = context->OuterBorder(owner);
	int right = left_1 + right_1;
	int update_variable_2 = left - right;
	Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)&context->ArcLine, update_variable_2);
	ft_int16_t left_2 = context->Widget.GlobalHeight;
	int left_3 = context->OuterBorder(owner);
	int right_3 = context->OuterBorder(owner);
	int right_2 = left_3 + right_3;
	int update_variable_3 = left_2 - right_2;
	Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)&context->ArcLine, update_variable_3);
	int update_variable_4 = context->RingWidth(owner);
	context->ArcLine.Border = update_variable_4;
	ft_argb32_t update_variable_5 = context->SelectionColor(owner);
	context->ArcLine.Color = update_variable_5;
	int update_variable_6 = context->Origin(owner);
	context->ArcLine.Origin = update_variable_6;
	ft_int16_t update_variable_7 = context->Angle(owner);
	context->ArcLine.Angle = update_variable_7;
	ft_bool_t update_variable_8 = context->Clockwise(owner);
	context->ArcLine.IsClockwise = update_variable_8;
	ft_bool_t update_variable_9 = context->StartPoint(owner);
	context->ArcLine.ShowStartPoint = update_variable_9;
	ft_bool_t update_variable_10 = context->EndPoint(owner);
	context->ArcLine.ShowEndPoint = update_variable_10;
	ft_bool_t value = context->CircleLineBorder.Widget.Active;
	int left_4 = !value;
	ft_argb32_t left_5 = context->BorderColor(owner);
	ft_argb32_t right_5 = context->CircleLineBG.Color;
	int right_4 = left_5 != right_5;
	int update_variable_11 = left_4 || right_4;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->CircleLineBG, update_variable_11);
	int update_variable_12 = context->OuterBorder(owner);
	Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->CircleLineBG, update_variable_12);
	int update_variable_13 = context->OuterBorder(owner);
	Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->CircleLineBG, update_variable_13);
	ft_int16_t left_6 = context->Widget.GlobalWidth;
	int left_7 = context->OuterBorder(owner);
	int right_7 = context->OuterBorder(owner);
	int right_6 = left_7 + right_7;
	int update_variable_14 = left_6 - right_6;
	Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)&context->CircleLineBG, update_variable_14);
	ft_int16_t left_8 = context->Widget.GlobalHeight;
	int left_9 = context->OuterBorder(owner);
	int right_9 = context->OuterBorder(owner);
	int right_8 = left_9 + right_9;
	int update_variable_15 = left_8 - right_8;
	Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)&context->CircleLineBG, update_variable_15);
	int update_variable_16 = context->RingWidth(owner);
	context->CircleLineBG.Border = update_variable_16;
	ft_argb32_t update_variable_17 = context->BackgroundColor(owner);
	context->CircleLineBG.Color = update_variable_17;
	int left_11 = context->InnerBorder(owner);
	int right_10 = 0L;
	int left_10 = left_11 > right_10;
	int left_12 = context->OuterBorder(owner);
	int right_12 = 0L;
	int right_11 = left_12 > right_12;
	int update_variable_18 = left_10 || right_11;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->CircleLineBorder, update_variable_18);
	ft_int16_t update_variable_19 = context->Widget.GlobalWidth;
	Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)&context->CircleLineBorder, update_variable_19);
	ft_int16_t update_variable_20 = context->Widget.GlobalHeight;
	Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)&context->CircleLineBorder, update_variable_20);
	int left_13 = context->RingWidth(owner);
	int left_14 = context->InnerBorder(owner);
	int right_14 = context->OuterBorder(owner);
	int right_13 = left_14 + right_14;
	int update_variable_21 = left_13 + right_13;
	context->CircleLineBorder.Border = update_variable_21;
	ft_argb32_t update_variable_22 = context->BorderColor(owner);
	context->CircleLineBorder.Color = update_variable_22;
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void Ft_Esd_Ring_End(Ft_Esd_Ring *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Positioning); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ArcLine); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->CircleLineBG); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->CircleLineBorder); 
}


/* end of file */
