/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_Video
C Source
*/

#include "Ft_Esd_Video.h"

#include "Esd_Context.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
Ft_Esd_BitmapCell Ft_Esd_Video_VideoFile__Default(void *context) { return (Ft_Esd_BitmapCell){ 0 }; }


static Ft_Esd_WidgetSlots s_Ft_Esd_Video__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Video_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Video_Update,
	(void(*)(void *))Ft_Esd_Video_Render,
	(void(*)(void *))Ft_Esd_Video_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Video_End,
};


void Ft_Esd_Video__Initializer(Ft_Esd_Video *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_Video_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_Video__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->VideoFile = Ft_Esd_Video_VideoFile__Default;
	context->Color = 0xffffffffUL;
	context->Align = ESD_ALIGN_TOPLEFT;
	context->Scaling = ESD_SCALING_STRETCH;
	context->AutoResize = ESD_AUTORESIZE_BOTH;
	context->ScaleX = (1L * (1L << 16) + 0x0L);
	context->ScaleY = (1L * (1L << 16) + 0x0L);
	context->Loop = 0;
	context->Sound = 0;
}

void Ft_Esd_Video_Loop_Play(Ft_Esd_Video *context);
void Ft_Esd_Video_Render_Signal(Ft_Esd_Video *context);
void Ft_Esd_Video_Playing(Ft_Esd_Video *context);
void Ft_Esd_Video_Stop_Signal(Ft_Esd_Video *context);

void Ft_Esd_Video_Start(Ft_Esd_Video *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context); 
}

void Ft_Esd_Video_Update(Ft_Esd_Video *context)
{
	void *owner = context->Owner;
	Ft_Esd_Video_Loop_Play(context);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context); 
}

void Ft_Esd_Video_Render(Ft_Esd_Video *context)
{
	void *owner = context->Owner;
	Ft_Esd_Video_Render_Signal(context);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

void Ft_Esd_Video_Idle(Ft_Esd_Video *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Idle((Ft_Esd_Widget *)context); 
}

void Ft_Esd_Video_End(Ft_Esd_Video *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context); 
}

void Ft_Esd_Video_Play(Ft_Esd_Video *context)
{
	void *owner = context->Owner;
	Ft_Esd_Video_Playing(context);
}

void Ft_Esd_Video_Stop(Ft_Esd_Video *context)
{
	void *owner = context->Owner;
	Ft_Esd_Video_Stop_Signal(context);
}


/* end of file */
