/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_Image
C Source
*/

/*
Comment :
Introduction:
This widget draws an image from Resources.
*/

#include "Ft_Esd_Image.h"

#include "Esd_Context.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
Ft_Esd_BitmapCell Ft_Esd_Image_BitmapCell__Default(void *context) { return (Ft_Esd_BitmapCell){ 0 }; }
ft_uint8_t Ft_Esd_Image_MinAlpha__Default(void *context) { return 1; }


static Ft_Esd_WidgetSlots s_Ft_Esd_Image__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Image_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Widget_End,
};


void Ft_Esd_Image__Initializer(Ft_Esd_Image *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_Image_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_Image__Slots;
	context->Widget.LocalX = 70;
	context->Widget.LocalY = 92;
	context->Widget.LocalWidth = 100;
	context->Widget.LocalHeight = 100;
	context->RenderComplete = Esd_Noop;
	context->Color = 0xffffffffUL;
	context->BitmapCell = Ft_Esd_Image_BitmapCell__Default;
	context->Align = ESD_ALIGN_TOPLEFT;
	context->Scaling = ESD_SCALING_ORIGINAL;
	context->AutoResize = ESD_AUTORESIZE_BOTH;
	context->ScaleX = (1L * (1L << 16) + 0x0L);
	context->ScaleY = (1L * (1L << 16) + 0x0L);
	context->MinAlpha = Ft_Esd_Image_MinAlpha__Default;
}

void Ft_Esd_Image_Render_Bitmap(Ft_Esd_Image *context);

void Ft_Esd_Image_Render(Ft_Esd_Image *context)
{
	void *owner = context->Owner;
	Ft_Esd_Image_Render_Bitmap(context);
	context->RenderComplete(owner);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}


/* end of file */
