/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_Arc
Header
*/

#ifndef Ft_Esd_Arc__H
#define Ft_Esd_Arc__H

#include "Esd_Base.h"
#include "Ft_Esd.h"
#include "Ft_Esd_RenderForwarder.h"
#include "Ft_Esd_Widget.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_ARRAY_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define Ft_Esd_Arc_CLASSID 0x5A78514B
ESD_SYMBOL(Ft_Esd_Arc_CLASSID, Type = esd_classid_t)

/* ESD Arc widget is supported exclusively by BT820. */
ESD_WIDGET(Ft_Esd_Arc, Include = "Ft_Esd_Arc.h", Callback, DisplayName = "ESD Arc", Category = EsdBasicWidgets, Icon = ":/icons/layer-shape-curve.png", X = 0, Y = 0, Width = 400, Height = 300, BackToFront)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	ESD_VARIABLE(cX, Type = int, Private)
	int cX;
	ESD_VARIABLE(cY, Type = int, Private)
	int cY;
	ESD_VARIABLE(Color, Type = ft_argb32_t, Default = #ffffff, Public)
	ft_argb32_t Color;
	ESD_VARIABLE(Radius, Type = int, Default = 100, Private)
	int Radius;
	ESD_VARIABLE(Border, Type = int, Min = 0, Default = 20, Public)
	int Border;
	/* The starting point of the arc ranges from 0 to 65535 (0xFFFF) */
	ESD_VARIABLE(StartPoint, DisplayName = "Start Point", Type = int, Min = 0, Max = 65535, Public)
	int StartPoint;
	/* The ending point of the arc ranges from 0 to 65535 (0xFFFF). */
	ESD_VARIABLE(EndPoint, DisplayName = "End Point", Type = int, Min = 0, Max = 65535, Default = 26380, Public)
	int EndPoint;
	Ft_Esd_RenderForwarder Render_Forwarder;
} Ft_Esd_Arc;

void Ft_Esd_Arc__Initializer(Ft_Esd_Arc *context);

ESD_SLOT(End)
void Ft_Esd_Arc_End(Ft_Esd_Arc *context);

#endif /* Ft_Esd_Arc__H */

/* end of file */
