/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_MultiGradientRounded
C Source
*/

/*
Comment :
Introduction:
This widget draws a four-color gradient rectangle.
Alpha channel can be changed.
*/

#include "Ft_Esd_MultiGradientRounded.h"

#include "Esd_Context.h"
#include "Esd_Core.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);


static Ft_Esd_WidgetSlots s_Ft_Esd_MultiGradientRounded__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_MultiGradientRounded_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Widget_End,
};


void Ft_Esd_MultiGradientRounded__Initializer(Ft_Esd_MultiGradientRounded *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_MultiGradientRounded_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_MultiGradientRounded__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 300;
	context->Widget.LocalHeight = 225;
	context->Alpha = 255;
	context->Radius = (4 * (1 << 4) + 0x0);
	context->TopLeft = 0xff0012UL;
	context->TopRight = 0x31ff00UL;
	context->BottomLeft = 0x6700ffUL;
	context->BottomRight = 0xd1ffUL;
}

ESD_CORE_EXPORT void Esd_Render_MultiGradient_Rounded(int16_t, int16_t, int16_t, int16_t, esd_int32_f4_t, uint8_t, esd_rgb32_t, esd_rgb32_t, esd_rgb32_t, esd_rgb32_t);

void Ft_Esd_MultiGradientRounded_Render(Ft_Esd_MultiGradientRounded *context)
{
	void *owner = context->Owner;
	ft_int16_t x = context->Widget.GlobalX;
	ft_int16_t y = context->Widget.GlobalY;
	ft_int16_t width = context->Widget.GlobalWidth;
	ft_int16_t height = context->Widget.GlobalHeight;
	ft_int32_f4_t radius = context->Radius;
	ft_uint8_t alpha = context->Alpha;
	ft_rgb32_t topLeft = context->TopLeft;
	ft_rgb32_t topRight = context->TopRight;
	ft_rgb32_t bottomLeft = context->BottomLeft;
	ft_rgb32_t bottomRight = context->BottomRight;
	Esd_Render_MultiGradient_Rounded(x, y, width, height, radius, alpha, topLeft, topRight, bottomLeft, bottomRight);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context);
}


/* end of file */
