/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_Glow
Header
*/

#ifndef Ft_Esd_Glow__H
#define Ft_Esd_Glow__H

#include "Esd_Base.h"
#include "Ft_Esd.h"
#include "Ft_Esd_Math.h"
#include "Ft_Esd_Widget.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_ARRAY_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define Ft_Esd_Glow_CLASSID 0x41632342
ESD_SYMBOL(Ft_Esd_Glow_CLASSID, Type = esd_classid_t)

/* ESD Glow widget is supported exclusively by BT820. */
ESD_WIDGET(Ft_Esd_Glow, Include = "Ft_Esd_Glow.h", Callback, DisplayName = "ESD Glow", Category = EsdBasicWidgets, Icon = ":/icons/layer-shape-ellipse.png", X = 0, Y = 0, Width = 100, Height = 100, BackToFront)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	ESD_VARIABLE(Color, Type = esd_argb32_t, Default = #ffffff, Public)
	esd_argb32_t Color;
} Ft_Esd_Glow;

void Ft_Esd_Glow__Initializer(Ft_Esd_Glow *context);

ESD_SLOT(Start)
void Ft_Esd_Glow_Start(Ft_Esd_Glow *context);

ESD_SLOT(Update)
void Ft_Esd_Glow_Update(Ft_Esd_Glow *context);

ESD_SLOT(Render)
void Ft_Esd_Glow_Render(Ft_Esd_Glow *context);

ESD_SLOT(Idle)
void Ft_Esd_Glow_Idle(Ft_Esd_Glow *context);

ESD_SLOT(End)
void Ft_Esd_Glow_End(Ft_Esd_Glow *context);

#endif /* Ft_Esd_Glow__H */

/* end of file */
