/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_SignalSwitch
C Source
*/

#include "Ft_Esd_SignalSwitch.h"

#include "Esd_Context.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
Ft_Esd_Widget * Ft_Esd_SignalSwitch_InitialPrevious__Default(void *context) { return 0x0; }
Ft_Esd_Widget * Ft_Esd_SignalSwitch_InitialCurrent__Default(void *context) { return 0x0; }
Ft_Esd_Widget * Ft_Esd_SignalSwitch_InitialNext__Default(void *context) { return 0x0; }
int Ft_Esd_SignalSwitch_InitialIndex__Default(void *context) { return 1L; }
Ft_Esd_Widget * Ft_Esd_SignalSwitch_New__Default(void *context) { return 0x0; }


static Ft_Esd_WidgetSlots s_Ft_Esd_SignalSwitch__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_SignalSwitch_Update,
	(void(*)(void *))Ft_Esd_SignalSwitch_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_SignalSwitch_End,
};


Ft_Esd_Widget *Ft_Esd_SignalSwitch_Widget_Interface__Container(void *context);

void Ft_Esd_SignalSwitch__ScrollPanel__Initializer(Ft_Esd_SignalSwitch *context)
{
	Ft_Esd_ScrollPanel *object = (Ft_Esd_ScrollPanel *)&context->ScrollPanel;
	Ft_Esd_ScrollPanel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = -2;
	object->Widget.LocalY = 41;
	object->Widget.LocalWidth = 322;
	object->Widget.LocalHeight = 431;
	object->Align = ESD_ALIGN_TOPLEFT;
	object->TouchScroll = 0;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Ft_Esd_SignalSwitch__FixedPositioning__Initializer(Ft_Esd_SignalSwitch *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->FixedPositioning;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 1016;
	object->Widget.LocalHeight = 390;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->ScrollPanel);
}

void Ft_Esd_SignalSwitch__Initializer(Ft_Esd_SignalSwitch *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_SignalSwitch_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_SignalSwitch__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->InitialPrevious = Ft_Esd_SignalSwitch_InitialPrevious__Default;
	context->InitialCurrent = Ft_Esd_SignalSwitch_InitialCurrent__Default;
	context->InitialNext = Ft_Esd_SignalSwitch_InitialNext__Default;
	context->InitialIndex = Ft_Esd_SignalSwitch_InitialIndex__Default;
	context->SwitchSpeed = 4L;
	context->Count = 4L;
	context->Target = 0L;
	context->Looping = 1;
	context->Direction = ESD_HORIZONTAL;
	context->State = 0L;
	context->Shifting = 0;
	context->UpdatePos = 0L;
	context->NewPage = Esd_Noop;
	context->New = Ft_Esd_SignalSwitch_New__Default;
	context->Previous = 0x0;
	context->Index = 1L;
	context->Current = 0x0;
	context->NewIndex = 1L;
	context->Next = 0x0;
	Ft_Esd_SignalSwitch__ScrollPanel__Initializer(context);
	Ft_Esd_SignalSwitch__FixedPositioning__Initializer(context);
	context->Widget.Container = Ft_Esd_SignalSwitch_Widget_Interface__Container(context);
}

void Esd_Switch_NextPage(Ft_Esd_SignalSwitch *context);
void Esd_Switch_PreviousPage(Ft_Esd_SignalSwitch *context);
void Ft_Esd_SignalSwitch_Initialise_Signal(Ft_Esd_SignalSwitch *context);
void Esd_Switch_Update_Handle(Ft_Esd_SignalSwitch *context);
void Esd_Switch_Render_Signal(Ft_Esd_SignalSwitch *context);

void Ft_Esd_SignalSwitch_Update__Builtin(Ft_Esd_SignalSwitch *context)
{
	void *owner = context->Owner;
	ft_int16_t update_variable = context->Widget.GlobalWidth;
	Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)&context->ScrollPanel, update_variable);
	ft_int16_t update_variable_1 = context->Widget.GlobalHeight;
	Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)&context->ScrollPanel, update_variable_1);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void Ft_Esd_SignalSwitch_End(Ft_Esd_SignalSwitch *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ScrollPanel); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->FixedPositioning); 
}

void Ft_Esd_SignalSwitch_NextPageSignal(Ft_Esd_SignalSwitch *context)
{
	void *owner = context->Owner;
	Esd_Switch_NextPage(context);
}

void Ft_Esd_SignalSwitch_PreviousPageSignal(Ft_Esd_SignalSwitch *context)
{
	void *owner = context->Owner;
	Esd_Switch_PreviousPage(context);
}

void Ft_Esd_SignalSwitch_Initialise(Ft_Esd_SignalSwitch *context)
{
	void *owner = context->Owner;
	Ft_Esd_SignalSwitch_Initialise_Signal(context);
}

void Ft_Esd_SignalSwitch_Update(Ft_Esd_SignalSwitch *context)
{
	void *owner = context->Owner;
	Esd_Switch_Update_Handle(context);
	Ft_Esd_SignalSwitch_Update__Builtin(context);
}

Ft_Esd_Widget * Ft_Esd_SignalSwitch_Widget_Interface__Container(void *c)
{
	Ft_Esd_SignalSwitch *context = (Ft_Esd_SignalSwitch *)c;
	void *owner = context->Owner;
	return (Ft_Esd_Widget *)&context->FixedPositioning;
}

void Ft_Esd_SignalSwitch_Render(Ft_Esd_SignalSwitch *context)
{
	void *owner = context->Owner;
	Esd_Switch_Render_Signal(context);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}


/* end of file */
