/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_CircularGradient
C Source
*/

/*
Comment :
Introduction:
This widget draws two-color gradient in circular form.
It supports two algorithms Pythagorean and Gaussian.
*/

#include "Ft_Esd_CircularGradient.h"

#include "Esd_Context.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
ft_argb32_t Ft_Esd_CircularGradient_Outer_color__Default(void *context) { return 0xff1b06faUL; }
ft_argb32_t Ft_Esd_CircularGradient_Inner_color__Default(void *context) { return 0xfff8ef86UL; }
ft_uint8_t Ft_Esd_CircularGradient_Gradient_Type__Default(void *context) { return ESD_PYTHAGOREAN; }


static Ft_Esd_WidgetSlots s_Ft_Esd_CircularGradient__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_CircularGradient_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_CircularGradient_Update,
	(void(*)(void *))Ft_Esd_CircularGradient_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Widget_End,
};


void Ft_Esd_CircularGradient__Initializer(Ft_Esd_CircularGradient *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_CircularGradient_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_CircularGradient__Slots;
	context->Widget.LocalX = 657;
	context->Widget.LocalY = 462;
	context->Widget.LocalWidth = 320;
	context->Widget.LocalHeight = 315;
	context->Outer_color = Ft_Esd_CircularGradient_Outer_color__Default;
	context->Inner_color = Ft_Esd_CircularGradient_Inner_color__Default;
	context->Check_Gradient_Type_Changed__0 = 0;
	context->Gradient_Type = Ft_Esd_CircularGradient_Gradient_Type__Default;
}

void Ft_Esd_CircularGradient_Update_Signal(Ft_Esd_CircularGradient *context, ft_uint8_t);
void Circular_Gradient_Widget_Render_Circular(Ft_Esd_CircularGradient *context, int32_t, int32_t, int32_t, int32_t, ft_argb32_t, ft_argb32_t, ft_uint8_t);

void Ft_Esd_CircularGradient_Start(Ft_Esd_CircularGradient *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context); 
	ft_uint8_t gradientType = context->Gradient_Type(owner);
	Ft_Esd_CircularGradient_Update_Signal(context, gradientType);
}

void Ft_Esd_CircularGradient_Update(Ft_Esd_CircularGradient *context)
{
	void *owner = context->Owner;
	ft_uint8_t watched__0 = context->Gradient_Type(owner);
	if (context->Check_Gradient_Type_Changed__0 != watched__0)
	{
		context->Check_Gradient_Type_Changed__0 = watched__0;
		ft_uint8_t gradientType_1 = context->Gradient_Type(owner);
		Ft_Esd_CircularGradient_Update_Signal(context, gradientType_1);
	}
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context); 
}

void Ft_Esd_CircularGradient_Render(Ft_Esd_CircularGradient *context)
{
	void *owner = context->Owner;
	ft_int16_t x0 = context->Widget.GlobalX;
	ft_int16_t y0 = context->Widget.GlobalY;
	ft_int16_t left = context->Widget.GlobalX;
	ft_int16_t right = context->Widget.GlobalWidth;
	int x1_1 = left + right;
	ft_int16_t left_1 = context->Widget.GlobalY;
	ft_int16_t right_1 = context->Widget.GlobalHeight;
	int y1_1 = left_1 + right_1;
	ft_argb32_t color1 = context->Outer_color(owner);
	ft_argb32_t color2 = context->Inner_color(owner);
	ft_uint8_t gradientType_2 = context->Gradient_Type(owner);
	Circular_Gradient_Widget_Render_Circular(context, x0, y0, x1_1, y1_1, color1, color2, gradientType_2);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}


/* end of file */
