/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_RadioGroup
C Source
*/

#include "Ft_Esd_RadioGroup.h"


ESD_CORE_EXPORT void Esd_Noop(void *context);



void Ft_Esd_RadioGroup__Initializer(Ft_Esd_RadioGroup *context)
{
	context->Owner = 0;
	context->Checked = 0x0;
}

void Ft_Esd_RadioGroup_Reset_Signal(Ft_Esd_RadioGroup *context);
Ft_Esd_RadioGroup *Ft_Esd_RadioGroup_GetPointer(Ft_Esd_RadioGroup *context);

void Ft_Esd_RadioGroup_Reset(Ft_Esd_RadioGroup *context)
{
	void *owner = context->Owner;
	Ft_Esd_RadioGroup_Reset_Signal(context);
}

Ft_Esd_RadioGroup * Ft_Esd_RadioGroup_Pointer(Ft_Esd_RadioGroup *context)
{
	void *owner = context->Owner;
	return Ft_Esd_RadioGroup_GetPointer(context);
}


/* end of file */
