/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_Cgradient
C Source
*/

#include "Ft_Esd_Cgradient.h"

#include "Esd_Context.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);


static Ft_Esd_WidgetSlots s_Ft_Esd_Cgradient__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Cgradient_End,
};

static void Ft_Esd_Cgradient_Render_Forwarder_ForwardRender__Signal(void *context);

void Ft_Esd_Cgradient__Render_Forwarder__Initializer(Ft_Esd_Cgradient *context)
{
	Ft_Esd_RenderForwarder *object = (Ft_Esd_RenderForwarder *)&context->Render_Forwarder;
	Ft_Esd_RenderForwarder__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 10;
	object->Widget.LocalY = 10;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->ForwardRender = Ft_Esd_Cgradient_Render_Forwarder_ForwardRender__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Ft_Esd_Cgradient__Initializer(Ft_Esd_Cgradient *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_Cgradient_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_Cgradient__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->Shape = ESD_CORNER_ZERO;
	context->OuterColor = 0xff4bff23UL;
	context->InnerColor = 0xffd42323UL;
	Ft_Esd_Cgradient__Render_Forwarder__Initializer(context);
}

void Ft_Esd_Cgradient_Render_Signal(Ft_Esd_Cgradient *context, int, int, int, int, int, ft_argb32_t, ft_argb32_t);

void Ft_Esd_Cgradient_End(Ft_Esd_Cgradient *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Render_Forwarder); 
}

void Ft_Esd_Cgradient_Render_Forwarder_ForwardRender__Signal(void *c)
{
	Ft_Esd_Cgradient *context = (Ft_Esd_Cgradient *)c;
	void *owner = context->Owner;
	ft_uint8_t shape = context->Shape;
	ft_int16_t x = Ft_Esd_RenderForwarder_GlobalX(&context->Render_Forwarder);
	ft_int16_t y = Ft_Esd_RenderForwarder_GlobalY(&context->Render_Forwarder);
	ft_int16_t w = Ft_Esd_RenderForwarder_GlobalWidth(&context->Render_Forwarder);
	ft_int16_t h = Ft_Esd_RenderForwarder_GlobalHeight(&context->Render_Forwarder);
	esd_argb32_t color1 = context->OuterColor;
	esd_argb32_t color2 = context->InnerColor;
	Ft_Esd_Cgradient_Render_Signal(context, shape, x, y, w, h, color1, color2);
}


/* end of file */
