/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_Joypad
C Source
*/

#include "Ft_Esd_Joypad.h"

#include "Esd_Context.h"
#include "EVE_CoDl.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
int Ft_Esd_Joypad_KnobRadius__Default(void *context) { return 25L; }
ft_argb32_t Ft_Esd_Joypad_KnobColor__Default(void *context) { return 0xff000000UL; }

static Ft_Esd_BitmapCell Ft_Esd_Joypad_ESD_Image_BitmapCell__Property(void *context);

static Ft_Esd_WidgetSlots s_Ft_Esd_Joypad__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Joypad_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Joypad_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Joypad_End,
};

static void Ft_Esd_Joypad_Touch_Tag_Down__Signal(void *context);
static void Ft_Esd_Joypad_Touch_Tag_Up__Signal(void *context);
static void Ft_Esd_Joypad_Render_Forwarder_ForwardRender__Signal(void *context);

void Ft_Esd_Joypad__Touch_Tag__Initializer(Ft_Esd_Joypad *context)
{
	Ft_Esd_TouchTag *object = (Ft_Esd_TouchTag *)&context->Touch_Tag;
	Ft_Esd_TouchTag__Initializer(object);
	object->Owner = (void *)context;
	object->Down = Ft_Esd_Joypad_Touch_Tag_Down__Signal;
	object->Up = Ft_Esd_Joypad_Touch_Tag_Up__Signal;
}

void Ft_Esd_Joypad__ESD_Image__Initializer(Ft_Esd_Joypad *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)context->ESD_Image;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.LocalX = 70;
	object->Widget.LocalY = 92;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 100;
	object->BitmapCell = Ft_Esd_Joypad_ESD_Image_BitmapCell__Property;
	object->Scaling = ESD_SCALING_FILL;
	object->AutoResize = ESD_AUTORESIZE_NONE;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Ft_Esd_Joypad__ESD_Image__Validate(Ft_Esd_Joypad *context)
{
	if (!context->ESD_Image)
	{
		context->ESD_Image = (Ft_Esd_Image *)esd_malloc(sizeof(Ft_Esd_Image));
		if (context->ESD_Image)
		{
			Ft_Esd_Joypad__ESD_Image__Initializer(context);
			context->ESD_Image->Widget.Slots->Start(context->ESD_Image);
		}
		else
		{
			eve_printf_debug("Out of memory (Ft_Esd_Joypad__ESD_Image__Validate)");
		}
	}
}

void Ft_Esd_Joypad__ESD_Image__Destroy(Ft_Esd_Joypad *context)
{
	if (context->ESD_Image)
	{
		Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->ESD_Image, 0);
		Ft_Esd_Widget_Detach((Ft_Esd_Widget *)context->ESD_Image);
		context->ESD_Image->Widget.Slots->End(context->ESD_Image);
		Ft_Esd_Widget_Free((Ft_Esd_Widget *)context->ESD_Image);
		context->ESD_Image = 0;
	}
}

void Ft_Esd_Joypad__Render_Forwarder__Initializer(Ft_Esd_Joypad *context)
{
	Ft_Esd_RenderForwarder *object = (Ft_Esd_RenderForwarder *)&context->Render_Forwarder;
	Ft_Esd_RenderForwarder__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->ForwardRender = Ft_Esd_Joypad_Render_Forwarder_ForwardRender__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Ft_Esd_Joypad__Initializer(Ft_Esd_Joypad *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_Joypad_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_Joypad__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 200;
	context->Widget.LocalHeight = 200;
	context->IsDown = 0;
	context->LockXAxis = 0;
	context->LockYAxis = 0;
	context->DefaultBackground = 1;
	context->BackgroundImage = (Ft_Esd_BitmapCell){ 0 };
	context->KnobRadius = Ft_Esd_Joypad_KnobRadius__Default;
	context->KnobColor = Ft_Esd_Joypad_KnobColor__Default;
	context->AngleValue = 0L;
	context->DistanceFrCenterValue = 0L;
	context->Variable = 0L;
	context->Variable_2 = 0L;
	context->Variable_3 = 0L;
	context->Variable_4 = 0L;
	context->KnobX_Value = 0L;
	context->KnobY_Value = 0L;
	Ft_Esd_Joypad__Touch_Tag__Initializer(context);
	context->ESD_Image = 0;
	Ft_Esd_Joypad__Render_Forwarder__Initializer(context);
}

void Ft_Esd_Joypad_Render_Func(Ft_Esd_Joypad *context, int, int, int, int);
void Ft_Esd_Knob_Render_Func(Ft_Esd_Joypad *context, int, int, int, int, int, int, int, int, ft_argb32_t);

void Ft_Esd_Joypad_Start(Ft_Esd_Joypad *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context);
	Ft_Esd_TouchTag_Start(&context->Touch_Tag);
	Ft_Esd_Joypad__ESD_Image__Validate(context);
	Ft_Esd_Widget_SetActive(context->ESD_Image, 1);
}

void Ft_Esd_Joypad_Update(Ft_Esd_Joypad *context)
{
	void *owner = context->Owner;
	Ft_Esd_TouchTag_Update(&context->Touch_Tag);
	if (context->ESD_Image && !context->ESD_Image->Widget.Active)
	{
		Ft_Esd_Joypad__ESD_Image__Destroy(context);
	}
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void Ft_Esd_Joypad_End(Ft_Esd_Joypad *context)
{
	void *owner = context->Owner;
	Ft_Esd_TouchTag_End(&context->Touch_Tag);
	Ft_Esd_Joypad__ESD_Image__Destroy(context); 
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Render_Forwarder); 
}

int Ft_Esd_Joypad_Angle(Ft_Esd_Joypad *context)
{
	void *owner = context->Owner;
	return context->AngleValue;
}

int Ft_Esd_Joypad_DistFrCenter(Ft_Esd_Joypad *context)
{
	void *owner = context->Owner;
	return context->DistanceFrCenterValue;
}

int Ft_Esd_Joypad_KnobX(Ft_Esd_Joypad *context)
{
	void *owner = context->Owner;
	return context->KnobX_Value;
}

int Ft_Esd_Joypad_KnobY(Ft_Esd_Joypad *context)
{
	void *owner = context->Owner;
	return context->KnobY_Value;
}

void Ft_Esd_Joypad_Touch_Tag_Down__Signal(void *c)
{
	Ft_Esd_Joypad *context = (Ft_Esd_Joypad *)c;
	void *owner = context->Owner;
	bool set_variable_3 = 1;
	context->IsDown = set_variable_3;
}

void Ft_Esd_Joypad_Touch_Tag_Up__Signal(void *c)
{
	Ft_Esd_Joypad *context = (Ft_Esd_Joypad *)c;
	void *owner = context->Owner;
	bool set_variable_4 = 0;
	context->IsDown = set_variable_4;
}

Ft_Esd_BitmapCell Ft_Esd_Joypad_ESD_Image_BitmapCell__Property(void *c)
{
	Ft_Esd_Joypad *context = (Ft_Esd_Joypad *)c;
	void *owner = context->Owner;
	return context->BackgroundImage;
}

void Ft_Esd_Joypad_Render_Forwarder_ForwardRender__Signal(void *c)
{
	Ft_Esd_Joypad *context = (Ft_Esd_Joypad *)c;
	void *owner = context->Owner;
	Ft_Esd_Joypad__ESD_Image__Validate(context);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->ESD_Image, 1);
	ft_int16_t x = context->Widget.GlobalX;
	ft_int16_t y = context->Widget.GlobalY;
	ft_int16_t width = context->Widget.GlobalWidth;
	ft_int16_t height = context->Widget.GlobalHeight;
	Ft_Esd_Joypad_Render_Func(context, x, y, width, height);
	EVE_HalContext * phost = Esd_GetHost();
	ft_uint8_t s = Ft_Esd_TouchTag_Tag(&context->Touch_Tag);
	EVE_CoDl_tag(phost, s);
	int left = context->Variable;
	bool if_1 = context->LockXAxis;
	int right;
	if (if_1)
	{
		right = 0L;
	}
	else
	{
		right = Ft_Esd_TouchTag_TouchXDelta(&context->Touch_Tag);
	}
	int set_variable = left + right;
	context->Variable = set_variable;
	context->Variable_2 = set_variable;
	int left_1 = context->Variable_3;
	bool if_2 = context->LockYAxis;
	int right_1;
	if (if_2)
	{
		right_1 = 0L;
	}
	else
	{
		right_1 = Ft_Esd_TouchTag_TouchYDelta(&context->Touch_Tag);
	}
	int set_variable_5 = left_1 + right_1;
	context->Variable_3 = set_variable_5;
	context->Variable_4 = set_variable_5;
	ft_int16_t x_1 = context->Widget.GlobalX;
	ft_int16_t y_1 = context->Widget.GlobalY;
	ft_int16_t width_1 = context->Widget.GlobalWidth;
	ft_int16_t height_1 = context->Widget.GlobalHeight;
	ft_uint8_t tagID = Ft_Esd_TouchTag_CurrentTag(&context->Touch_Tag);
	int knobX = context->Variable_2;
	int knobY = context->Variable_4;
	int knobRadius = context->KnobRadius(owner);
	ft_argb32_t knobColor = context->KnobColor(owner);
	Ft_Esd_Knob_Render_Func(context, x_1, y_1, width_1, height_1, tagID, knobX, knobY, knobRadius, knobColor);
	EVE_HalContext * phost_1 = Esd_GetHost();
	eve_tag_t s_1 = 255UL;
	EVE_CoDl_tag(phost_1, s_1);
	bool if_3 = context->IsDown;
	if (if_3)
	{
	}
	else
	{
		ft_int16_t set_variable_6 = context->Widget.GlobalY;
		context->Variable_3 = set_variable_6;
		ft_int16_t set_variable_2 = context->Widget.GlobalX;
		context->Variable = set_variable_2;
	}
}


/* end of file */
