/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_IntCounter
C Source
*/

#include "Ft_Esd_IntCounter.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);



void Ft_Esd_IntCounter__Initializer(Ft_Esd_IntCounter *context)
{
	context->Owner = 0;
	context->Value = 0L;
	context->Step = 1L;
}

void Ft_Esd_IntCounter_Inc(Ft_Esd_IntCounter *context)
{
	void *owner = context->Owner;
	int left = context->Value;
	int right = context->Step;
	int set_variable = left + right;
	context->Value = set_variable;
}

void Ft_Esd_IntCounter_Dec(Ft_Esd_IntCounter *context)
{
	void *owner = context->Owner;
	int left_1 = context->Value;
	int right_1 = context->Step;
	int set_variable_1 = left_1 - right_1;
	context->Value = set_variable_1;
}


/* end of file */
