/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_NumericLabel
C Source
*/

/*
Comment :
Introduction:
This widget shows an integer in decimal or in hexadecimal format.
The number can be padded by zero or space.
Font type and font size can be customized.
CMD_TEXT is used internally.

*/

#include "Ft_Esd_NumericLabel.h"

#include "Esd_Context.h"
#include "Esd_BitmapHandle.h"
#include "Ft_Esd_BitmapHandle.h"
#include "Ft_Esd_CoCmd.h"
#include "Ft_Esd_Dl.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
Ft_Esd_Theme * Ft_Esd_NumericLabel_Theme__Default(void *context) { return Ft_Esd_Theme_GetCurrent(); }
uint8_t Ft_Esd_NumericLabel_Alpha__Default(void *context) { return 255; }
uint8_t Ft_Esd_NumericLabel_Font__Default(void *context) { return 27; }
Esd_FontInfo * Ft_Esd_NumericLabel_FontResource__Default(void *context) { return 0; }
ft_uint16_t Ft_Esd_NumericLabel_AlignX__Default(void *context) { return OPT_ALIGN_LEFT; }
ft_uint16_t Ft_Esd_NumericLabel_AlignY__Default(void *context) { return OPT_ALIGN_CENTER; }
ft_uint8_t Ft_Esd_NumericLabel_AutoResize__Default(void *context) { return ESD_AUTORESIZE_HEIGHT; }
ft_int32_t Ft_Esd_NumericLabel_Value__Default(void *context) { return 0L; }
ft_bool_t Ft_Esd_NumericLabel_EnablePadding__Default(void *context) { return 0; }
ft_int32_t Ft_Esd_NumericLabel_NoOfDigits__Default(void *context) { return 5L; }
ft_bool_t Ft_Esd_NumericLabel_IsZeroLeading__Default(void *context) { return 0; }
ft_bool_t Ft_Esd_NumericLabel_IsHexDisplay__Default(void *context) { return 0; }


static Ft_Esd_WidgetSlots s_Ft_Esd_NumericLabel__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_NumericLabel_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_NumericLabel_Update,
	(void(*)(void *))Ft_Esd_NumericLabel_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_NumericLabel_End,
};


void Ft_Esd_NumericLabel__Initializer(Ft_Esd_NumericLabel *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_NumericLabel_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_NumericLabel__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 120;
	context->Widget.LocalHeight = 36;
	context->Theme = Ft_Esd_NumericLabel_Theme__Default;
	context->Alpha = Ft_Esd_NumericLabel_Alpha__Default;
	context->X = 0;
	context->Y = 0;
	context->Option = OPT_SIGNED;
	context->Font = Ft_Esd_NumericLabel_Font__Default;
	context->Number = "";
	context->FontResource = Ft_Esd_NumericLabel_FontResource__Default;
	context->AlignX = Ft_Esd_NumericLabel_AlignX__Default;
	context->AlignY = Ft_Esd_NumericLabel_AlignY__Default;
	context->AutoResize = Ft_Esd_NumericLabel_AutoResize__Default;
	context->NDigit = 0L;
	context->Value = Ft_Esd_NumericLabel_Value__Default;
	context->EnablePadding = Ft_Esd_NumericLabel_EnablePadding__Default;
	context->NoOfDigits = Ft_Esd_NumericLabel_NoOfDigits__Default;
	context->IsZeroLeading = Ft_Esd_NumericLabel_IsZeroLeading__Default;
	context->IsHexDisplay = Ft_Esd_NumericLabel_IsHexDisplay__Default;
}

static uint16_t Ft_Esd_NumericLabel_Get_Font_Height_2__return(Ft_Esd_NumericLabel *context);

void Ft_Esd_NumericLabel_Start_Signal(Ft_Esd_NumericLabel *context);
void Ft_Esd_NumericLabel_End_Signal(Ft_Esd_NumericLabel *context);
ESD_CORE_EXPORT uint16_t Esd_GetFontBaseLine(Esd_FontInfo *);
ESD_CORE_EXPORT uint16_t Esd_GetFontCapsHeight(Esd_FontInfo *);
ESD_CORE_EXPORT uint16_t Esd_GetFontXOffset(Esd_FontInfo *);
ESD_CORE_EXPORT Esd_FontInfo *Esd_GetRomFont(uint8_t);
ESD_CORE_EXPORT uint16_t Esd_GetFontHeight(Esd_FontInfo *);
void Ft_Esd_NumericLabel_UpdateNumberString(Ft_Esd_NumericLabel *context);
void Ft_Esd_NumericLabel_ComputePosition(Ft_Esd_NumericLabel *context);

void Ft_Esd_NumericLabel_Start(Ft_Esd_NumericLabel *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context); 
	Ft_Esd_NumericLabel_Start_Signal(context);
}

void Ft_Esd_NumericLabel_End(Ft_Esd_NumericLabel *context)
{
	void *owner = context->Owner;
	Ft_Esd_NumericLabel_End_Signal(context);
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context); 
}

void Ft_Esd_NumericLabel_Render(Ft_Esd_NumericLabel *context)
{
	void *owner = context->Owner;
	uint8_t alpha = context->Alpha(owner);
	Ft_Esd_Dl_COLOR_A(alpha);
	Ft_Esd_Theme * theme = context->Theme(owner);
	ft_argb32_t c_1 = Ft_Esd_Theme_GetTextColor(theme);
	Ft_Esd_Dl_COLOR_RGB(c_1);
	EVE_HalContext * phost = Ft_Esd_GetHost();
	ft_int16_t x = context->X;
	ft_int16_t y = context->Y;
	Esd_FontInfo * if_1 = context->FontResource(owner);
	Esd_FontInfo *fontInfo;
	if (if_1)
	{
		fontInfo = context->FontResource(owner);
	}
	else
	{
		uint8_t i = context->Font(owner);
		fontInfo = Esd_GetRomFont(i);
	}
	uint8_t font = Ft_Esd_Dl_Font_Setup(fontInfo);
	uint16_t options = context->Option;
	ft_uint16_t left = context->AlignY(owner);
	ft_uint16_t right = OPT_ALIGN_BOTTOM;
	int bottom = left == right;
	Esd_FontInfo * if_2 = context->FontResource(owner);
	Esd_FontInfo *fontInfo_1;
	if (if_2)
	{
		fontInfo_1 = context->FontResource(owner);
	}
	else
	{
		uint8_t i_1 = context->Font(owner);
		fontInfo_1 = Esd_GetRomFont(i_1);
	}
	uint16_t baseLine = Esd_GetFontBaseLine(fontInfo_1);
	Esd_FontInfo * if_3 = context->FontResource(owner);
	Esd_FontInfo *fontInfo_2;
	if (if_3)
	{
		fontInfo_2 = context->FontResource(owner);
	}
	else
	{
		uint8_t i_2 = context->Font(owner);
		fontInfo_2 = Esd_GetRomFont(i_2);
	}
	uint16_t capsHeight = Esd_GetFontCapsHeight(fontInfo_2);
	Esd_FontInfo * if_4 = context->FontResource(owner);
	Esd_FontInfo *fontInfo_3;
	if (if_4)
	{
		fontInfo_3 = context->FontResource(owner);
	}
	else
	{
		uint8_t i_3 = context->Font(owner);
		fontInfo_3 = Esd_GetRomFont(i_3);
	}
	uint16_t xOffset = Esd_GetFontXOffset(fontInfo_3);
	char * s = context->Number;
	Ft_Gpu_CoCmd_Text_Ex(phost, x, y, font, options, bottom, baseLine, capsHeight, xOffset, s);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

ft_int16_t Ft_Esd_NumericLabel_FontHeight(Ft_Esd_NumericLabel *context)
{
	void *owner = context->Owner;
	return Ft_Esd_NumericLabel_Get_Font_Height_2__return(context);
}

uint16_t Ft_Esd_NumericLabel_Get_Font_Height_2__return(Ft_Esd_NumericLabel *context)
{
	void *owner = context->Owner;
	Esd_FontInfo * if_5 = context->FontResource(owner);
	Esd_FontInfo *fontInfo_4;
	if (if_5)
	{
		fontInfo_4 = context->FontResource(owner);
	}
	else
	{
		uint8_t i_4 = context->Font(owner);
		fontInfo_4 = Esd_GetRomFont(i_4);
	}
	return Esd_GetFontHeight(fontInfo_4);
}

void Ft_Esd_NumericLabel_Update(Ft_Esd_NumericLabel *context)
{
	void *owner = context->Owner;
	ft_uint8_t left_1 = context->AutoResize(owner);
	ft_uint8_t right_1 = ESD_AUTORESIZE_HEIGHT;
	int if_6 = left_1 == right_1;
	if (if_6)
	{
		uint16_t set_local_height = Ft_Esd_NumericLabel_Get_Font_Height_2__return(context);
		Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)context, (int)set_local_height);
	}
	else
	{
	}
	ft_int32_t set_ndigit = context->NoOfDigits(owner);
	context->NDigit = set_ndigit;
	Ft_Esd_NumericLabel_UpdateNumberString(context);
	Ft_Esd_NumericLabel_ComputePosition(context);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context); 
}


/* end of file */
