/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_Cgradient
Header
*/

#ifndef Ft_Esd_Cgradient__H
#define Ft_Esd_Cgradient__H

#include "Esd_Base.h"
#include "Ft_Esd.h"
#include "Ft_Esd_RenderForwarder.h"
#include "Ft_Esd_Widget.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_ARRAY_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define Ft_Esd_Cgradient_CLASSID 0x464AC402
ESD_SYMBOL(Ft_Esd_Cgradient_CLASSID, Type = esd_classid_t)

/* ESD cGradient widget is supported exclusively by BT820. */
ESD_WIDGET(Ft_Esd_Cgradient, Include = "Ft_Esd_Cgradient.h", Callback, DisplayName = "ESD cGradient", Category = EsdBasicWidgets, Icon = ":/icons/gradient.png", X = 0, Y = 0, Width = 400, Height = 300, BackToFront)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	ESD_VARIABLE(Shape, DisplayName = "Shape Option", Type = Esd_CGradientType, Default = ESD_CORNER_ZERO, Public)
	ft_uint8_t Shape;
	ESD_VARIABLE(OuterColor, DisplayName = "Outer Color", Type = esd_argb32_t, Default = #4bff23, Public)
	esd_argb32_t OuterColor;
	ESD_VARIABLE(InnerColor, DisplayName = "Inner Color", Type = esd_argb32_t, Default = #d42323, Public)
	esd_argb32_t InnerColor;
	Ft_Esd_RenderForwarder Render_Forwarder;
} Ft_Esd_Cgradient;

void Ft_Esd_Cgradient__Initializer(Ft_Esd_Cgradient *context);

ESD_SLOT(End)
void Ft_Esd_Cgradient_End(Ft_Esd_Cgradient *context);

#endif /* Ft_Esd_Cgradient__H */

/* end of file */
