/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_Gauge
C Source
*/

/*
Comment :
Introduction:
This widget draws a gauge.
It internally calls co-processor command CMD_GAUGE.
*/

#include "Ft_Esd_Gauge.h"

#include "Esd_Context.h"
#include "Ft_Esd_CoCmd.h"
#include "Ft_Esd_Dl.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
Ft_Esd_Theme * Ft_Esd_Gauge_Theme__Default(void *context) { return Ft_Esd_Theme_GetCurrent(); }
ft_uint8_t Ft_Esd_Gauge_Alpha__Default(void *context) { return 255; }
ft_uint16_t Ft_Esd_Gauge_Val__Default(void *context) { return 0U; }
ft_uint16_t Ft_Esd_Gauge_Range__Default(void *context) { return 0U; }
ft_uint16_t Ft_Esd_Gauge_Major__Default(void *context) { return 4U; }
ft_uint16_t Ft_Esd_Gauge_Minor__Default(void *context) { return 16U; }
ft_bool_t Ft_Esd_Gauge_ShowTicks__Default(void *context) { return 1; }
ft_bool_t Ft_Esd_Gauge_ShowPointer__Default(void *context) { return 1; }
ft_bool_t Ft_Esd_Gauge_ShowBackground__Default(void *context) { return 1; }

static ft_int16_t Ft_Esd_Gauge_Ft_Esd_PosSizeToRadius_X__Property(void *context);
static ft_int16_t Ft_Esd_Gauge_Ft_Esd_PosSizeToRadius_Y__Property(void *context);
static ft_int16_t Ft_Esd_Gauge_Ft_Esd_PosSizeToRadius_Width__Property(void *context);
static ft_int16_t Ft_Esd_Gauge_Ft_Esd_PosSizeToRadius_Height__Property(void *context);

static Ft_Esd_WidgetSlots s_Ft_Esd_Gauge__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Gauge_Update,
	(void(*)(void *))Ft_Esd_Gauge_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Widget_End,
};


void Ft_Esd_Gauge__Ft_Esd_PosSizeToRadius__Initializer(Ft_Esd_Gauge *context)
{
	Ft_Esd_PosSizeToRadius *object = (Ft_Esd_PosSizeToRadius *)&context->Ft_Esd_PosSizeToRadius;
	Ft_Esd_PosSizeToRadius__Initializer(object);
	object->Owner = (void *)context;
	object->X = Ft_Esd_Gauge_Ft_Esd_PosSizeToRadius_X__Property;
	object->Y = Ft_Esd_Gauge_Ft_Esd_PosSizeToRadius_Y__Property;
	object->Width = Ft_Esd_Gauge_Ft_Esd_PosSizeToRadius_Width__Property;
	object->Height = Ft_Esd_Gauge_Ft_Esd_PosSizeToRadius_Height__Property;
}

void Ft_Esd_Gauge__Initializer(Ft_Esd_Gauge *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_Gauge_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_Gauge__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 144;
	context->Widget.LocalHeight = 144;
	context->Theme = Ft_Esd_Gauge_Theme__Default;
	Ft_Esd_Gauge__Ft_Esd_PosSizeToRadius__Initializer(context);
	context->Alpha = Ft_Esd_Gauge_Alpha__Default;
	context->Val = Ft_Esd_Gauge_Val__Default;
	context->Range = Ft_Esd_Gauge_Range__Default;
	context->Major = Ft_Esd_Gauge_Major__Default;
	context->Minor = Ft_Esd_Gauge_Minor__Default;
	context->AutoResize = ESD_AUTORESIZE_NONE;
	context->ShowTicks = Ft_Esd_Gauge_ShowTicks__Default;
	context->ShowPointer = Ft_Esd_Gauge_ShowPointer__Default;
	context->ShowBackground = Ft_Esd_Gauge_ShowBackground__Default;
}


void Ft_Esd_Gauge_Render(Ft_Esd_Gauge *context)
{
	void *owner = context->Owner;
	ft_uint8_t alpha = context->Alpha(owner);
	Ft_Esd_Dl_COLOR_A(alpha);
	EVE_HalContext * phost = Ft_Esd_GetHost();
	Ft_Esd_Theme * theme = context->Theme(owner);
	ft_argb32_t c_1 = Ft_Esd_Theme_GetBackColor(theme);
	Ft_Gpu_CoCmd_BgColor(phost, c_1);
	Ft_Esd_Theme * theme_1 = context->Theme(owner);
	ft_argb32_t c_2 = Ft_Esd_Theme_GetTextColor(theme_1);
	Ft_Esd_Dl_COLOR_RGB(c_2);
	EVE_HalContext * phost_1 = Ft_Esd_GetHost();
	ft_int16_t x = Ft_Esd_PosSizeToRadius_CenterX(&context->Ft_Esd_PosSizeToRadius);
	ft_int16_t y = Ft_Esd_PosSizeToRadius_CenterY(&context->Ft_Esd_PosSizeToRadius);
	ft_int16_t r = Ft_Esd_PosSizeToRadius_Radius(&context->Ft_Esd_PosSizeToRadius);
	ft_bool_t if_1 = context->ShowTicks(owner);
	uint16_t left_1;
	if (if_1)
	{
		left_1 = 0;
	}
	else
	{
		left_1 = OPT_NOTICKS;
	}
	ft_bool_t if_2 = context->ShowPointer(owner);
	uint16_t right;
	if (if_2)
	{
		right = 0;
	}
	else
	{
		right = OPT_NOPOINTER;
	}
	int left = left_1 | right;
	ft_bool_t if_3 = context->ShowBackground(owner);
	uint16_t right_1;
	if (if_3)
	{
		right_1 = 0;
	}
	else
	{
		right_1 = OPT_NOBACK;
	}
	int options = left + right_1;
	ft_uint16_t major = context->Major(owner);
	ft_uint16_t minor = context->Minor(owner);
	ft_uint16_t val = context->Val(owner);
	ft_uint16_t range = context->Range(owner);
	Ft_Gpu_CoCmd_Gauge(phost_1, x, y, r, options, major, minor, val, range);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

ft_int16_t Ft_Esd_Gauge_Ft_Esd_PosSizeToRadius_X__Property(void *c)
{
	Ft_Esd_Gauge *context = (Ft_Esd_Gauge *)c;
	void *owner = context->Owner;
	return context->Widget.GlobalX;
}

ft_int16_t Ft_Esd_Gauge_Ft_Esd_PosSizeToRadius_Y__Property(void *c)
{
	Ft_Esd_Gauge *context = (Ft_Esd_Gauge *)c;
	void *owner = context->Owner;
	return context->Widget.GlobalY;
}

ft_int16_t Ft_Esd_Gauge_Ft_Esd_PosSizeToRadius_Width__Property(void *c)
{
	Ft_Esd_Gauge *context = (Ft_Esd_Gauge *)c;
	void *owner = context->Owner;
	return context->Widget.GlobalWidth;
}

ft_int16_t Ft_Esd_Gauge_Ft_Esd_PosSizeToRadius_Height__Property(void *c)
{
	Ft_Esd_Gauge *context = (Ft_Esd_Gauge *)c;
	void *owner = context->Owner;
	return context->Widget.GlobalHeight;
}

void Ft_Esd_Gauge_Update(Ft_Esd_Gauge *context)
{
	void *owner = context->Owner;
	ft_uint8_t left_2 = context->AutoResize;
	ft_uint8_t right_2 = ESD_AUTORESIZE_HEIGHT;
	ft_uint8_t if_4 = left_2 & right_2;
	if (if_4)
	{
		ft_int16_t left_3 = context->Widget.GlobalHeight;
		ft_int16_t right_3 = context->Widget.GlobalWidth;
		int if_5 = left_3 > right_3;
		if (if_5)
		{
			ft_int16_t set_height_to_width = context->Widget.GlobalWidth;
			Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)context, set_height_to_width);
		}
		else
		{
		}
	}
	else
	{
	}
	ft_uint8_t left_4 = context->AutoResize;
	ft_uint8_t right_4 = ESD_AUTORESIZE_WIDTH;
	ft_uint8_t if_6 = left_4 & right_4;
	if (if_6)
	{
		ft_int16_t left_5 = context->Widget.GlobalWidth;
		ft_int16_t right_5 = context->Widget.GlobalHeight;
		int if_7 = (left_5 << 2) > (right_5 << 2);
		if (if_7)
		{
			ft_int16_t set_width_to_height = context->Widget.GlobalHeight;
			Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)context, set_width_to_height);
		}
		else
		{
		}
	}
	else
	{
	}
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context); 
}


/* end of file */
