/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_PushButton
C Source
*/

/*
Comment :
Introduction:
This widget draws a push button.
CMD_BUTTON is used internally.
Font type, font size and text can be customized.
Touch input is supported.
*/

#include "Ft_Esd_PushButton.h"

#include "Esd_Context.h"
#include "Esd_BitmapHandle.h"
#include "Ft_Esd_BitmapHandle.h"
#include "Ft_Esd_CoCmd.h"
#include "Ft_Esd_Dl.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
Ft_Esd_Theme * Ft_Esd_PushButton_Theme__Default(void *context) { return Ft_Esd_Theme_GetCurrent(); }
uint8_t Ft_Esd_PushButton_Font__Default(void *context) { return 27; }
Esd_FontInfo * Ft_Esd_PushButton_FontResource__Default(void *context) { return 0; }
const char * Ft_Esd_PushButton_Text__Default(void *context) { return "Button"; }
ft_bool_t Ft_Esd_PushButton_Primary__Default(void *context) { return 1; }


static Ft_Esd_WidgetSlots s_Ft_Esd_PushButton__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_PushButton_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_PushButton_Update,
	(void(*)(void *))Ft_Esd_PushButton_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_PushButton_End,
};

static void Ft_Esd_PushButton_Touch_Tag_Down__Signal(void *context);
static void Ft_Esd_PushButton_Touch_Tag_Up__Signal(void *context);
static void Ft_Esd_PushButton_Touch_Tag_Tap__Signal(void *context);
static void Ft_Esd_PushButton_ESD_Timer_Fired__Signal(void *context);

void Ft_Esd_PushButton__Touch_Tag__Initializer(Ft_Esd_PushButton *context)
{
	Ft_Esd_TouchTag *object = (Ft_Esd_TouchTag *)&context->Touch_Tag;
	Ft_Esd_TouchTag__Initializer(object);
	object->Owner = (void *)context;
	object->Down = Ft_Esd_PushButton_Touch_Tag_Down__Signal;
	object->Up = Ft_Esd_PushButton_Touch_Tag_Up__Signal;
	object->Tap = Ft_Esd_PushButton_Touch_Tag_Tap__Signal;
}

void Ft_Esd_PushButton__ESD_Timer__Initializer(Ft_Esd_PushButton *context)
{
	Ft_Esd_Timer *object = (Ft_Esd_Timer *)&context->ESD_Timer;
	Ft_Esd_Timer__Initializer(object);
	object->Owner = (void *)context;
	object->Repeat = 1;
	object->Fired = Ft_Esd_PushButton_ESD_Timer_Fired__Signal;
}

void Ft_Esd_PushButton__Initializer(Ft_Esd_PushButton *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_PushButton_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_PushButton__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 120;
	context->Widget.LocalHeight = 36;
	context->Theme = Ft_Esd_PushButton_Theme__Default;
	context->Down = Esd_Noop;
	context->Font = Ft_Esd_PushButton_Font__Default;
	context->Up = Esd_Noop;
	context->FontResource = Ft_Esd_PushButton_FontResource__Default;
	context->Pushed = Esd_Noop;
	context->Text = Ft_Esd_PushButton_Text__Default;
	context->Primary = Ft_Esd_PushButton_Primary__Default;
	context->Style = ESD_OPT_3D;
	context->LongPush = 0;
	context->Interval = 1000L;
	Ft_Esd_PushButton__Touch_Tag__Initializer(context);
	Ft_Esd_PushButton__ESD_Timer__Initializer(context);
}

ESD_CORE_EXPORT Esd_FontInfo *Esd_GetRomFont(uint8_t);

void Ft_Esd_PushButton_Start(Ft_Esd_PushButton *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context);
	Ft_Esd_TouchTag_Start(&context->Touch_Tag);
}

void Ft_Esd_PushButton_Update(Ft_Esd_PushButton *context)
{
	void *owner = context->Owner;
	Ft_Esd_TouchTag_Update(&context->Touch_Tag);
	int update_variable = context->Interval;
	context->ESD_Timer.TimeoutMs = update_variable;
	Ft_Esd_Timer_Update(&context->ESD_Timer);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void Ft_Esd_PushButton_End(Ft_Esd_PushButton *context)
{
	void *owner = context->Owner;
	Ft_Esd_TouchTag_End(&context->Touch_Tag);
	Ft_Esd_Timer_End(&context->ESD_Timer);
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
}

void Ft_Esd_PushButton_Render(Ft_Esd_PushButton *context)
{
	void *owner = context->Owner;
	ft_uint8_t alpha = 255;
	Ft_Esd_Dl_COLOR_A(alpha);
	ft_uint8_t s = Ft_Esd_TouchTag_Tag(&context->Touch_Tag);
	Ft_Esd_Dl_TAG(s);
	EVE_HalContext * phost = Ft_Esd_GetHost();
	ft_bool_t if_1 = context->Primary(owner);
	ft_rgb32_t c_1;
	if (if_1)
	{
		Ft_Esd_Theme * theme = context->Theme(owner);
		c_1 = Ft_Esd_Theme_GetPrimaryColor(theme);
	}
	else
	{
		Ft_Esd_Theme * theme_1 = context->Theme(owner);
		c_1 = Ft_Esd_Theme_GetCurrentColor(theme_1);
	}
	Ft_Gpu_CoCmd_FgColor(phost, c_1);
	Ft_Esd_Theme * theme_2 = context->Theme(owner);
	ft_argb32_t c_2 = Ft_Esd_Theme_GetButtonTextColor(theme_2);
	Ft_Esd_Dl_COLOR_RGB(c_2);
	EVE_HalContext * phost_1 = Ft_Esd_GetHost();
	ft_int16_t x = context->Widget.GlobalX;
	ft_int16_t y = context->Widget.GlobalY;
	ft_int16_t width = context->Widget.GlobalWidth;
	ft_int16_t height = context->Widget.GlobalHeight;
	Esd_FontInfo * if_2 = context->FontResource(owner);
	Esd_FontInfo *fontInfo;
	if (if_2)
	{
		fontInfo = context->FontResource(owner);
	}
	else
	{
		uint8_t i = context->Font(owner);
		fontInfo = Esd_GetRomFont(i);
	}
	uint8_t font = Ft_Esd_Dl_Font_Setup(fontInfo);
	ft_bool_t if_3 = Ft_Esd_TouchTag_Inside(&context->Touch_Tag);
	uint16_t options;
	if (if_3)
	{
		ft_uint8_t value = context->Style;
		switch (value)
		{
			case 0L:
			{
				options = OPT_FLAT | 0;
				break;
			}
			case 1L:
			{
				options = 0;
				break;
			}
			default:
			{
				options = OPT_FLAT;
				break;
			}
		}
	}
	else
	{
		ft_uint8_t value_1 = context->Style;
		switch (value_1)
		{
			case 0L:
			{
				options = 0;
				break;
			}
			case 1L:
			{
				options = OPT_FLAT;
				break;
			}
			default:
			{
				options = 0;
				break;
			}
		}
	}
	const char * s_1 = context->Text(owner);
	Ft_Gpu_CoCmd_Button(phost_1, x, y, width, height, font, options, s_1);
	ft_uint8_t s_2 = 255;
	Ft_Esd_Dl_TAG(s_2);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

ft_bool_t Ft_Esd_PushButton_Pushing(Ft_Esd_PushButton *context)
{
	void *owner = context->Owner;
	return Ft_Esd_TouchTag_Inside(&context->Touch_Tag);
}

void Ft_Esd_PushButton_Touch_Tag_Down__Signal(void *c)
{
	Ft_Esd_PushButton *context = (Ft_Esd_PushButton *)c;
	void *owner = context->Owner;
	context->Down(owner);
	ft_bool_t if_4 = context->LongPush;
	if (if_4)
	{
		Ft_Esd_Timer_Run(&context->ESD_Timer);
	}
	else
	{
	}
}

void Ft_Esd_PushButton_Touch_Tag_Up__Signal(void *c)
{
	Ft_Esd_PushButton *context = (Ft_Esd_PushButton *)c;
	void *owner = context->Owner;
	context->Up(owner);
	int if_5 = context->ESD_Timer.RemainingMs;
	if (if_5)
	{
		Ft_Esd_Timer_Halt(&context->ESD_Timer);
	}
	else
	{
	}
}

void Ft_Esd_PushButton_Touch_Tag_Tap__Signal(void *c)
{
	Ft_Esd_PushButton *context = (Ft_Esd_PushButton *)c;
	void *owner = context->Owner;
	context->Pushed(owner);
}

void Ft_Esd_PushButton_ESD_Timer_Fired__Signal(void *c)
{
	Ft_Esd_PushButton *context = (Ft_Esd_PushButton *)c;
	void *owner = context->Owner;
	context->Pushed(owner);
}


/* end of file */
