/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_Image_SlideShow
C Source
*/

/*
Comment :
This part is Right to Left.
*/

#include "Ft_Esd_Image_SlideShow.h"

#include "Esd_Context.h"
#include "EVE_CoDl.h"
#include "Esd_Math.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
int Ft_Esd_Image_SlideShow_Array_Input__Default(void *context, size_t *size) { *size = 0; return NULL; }

static Ft_Esd_BitmapCell Ft_Esd_Image_SlideShow_ESD_Image_2_BitmapCell__Property(void *context);
static Ft_Esd_BitmapCell Ft_Esd_Image_SlideShow_ESD_Image_BitmapCell__Property(void *context);
static ft_argb32_t Ft_Esd_Image_SlideShow_ESD_Rectangle_Widget_Color__Property(void *context) { return 0x64636363UL; }

static Ft_Esd_WidgetSlots s_Ft_Esd_Image_SlideShow__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Image_SlideShow_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Image_SlideShow_Update,
	(void(*)(void *))Ft_Esd_Image_SlideShow_Render,
	(void(*)(void *))Ft_Esd_Image_SlideShow_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Image_SlideShow_End,
};

static void Ft_Esd_Image_SlideShow_ESD_Timer_Fired__Signal(void *context);
static void Ft_Esd_Image_SlideShow_ESD_Image_2_RenderComplete__Signal(void *context);
static void Ft_Esd_Image_SlideShow_ESD_Image_RenderComplete__Signal(void *context);

void Ft_Esd_Image_SlideShow__ESD_Timer__Initializer(Ft_Esd_Image_SlideShow *context)
{
	Ft_Esd_Timer *object = (Ft_Esd_Timer *)&context->ESD_Timer;
	Ft_Esd_Timer__Initializer(object);
	object->Owner = (void *)context;
	object->Repeat = 1;
	object->Fired = Ft_Esd_Image_SlideShow_ESD_Timer_Fired__Signal;
}

void Ft_Esd_Image_SlideShow__Fixed_Positioning__Initializer(Ft_Esd_Image_SlideShow *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Positioning;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Ft_Esd_Image_SlideShow__ESD_Image_2__Initializer(Ft_Esd_Image_SlideShow *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image_2;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->BitmapCell = Ft_Esd_Image_SlideShow_ESD_Image_2_BitmapCell__Property;
	object->RenderComplete = Ft_Esd_Image_SlideShow_ESD_Image_2_RenderComplete__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Positioning);
}

void Ft_Esd_Image_SlideShow__ESD_Image__Initializer(Ft_Esd_Image_SlideShow *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->BitmapCell = Ft_Esd_Image_SlideShow_ESD_Image_BitmapCell__Property;
	object->Scaling = ESD_SCALING_FIT;
	object->RenderComplete = Ft_Esd_Image_SlideShow_ESD_Image_RenderComplete__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Positioning);
}

void Ft_Esd_Image_SlideShow__ESD_Rectangle_Widget__Initializer(Ft_Esd_Image_SlideShow *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->ESD_Rectangle_Widget;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 300;
	object->Color = Ft_Esd_Image_SlideShow_ESD_Rectangle_Widget_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Ft_Esd_Image_SlideShow__Initializer(Ft_Esd_Image_SlideShow *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_Image_SlideShow_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_Image_SlideShow__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->Color = 0xffffffffUL;
	context->AutoResize = ESD_AUTORESIZE_NONE;
	context->Scaling = ESD_SCALING_STRETCH;
	context->Speed = 1L;
	context->Duration = 15L;
	context->Animation = IMAGE_RIGHT_TO_LEFT;
	context->VariableTest = 0L;
	context->totalNum = 0L;
	context->Array_Input = Ft_Esd_Image_SlideShow_Array_Input__Default;
	context->Variable_2 = 0L;
	context->BitmapVar = (Esd_BitmapCell){ 0 };
	context->Variable_3 = 0L;
	context->Variable_8 = 0L;
	context->Esd_Scissor_Set = (Esd_Rect16){ 0 };
	context->Bitmap = (Esd_BitmapCell){ 0 };
	context->Variable_5 = (Esd_BitmapCell){ 0 };
	context->Variable_4 = (Esd_BitmapCell){ 0 };
	context->Variable_6 = 0;
	context->Variable_11 = 255L;
	context->Variable_12 = 0.0f;
	context->Variable_14 = 0L;
	context->Variable_13 = 0.0f;
	context->Variable_7 = 0L;
	context->Variable_9 = 0L;
	context->Variable_10 = 0L;
	Ft_Esd_Image_SlideShow__ESD_Timer__Initializer(context);
	Ft_Esd_Image_SlideShow__Fixed_Positioning__Initializer(context);
	Ft_Esd_Image_SlideShow__ESD_Image_2__Initializer(context);
	Ft_Esd_Image_SlideShow__ESD_Image__Initializer(context);
	Ft_Esd_Image_SlideShow__ESD_Rectangle_Widget__Initializer(context);
}

ESD_CORE_EXPORT void Esd_Scissor_Reset(Esd_Rect16);
ESD_CORE_EXPORT Esd_Rect16 Esd_Scissor_Set(Esd_Rect16);

static esd_argb32_t Ft_Esd_Image_SlideShow_Local_Method(Ft_Esd_Image_SlideShow *context, int a, int r, int g, int b);
static esd_argb32_t Ft_Esd_Image_SlideShow_Local_Method_1(Ft_Esd_Image_SlideShow *context, int a, int r, int g, int b);

void Ft_Esd_Image_SlideShow_Update__Builtin(Ft_Esd_Image_SlideShow *context)
{
	void *owner = context->Owner;
	int 	arrayIndex = context->Variable_3;
	size_t sizeAry = 0;
	Esd_BitmapCell* ptrAry = context->Array_Input(context, &sizeAry);
	int update_variable = sizeAry;
	context->totalNum = update_variable;
	int 	arrayIndex_1 = context->Variable_3;
	if(arrayIndex_1<0)  arrayIndex_1=0;
	size_t sizeAry_1 = 0;
	Esd_BitmapCell* ptrAry_1 = context->Array_Input(context, &sizeAry_1);
	Esd_BitmapCell update_variable_1;
	if(sizeAry_1 > 0) {
		arrayIndex_1 = arrayIndex_1%sizeAry_1;
		update_variable_1 = ptrAry_1[arrayIndex_1];
 	}
 	else
		update_variable_1 = (Esd_BitmapCell) {NULL};
 	context->BitmapVar = update_variable_1;
	Esd_BitmapCell update_variable_2 = context->Bitmap;
	context->Variable_4 = update_variable_2;
	int left = context->Duration;
	int right = 1000L;
	int update_variable_3 = left * right;
	context->ESD_Timer.TimeoutMs = update_variable_3;
	Ft_Esd_Timer_Update(&context->ESD_Timer);
	bool update_variable_4 = context->Variable_6;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->ESD_Image_2, update_variable_4);
	ft_int16_t update_variable_5 = context->Widget.GlobalWidth;
	Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)&context->ESD_Image_2, update_variable_5);
	ft_int16_t update_variable_6 = context->Widget.GlobalHeight;
	Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)&context->ESD_Image_2, update_variable_6);
	uint8_t update_variable_7 = context->Scaling;
	context->ESD_Image_2.Scaling = update_variable_7;
	ft_int16_t update_variable_8 = context->Widget.GlobalWidth;
	Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)&context->ESD_Image, update_variable_8);
	ft_int16_t update_variable_9 = context->Widget.GlobalHeight;
	Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)&context->ESD_Image, update_variable_9);
	esd_argb32_t update_variable_10 = context->Color;
	context->ESD_Image.Color = update_variable_10;
	uint8_t update_variable_11 = context->Scaling;
	context->ESD_Image.Scaling = update_variable_11;
	ft_int16_t update_variable_12 = context->Widget.GlobalX;
	Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget, update_variable_12);
	ft_int16_t update_variable_13 = context->Widget.GlobalY;
	Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget, update_variable_13);
	ft_int16_t update_variable_14 = context->Widget.GlobalWidth;
	Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget, update_variable_14);
	ft_int16_t update_variable_15 = context->Widget.GlobalHeight;
	Ft_Esd_Widget_SetHeight((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget, update_variable_15);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void Ft_Esd_Image_SlideShow_End__Builtin(Ft_Esd_Image_SlideShow *context)
{
	void *owner = context->Owner;
	Ft_Esd_Timer_End(&context->ESD_Timer);
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Positioning); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget); 
}

void Ft_Esd_Image_SlideShow_Render(Ft_Esd_Image_SlideShow *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

void Ft_Esd_Image_SlideShow_Idle(Ft_Esd_Image_SlideShow *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Idle((Ft_Esd_Widget *)context); 
}

void Ft_Esd_Image_SlideShow_End(Ft_Esd_Image_SlideShow *context)
{
	void *owner = context->Owner;
	Ft_Esd_Image_SlideShow_End__Builtin(context);
}

void Ft_Esd_Image_SlideShow_Start(Ft_Esd_Image_SlideShow *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context); 
	Ft_Esd_Timer_Run(&context->ESD_Timer);
}

void Ft_Esd_Image_SlideShow_Update(Ft_Esd_Image_SlideShow *context)
{
	void *owner = context->Owner;
	int value = context->Animation;
	switch (value)
	{
		case 0L:
		{
			esd_argb32_t set_variable_30 = 0xffffffffUL;
			context->ESD_Image_2.Color = (esd_argb32_t)set_variable_30;
			int left_1 = context->Variable_8;
			int right_1 = context->Speed;
			int set_variable_6 = left_1 - right_1;
			context->Variable_8 = set_variable_6;
			int left_3 = context->Variable_8;
			int right_2 = context->Speed;
			int left_2 = left_3 - right_2;
			int right_3 = 0L;
			int if_1 = left_2 <= right_3;
			if (if_1)
			{
				Esd_BitmapCell set_variable_13 = context->Variable_4;
				context->Variable_5 = set_variable_13;
				bool set_variable_8 = 0;
				context->Variable_6 = set_variable_8;
			}
			else
			{
				int left_4 = context->Variable_8;
				int right_4 = context->Speed;
				int set_variable_15 = left_4 - right_4;
				Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->ESD_Image_2, (int)set_variable_15);
				bool set_variable_7 = 1;
				context->Variable_6 = set_variable_7;
			}
			break;
		}
		case 1L:
		{
			esd_argb32_t set_variable_30_1 = 0xffffffffUL;
			context->ESD_Image_2.Color = (esd_argb32_t)set_variable_30_1;
			int left_5 = context->Variable_7;
			int right_5 = context->Speed;
			int set_variable_10 = left_5 + right_5;
			context->Variable_7 = set_variable_10;
			int left_7 = context->Variable_7;
			int right_6 = context->Speed;
			int left_6 = left_7 + right_6;
			int right_7 = 0L;
			int if_2 = left_6 >= right_7;
			if (if_2)
			{
				Esd_BitmapCell set_variable_13_1 = context->Variable_4;
				context->Variable_5 = set_variable_13_1;
				bool set_variable_8_1 = 0;
				context->Variable_6 = set_variable_8_1;
			}
			else
			{
				bool set_variable_7_1 = 1;
				context->Variable_6 = set_variable_7_1;
				int left_8 = context->Variable_7;
				int right_8 = context->Speed;
				int set_variable_14 = left_8 + right_8;
				Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->ESD_Image_2, (int)set_variable_14);
			}
			break;
		}
		case 2L:
		{
			esd_argb32_t set_variable_30_2 = 0xffffffffUL;
			context->ESD_Image_2.Color = (esd_argb32_t)set_variable_30_2;
			int left_9 = context->Variable_9;
			int right_9 = context->Speed;
			int set_variable_16 = left_9 - right_9;
			context->Variable_9 = set_variable_16;
			int left_11 = context->Variable_9;
			int right_10 = context->Speed;
			int left_10 = left_11 - right_10;
			int right_11 = 0L;
			int if_3 = left_10 <= right_11;
			if (if_3)
			{
				Esd_BitmapCell set_variable_13_2 = context->Variable_4;
				context->Variable_5 = set_variable_13_2;
				bool set_variable_8_2 = 0;
				context->Variable_6 = set_variable_8_2;
			}
			else
			{
				bool set_variable_7_2 = 1;
				context->Variable_6 = set_variable_7_2;
				int left_12 = context->Variable_9;
				int right_12 = context->Speed;
				int set_variable_18 = left_12 - right_12;
				Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->ESD_Image_2, (int)set_variable_18);
			}
			break;
		}
		case 3L:
		{
			esd_argb32_t set_variable_30_3 = 0xffffffffUL;
			context->ESD_Image_2.Color = (esd_argb32_t)set_variable_30_3;
			int left_13 = context->Variable_10;
			int right_13 = context->Speed;
			int set_variable_20 = left_13 + right_13;
			context->Variable_10 = set_variable_20;
			int left_15 = context->Variable_10;
			int right_14 = context->Speed;
			int left_14 = left_15 + right_14;
			int right_15 = 0L;
			int if_4 = left_14 >= right_15;
			if (if_4)
			{
				Esd_BitmapCell set_variable_13_3 = context->Variable_4;
				context->Variable_5 = set_variable_13_3;
				bool set_variable_8_3 = 0;
				context->Variable_6 = set_variable_8_3;
			}
			else
			{
				bool set_variable_7_3 = 1;
				context->Variable_6 = set_variable_7_3;
				int left_16 = context->Variable_10;
				int right_16 = context->Speed;
				int set_variable_22 = left_16 + right_16;
				Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->ESD_Image_2, (int)set_variable_22);
			}
			break;
		}
		case 4L:
		{
			float left_17 = context->Variable_12;
			int left_18 = context->Speed;
			float right_18 = 2.0f;
			float right_17 = left_18 / right_18;
			float set_variable_24 = left_17 + right_17;
			context->Variable_12 = set_variable_24;
			int set_variable_xy = 0L;
			Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->ESD_Image_2, (int)set_variable_xy);
			Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->ESD_Image_2, (int)set_variable_xy);
			int set_variable_23 = 255L;
			context->Variable_11 = set_variable_23;
			float left_20 = context->Variable_12;
			int left_21 = context->Speed;
			float right_20 = 2.0f;
			float right_19 = left_21 / right_20;
			float left_19 = left_20 + right_19;
			int right_21 = 255L;
			int if_5 = left_19 <= right_21;
			if (if_5)
			{
				bool set_variable_7_4 = 1;
				context->Variable_6 = set_variable_7_4;
				float left_22 = context->Variable_12;
				int left_23 = context->Speed;
				float right_23 = 2.0f;
				float right_22 = left_23 / right_23;
				float a = left_22 + right_22;
				int r = context->Variable_11;
				int g = context->Variable_11;
				int b = context->Variable_11;
				esd_argb32_t set_variable_25 = Ft_Esd_Image_SlideShow_Local_Method(context, a, r, g, b);
				context->ESD_Image_2.Color = (esd_argb32_t)set_variable_25;
			}
			else
			{
				Esd_BitmapCell set_variable_13_4 = context->Variable_4;
				context->Variable_5 = set_variable_13_4;
				bool set_variable_8_4 = 0;
				context->Variable_6 = set_variable_8_4;
			}
			break;
		}
		case 5L:
		{
			float left_24 = context->Variable_13;
			int left_25 = context->Speed;
			float right_25 = 2.0f;
			float right_24 = left_25 / right_25;
			float set_variable_28 = left_24 + right_24;
			context->Variable_13 = set_variable_28;
			int set_variable_xy_1 = 0L;
			Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->ESD_Image_2, (int)set_variable_xy_1);
			Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->ESD_Image_2, (int)set_variable_xy_1);
			int set_variable_31 = 255L;
			context->Variable_14 = set_variable_31;
			float left_27 = context->Variable_13;
			int left_28 = context->Speed;
			float right_27 = 2.0f;
			float right_26 = left_28 / right_27;
			float left_26 = left_27 + right_26;
			int right_28 = 255L;
			int if_6 = left_26 <= right_28;
			if (if_6)
			{
				bool set_variable_7_5 = 1;
				context->Variable_6 = set_variable_7_5;
				float left_29 = context->Variable_13;
				int left_30 = context->Speed;
				float right_30 = 2.0f;
				float right_29 = left_30 / right_30;
				float a_1 = left_29 + right_29;
				int r_1 = context->Variable_14;
				int g_1 = context->Variable_14;
				int b_1 = context->Variable_14;
				esd_argb32_t set_variable_29 = Ft_Esd_Image_SlideShow_Local_Method_1(context, a_1, r_1, g_1, b_1);
				context->ESD_Image_2.Color = (esd_argb32_t)set_variable_29;
			}
			else
			{
				Esd_BitmapCell set_variable_13_5 = context->Variable_4;
				context->Variable_5 = set_variable_13_5;
				bool set_variable_8_5 = 0;
				context->Variable_6 = set_variable_8_5;
			}
			break;
		}
		case 6L:
		{
			break;
		}
		default:
		{
			break;
		}
	}
	Ft_Esd_Image_SlideShow_Update__Builtin(context);
}

static esd_argb32_t Ft_Esd_Image_SlideShow_Local_Method(Ft_Esd_Image_SlideShow *context, int a, int r, int g, int b)
{
	void *owner = context->Owner;
	return (a << 24) | (r << 16) | (g << 8) | b;
}

static esd_argb32_t Ft_Esd_Image_SlideShow_Local_Method_1(Ft_Esd_Image_SlideShow *context, int a, int r, int g, int b)
{
	void *owner = context->Owner;
	return (a << 24) | (r << 16) | (g << 8) | b;
}

void Ft_Esd_Image_SlideShow_ESD_Timer_Fired__Signal(void *c)
{
	Ft_Esd_Image_SlideShow *context = (Ft_Esd_Image_SlideShow *)c;
	void *owner = context->Owner;
	int set_variable = context->Variable_2;
	context->VariableTest = set_variable;
	Ft_Esd_Timer_Halt(&context->ESD_Timer);
	int left_32 = context->VariableTest;
	int right_31 = 1L;
	int left_31 = left_32 + right_31;
	int right_32 = context->totalNum;
	int if_7 = left_31 <= right_32;
	if (if_7)
	{
		int left_33 = context->VariableTest;
		int right_33 = 1L;
		int set_variable_2 = left_33 + right_33;
		context->Variable_2 = set_variable_2;
		int set_variable_4 = context->Variable_2;
		context->Variable_3 = set_variable_4;
		Esd_BitmapCell set_variable_5 = context->BitmapVar;
		context->Bitmap = set_variable_5;
		// Variable writer 'Set_Variable_Common' does not write to any variables
		ft_int16_t set_variable_value_x = context->Widget.GlobalWidth;
		context->Variable_8 = set_variable_value_x;
		int set_variable_11 = 0L;
		Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->ESD_Image_2, (int)set_variable_11);
		float set_variable_26 = 0.0f;
		context->Variable_12 = set_variable_26;
		float set_variable_27 = 0.0f;
		context->Variable_13 = set_variable_27;
		ft_int16_t left_34 = context->Widget.GlobalWidth;
		int right_34 = -1L;
		int set_variable_9 = left_34 * right_34;
		context->Variable_7 = set_variable_9;
		int set_variable_12 = 0L;
		Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->ESD_Image_2, (int)set_variable_12);
		ft_int16_t set_variable_h = context->Widget.GlobalHeight;
		context->Variable_9 = set_variable_h;
		int set_variable_17 = 0L;
		Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->ESD_Image_2, (int)set_variable_17);
		ft_int16_t left_35 = context->Widget.GlobalHeight;
		int right_35 = -1L;
		int set_variable_19 = left_35 * right_35;
		context->Variable_10 = set_variable_19;
		int set_variable_21 = 0L;
		Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->ESD_Image_2, (int)set_variable_21);
	}
	else
	{
		int set_variable_3 = 1L;
		context->Variable_2 = set_variable_3;
		int set_variable_4_1 = context->Variable_2;
		context->Variable_3 = set_variable_4_1;
		Esd_BitmapCell set_variable_5_1 = context->BitmapVar;
		context->Bitmap = set_variable_5_1;
		// Variable writer 'Set_Variable_Common' does not write to any variables
		ft_int16_t set_variable_value_x_1 = context->Widget.GlobalWidth;
		context->Variable_8 = set_variable_value_x_1;
		int set_variable_11_1 = 0L;
		Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->ESD_Image_2, (int)set_variable_11_1);
		float set_variable_26_1 = 0.0f;
		context->Variable_12 = set_variable_26_1;
		float set_variable_27_1 = 0.0f;
		context->Variable_13 = set_variable_27_1;
		ft_int16_t left_36 = context->Widget.GlobalWidth;
		int right_36 = -1L;
		int set_variable_9_1 = left_36 * right_36;
		context->Variable_7 = set_variable_9_1;
		int set_variable_12_1 = 0L;
		Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->ESD_Image_2, (int)set_variable_12_1);
		ft_int16_t set_variable_h_1 = context->Widget.GlobalHeight;
		context->Variable_9 = set_variable_h_1;
		int set_variable_17_1 = 0L;
		Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->ESD_Image_2, (int)set_variable_17_1);
		ft_int16_t left_37 = context->Widget.GlobalHeight;
		int right_37 = -1L;
		int set_variable_19_1 = left_37 * right_37;
		context->Variable_10 = set_variable_19_1;
		int set_variable_21_1 = 0L;
		Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->ESD_Image_2, (int)set_variable_21_1);
	}
}

Ft_Esd_BitmapCell Ft_Esd_Image_SlideShow_ESD_Image_2_BitmapCell__Property(void *c)
{
	Ft_Esd_Image_SlideShow *context = (Ft_Esd_Image_SlideShow *)c;
	void *owner = context->Owner;
	return context->Variable_4;
}

void Ft_Esd_Image_SlideShow_ESD_Image_2_RenderComplete__Signal(void *c)
{
	Ft_Esd_Image_SlideShow *context = (Ft_Esd_Image_SlideShow *)c;
	void *owner = context->Owner;
	EVE_HalContext * phost = Esd_GetHost();
	EVE_CoDl_restoreContext(phost);
}

Ft_Esd_BitmapCell Ft_Esd_Image_SlideShow_ESD_Image_BitmapCell__Property(void *c)
{
	Ft_Esd_Image_SlideShow *context = (Ft_Esd_Image_SlideShow *)c;
	void *owner = context->Owner;
	return context->Variable_5;
}

void Ft_Esd_Image_SlideShow_ESD_Image_RenderComplete__Signal(void *c)
{
	Ft_Esd_Image_SlideShow *context = (Ft_Esd_Image_SlideShow *)c;
	void *owner = context->Owner;
	bool if_8 = context->Variable_6;
	if (if_8)
	{
		Ft_Esd_Rect16 state = context->Widget.GlobalRect;
		Esd_Scissor_Reset(state);
	}
	else
	{
	}
}


/* end of file */
