/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_Gradient_Arc_Line
C Source
*/

#include "Ft_Esd_Gradient_Arc_Line.h"

#include "Esd_Context.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);


static Ft_Esd_WidgetSlots s_Ft_Esd_Gradient_Arc_Line__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Gradient_Arc_Line_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Widget_End,
};


void Ft_Esd_Gradient_Arc_Line__Initializer(Ft_Esd_Gradient_Arc_Line *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_Gradient_Arc_Line_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_Gradient_Arc_Line__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->Border = 20L;
	context->Start_Color = 0xff00ff00UL;
	context->End_Color = 0xffaa0000UL;
	context->Origin = 0L;
	context->Angle = 90L;
	context->IsClockwise = 1;
	context->ShowEndPoint = 1;
	context->ShowStartPoint = 1;
}

void Ft_Esd_Gradient_Arc_Line_Func(Ft_Esd_Gradient_Arc_Line *context, int, int, int, int, int, int, ft_argb32_t, ft_argb32_t, ft_bool_t, int, int);

void Ft_Esd_Gradient_Arc_Line_Render(Ft_Esd_Gradient_Arc_Line *context)
{
	void *owner = context->Owner;
	ft_int16_t x = context->Widget.GlobalX;
	ft_int16_t y = context->Widget.GlobalY;
	ft_int16_t width = context->Widget.GlobalWidth;
	ft_int16_t height = context->Widget.GlobalHeight;
	int radius = 0L;
	int border = context->Border;
	esd_argb32_t startColor = context->Start_Color;
	esd_argb32_t endColor = context->End_Color;
	bool isClockwise = context->IsClockwise;
	int origin = context->Origin;
	int value = context->Angle;
	Ft_Esd_Gradient_Arc_Line_Func(context, x, y, width, height, radius, border, startColor, endColor, isClockwise, origin, value);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}


/* end of file */
