/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_SignalSwitch
Header
*/

#ifndef Ft_Esd_SignalSwitch__H
#define Ft_Esd_SignalSwitch__H

#include "Esd_Base.h"
#include "Esd_Core.h"
#include "Ft_Esd.h"
#include "Ft_Esd_Layout_Fixed.h"
#include "Ft_Esd_Math.h"
#include "Ft_Esd_ScrollPanel.h"
#include "Ft_Esd_Theme.h"
#include "Ft_Esd_Widget.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_ARRAY_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define Ft_Esd_SignalSwitch_CLASSID 0xB553304E
ESD_SYMBOL(Ft_Esd_SignalSwitch_CLASSID, Type = esd_classid_t)

/* Signal Switch Page layout, requires initialising on start and switch nodes for allocating new widget */
ESD_WIDGET(Ft_Esd_SignalSwitch, Include = "Ft_Esd_SignalSwitch.h", Callback, DisplayName = "Signal Switch Page", Category = EsdLayouts, Icon = ":/icons/ui-scroll-pane-horizontal.png", X = 0, Y = 0, Width = 400, Height = 300, Layout, BackToFront)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	/* Initial Previous Page Object Pointer */
	ESD_INPUT(InitialPrevious, DisplayName = "Initial Previous ", Type = Ft_Esd_Widget *)
	Ft_Esd_Widget *(* InitialPrevious)(void *context);
	/* Initial Current Page Object Pointer */
	ESD_INPUT(InitialCurrent, DisplayName = "Initial Current", Type = Ft_Esd_Widget *)
	Ft_Esd_Widget *(* InitialCurrent)(void *context);
	/* Initial Next Page Object Pointer */
	ESD_INPUT(InitialNext, DisplayName = "Initial Next", Type = Ft_Esd_Widget *)
	Ft_Esd_Widget *(* InitialNext)(void *context);
	/* Initial Current Index */
	ESD_INPUT(InitialIndex, DisplayName = "Initial Index", Type = int, Min = 0, Default = 1)
	int(* InitialIndex)(void *context);
	/* Switch Speed in scale of 1 to 16. */
	ESD_VARIABLE(SwitchSpeed, DisplayName = "Switch Speed", Type = int, Min = 1, Max = 16, Default = 4, Public)
	int SwitchSpeed;
	/* Page Count */
	ESD_VARIABLE(Count, DisplayName = "Count", Type = int, Min = 3, Max = 20, Default = 4, Public)
	int Count;
	ESD_VARIABLE(Target, Type = int, Private)
	int Target;
	/* Enable switch looping */
	ESD_VARIABLE(Looping, DisplayName = "Loop Pages", Type = ft_bool_t, Default = true, Public)
	ft_bool_t Looping;
	/* Horizontal or vertical layout */
	ESD_VARIABLE(Direction, DisplayName = "Layout Direction", Type = Esd_LayoutDirection, Min = 0, Max = 1, Default = ESD_HORIZONTAL, Public)
	ft_uint8_t Direction;
	ESD_VARIABLE(State, Type = int, Private)
	int State;
	/* If currently widget is on shifting */
	ESD_VARIABLE(Shifting, DisplayName = "Shifting", Type = ft_bool_t, Default = false, ReadOnly)
	ft_bool_t Shifting;
	ESD_VARIABLE(UpdatePos, Type = int, Private)
	int UpdatePos;
	ESD_SIGNAL(NewPage)
	void(* NewPage)(void *context);
	/* Input New Page Object Pointer */
	ESD_INPUT(New, DisplayName = "New Page", Type = Ft_Esd_Widget *)
	Ft_Esd_Widget *(* New)(void *context);
	/* Previous Page Object Pointer */
	ESD_VARIABLE(Previous, DisplayName = "Previous Page", Type = Ft_Esd_Widget *, ReadOnly)
	Ft_Esd_Widget * Previous;
	/* Current Page Index */
	ESD_VARIABLE(Index, DisplayName = "Current Index", Type = int, Default = 1, ReadOnly)
	int Index;
	/* Current Page Object Pointer */
	ESD_VARIABLE(Current, DisplayName = "Current Page", Type = Ft_Esd_Widget *, ReadOnly)
	Ft_Esd_Widget * Current;
	/* New Page Index */
	ESD_VARIABLE(NewIndex, DisplayName = "New Index", Type = int, Default = 1, ReadOnly)
	int NewIndex;
	/* Next Page Object Pointer */
	ESD_VARIABLE(Next, DisplayName = "Next Page", Type = Ft_Esd_Widget *, ReadOnly)
	Ft_Esd_Widget * Next;
	Ft_Esd_ScrollPanel ScrollPanel;
	Ft_Esd_Layout_Fixed FixedPositioning;
} Ft_Esd_SignalSwitch;

void Ft_Esd_SignalSwitch__Initializer(Ft_Esd_SignalSwitch *context);

ESD_SLOT(End)
void Ft_Esd_SignalSwitch_End(Ft_Esd_SignalSwitch *context);

ESD_SLOT(NextPageSignal)
void Ft_Esd_SignalSwitch_NextPageSignal(Ft_Esd_SignalSwitch *context);

ESD_SLOT(PreviousPageSignal)
void Ft_Esd_SignalSwitch_PreviousPageSignal(Ft_Esd_SignalSwitch *context);

ESD_SLOT(Initialise)
void Ft_Esd_SignalSwitch_Initialise(Ft_Esd_SignalSwitch *context);

ESD_SLOT(Update)
void Ft_Esd_SignalSwitch_Update(Ft_Esd_SignalSwitch *context);

ESD_SLOT(Render)
void Ft_Esd_SignalSwitch_Render(Ft_Esd_SignalSwitch *context);

#endif /* Ft_Esd_SignalSwitch__H */

/* end of file */
