/*
This file is automatically generated
DO NOT MODIFY BY HAND
FirstPage
C Source
*/

#include "FirstPage.h"

#include "Esd_Context.h"
ESD_CORE_EXPORT void Esd_Noop(void *context);

static uint8_t FirstPage_Click_Me_Font__Property(void *context) { return 31; }
static const char * FirstPage_Click_Me_Text__Property(void *context) { return "Click Me"; }
static uint8_t FirstPage_ESD_Label_Font__Property(void *context) { return 31; }
static const char * FirstPage_ESD_Label_Text__Property(void *context) { return "ESD"; }

static Ft_Esd_WidgetSlots s_FirstPage__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))FirstPage_End,
};


void FirstPage__Fixed_Position__Initializer(FirstPage *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void FirstPage__Click_Me__Initializer(FirstPage *context)
{
	Ft_Esd_LabelButton *object = (Ft_Esd_LabelButton *)&context->Click_Me;
	Ft_Esd_LabelButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 319;
	object->Widget.LocalY = 179;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = FirstPage_Click_Me_Font__Property;
	object->Text = FirstPage_Click_Me_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void FirstPage__ESD_Label__Initializer(FirstPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = FirstPage_ESD_Label_Font__Property;
	object->Text = FirstPage_ESD_Label_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void FirstPage__Initializer(FirstPage *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = FirstPage_CLASSID;
	context->Widget.Slots = &s_FirstPage__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	FirstPage__Fixed_Position__Initializer(context);
	FirstPage__Click_Me__Initializer(context);
	FirstPage__ESD_Label__Initializer(context);
}

void FirstPage_End(FirstPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Click_Me); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label); 
}


/* end of file */
