/*
This file is automatically generated
EVE_CoCmd__h
Simulation wrapper
*/

/* Simulation wrapper for 'EVE_CoCmd_clock' */


/* Simulation wrapper for 'EVE_CoCmd_dial' */


/* Simulation wrapper for 'EVE_CoCmd_gauge' */


/* Simulation wrapper for 'EVE_CoCmd_keys' */


/* Simulation wrapper for 'EVE_CoCmd_number' */


/* Simulation wrapper for 'EVE_CoCmd_progress' */


/* Simulation wrapper for 'EVE_CoCmd_scrollbar' */


/* Simulation wrapper for 'EVE_CoCmd_slider' */


/* Simulation wrapper for 'EVE_CoCmd_text_ex' */


/* end of file */
