/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_TouchArea
C Source
*/

#include "Ft_Esd_TouchArea.h"

#include "Esd_Context.h"
#include "Ft_Esd_TouchTag.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
int Ft_Esd_TouchArea_X__Default(void *context) { return 0L; }
int Ft_Esd_TouchArea_Y__Default(void *context) { return 0L; }
int Ft_Esd_TouchArea_Width__Default(void *context) { return 0L; }
int Ft_Esd_TouchArea_Height__Default(void *context) { return 0L; }



void Ft_Esd_TouchArea__Initializer(Ft_Esd_TouchArea *context)
{
	context->Owner = 0;
	context->Up = Esd_Noop;
	context->LastTouching = 0;
	context->Down = Esd_Noop;
	context->Touching = 0;
	context->X = Ft_Esd_TouchArea_X__Default;
	context->Y = Ft_Esd_TouchArea_Y__Default;
	context->Width = Ft_Esd_TouchArea_Width__Default;
	context->Height = Ft_Esd_TouchArea_Height__Default;
}

static ft_bool_t Ft_Esd_TouchArea_Ft_Esd_TouchArea_IsInBounds__return(Ft_Esd_TouchArea *context);

void Ft_Esd_TouchArea_Update_TouchTag(Ft_Esd_TouchArea *context);
ft_bool_t Ft_Esd_TouchArea_IsInBounds(Ft_Esd_TouchArea *context);

void Ft_Esd_TouchArea_Update(Ft_Esd_TouchArea *context)
{
	void *owner = context->Owner;
	Ft_Esd_TouchArea_Update_TouchTag(context);
	Ft_Esd_TouchTag * context_1 = 0x0;
	ft_uint8_t left_1 = Ft_Esd_TouchTag_CurrentTag(context_1);
	ft_uint8_t right = 0;
	int left = left_1 != right;
	ft_bool_t right_1 = context->LastTouching;
	int if_1 = left != right_1;
	if (if_1)
	{
		ft_bool_t if_2 = context->Touching;
		if (if_2)
		{
			context->Up(owner);
		}
		else
		{
		}
		Ft_Esd_TouchTag * context_2 = 0x0;
		ft_uint8_t left_2 = Ft_Esd_TouchTag_CurrentTag(context_2);
		ft_uint8_t right_2 = 0;
		int set_lasttouching = left_2 != right_2;
		context->LastTouching = set_lasttouching;
		ft_bool_t left_3 = context->LastTouching;
		ft_bool_t right_3 = Ft_Esd_TouchArea_Ft_Esd_TouchArea_IsInBounds__return(context);
		int set_if_touch_down_in_bounds = left_3 && right_3;
		context->Touching = set_if_touch_down_in_bounds;
		ft_bool_t if_3 = context->Touching;
		if (if_3)
		{
			context->Down(owner);
		}
		else
		{
		}
	}
	else
	{
	}
}

ft_bool_t Ft_Esd_TouchArea_Ft_Esd_TouchArea_IsInBounds__return(Ft_Esd_TouchArea *context)
{
	void *owner = context->Owner;
	return Ft_Esd_TouchArea_IsInBounds(context);
}

ft_bool_t Ft_Esd_TouchArea_Inside(Ft_Esd_TouchArea *context)
{
	void *owner = context->Owner;
	ft_bool_t left_4 = context->Touching;
	ft_bool_t right_4 = Ft_Esd_TouchArea_Ft_Esd_TouchArea_IsInBounds__return(context);
	return left_4 && right_4;
}

ft_bool_t Ft_Esd_TouchArea_Hover(Ft_Esd_TouchArea *context)
{
	void *owner = context->Owner;
	return Ft_Esd_TouchArea_Ft_Esd_TouchArea_IsInBounds__return(context);
}

ft_int16_t Ft_Esd_TouchArea_TouchX(Ft_Esd_TouchArea *context)
{
	void *owner = context->Owner;
	Ft_Esd_TouchTag * context_3 = 0x0;
	return Ft_Esd_TouchTag_TouchX(context_3);
}

ft_int16_t Ft_Esd_TouchArea_TouchY(Ft_Esd_TouchArea *context)
{
	void *owner = context->Owner;
	Ft_Esd_TouchTag * context_4 = 0x0;
	return Ft_Esd_TouchTag_TouchY(context_4);
}


/* end of file */
