/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_TouchScrollLogic
C Source
*/

#include "Ft_Esd_TouchScrollLogic.h"

#include "Esd_Context.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
int Ft_Esd_TouchScrollLogic_X__Default(void *context) { return 0L; }
int Ft_Esd_TouchScrollLogic_Y__Default(void *context) { return 0L; }
int Ft_Esd_TouchScrollLogic_Width__Default(void *context) { return 0L; }
int Ft_Esd_TouchScrollLogic_Height__Default(void *context) { return 0L; }
ft_bool_t Ft_Esd_TouchScrollLogic_EnableXScroll__Default(void *context) { return 1; }
ft_bool_t Ft_Esd_TouchScrollLogic_EnableYScroll__Default(void *context) { return 0; }
int Ft_Esd_TouchScrollLogic_OffsetThreshold__Default(void *context) { return 2L; }
int Ft_Esd_TouchScrollLogic_MinX__Default(void *context) { return 0L; }
int Ft_Esd_TouchScrollLogic_DefaultX__Default(void *context) { return 0L; }
int Ft_Esd_TouchScrollLogic_MaxX__Default(void *context) { return 0L; }
int Ft_Esd_TouchScrollLogic_MinY__Default(void *context) { return 0L; }
int Ft_Esd_TouchScrollLogic_DefaultY__Default(void *context) { return 0L; }
int Ft_Esd_TouchScrollLogic_MaxY__Default(void *context) { return 0L; }

static int Ft_Esd_TouchScrollLogic_Touch_Area_X__Property(void *context);
static int Ft_Esd_TouchScrollLogic_Touch_Area_Y__Property(void *context);
static int Ft_Esd_TouchScrollLogic_Touch_Area_Width__Property(void *context);
static int Ft_Esd_TouchScrollLogic_Touch_Area_Height__Property(void *context);

static void Ft_Esd_TouchScrollLogic_Touch_Area_Up__Signal(void *context);
static void Ft_Esd_TouchScrollLogic_Touch_Area_Down__Signal(void *context);

void Ft_Esd_TouchScrollLogic__Touch_Area__Initializer(Ft_Esd_TouchScrollLogic *context)
{
	Ft_Esd_TouchArea *object = (Ft_Esd_TouchArea *)&context->Touch_Area;
	Ft_Esd_TouchArea__Initializer(object);
	object->Owner = (void *)context;
	object->X = Ft_Esd_TouchScrollLogic_Touch_Area_X__Property;
	object->Y = Ft_Esd_TouchScrollLogic_Touch_Area_Y__Property;
	object->Width = Ft_Esd_TouchScrollLogic_Touch_Area_Width__Property;
	object->Height = Ft_Esd_TouchScrollLogic_Touch_Area_Height__Property;
	object->Up = Ft_Esd_TouchScrollLogic_Touch_Area_Up__Signal;
	object->Down = Ft_Esd_TouchScrollLogic_Touch_Area_Down__Signal;
}

void Ft_Esd_TouchScrollLogic__Initializer(Ft_Esd_TouchScrollLogic *context)
{
	context->Owner = 0;
	context->IsTouched = 0;
	context->X = Ft_Esd_TouchScrollLogic_X__Default;
	context->isTouchChanged = 0;
	context->Y = Ft_Esd_TouchScrollLogic_Y__Default;
	context->Width = Ft_Esd_TouchScrollLogic_Width__Default;
	context->Height = Ft_Esd_TouchScrollLogic_Height__Default;
	context->EnableXScroll = Ft_Esd_TouchScrollLogic_EnableXScroll__Default;
	context->speedXAvg = 0.0;
	context->speedYAvg = 0.0;
	context->TouchScrolled = Esd_Noop;
	context->EnableYScroll = Ft_Esd_TouchScrollLogic_EnableYScroll__Default;
	context->OffsetThreshold = Ft_Esd_TouchScrollLogic_OffsetThreshold__Default;
	context->aX = 0.0;
	context->aY = 0.0;
	context->lastX = 0.0;
	context->lastY = 0.0;
	context->lastOffsetX = 0.0;
	context->lastOffsetY = 0.0;
	context->dY = 0.0;
	context->dX = 0.0;
	context->OldDy = 0.0;
	context->MinX = Ft_Esd_TouchScrollLogic_MinX__Default;
	context->OldDx = 0.0;
	context->DefaultX = Ft_Esd_TouchScrollLogic_DefaultX__Default;
	context->offsetY = 0L;
	context->offsetX = 0L;
	context->MaxX = Ft_Esd_TouchScrollLogic_MaxX__Default;
	context->MinY = Ft_Esd_TouchScrollLogic_MinY__Default;
	context->DefaultY = Ft_Esd_TouchScrollLogic_DefaultY__Default;
	context->MaxY = Ft_Esd_TouchScrollLogic_MaxY__Default;
	Ft_Esd_TouchScrollLogic__Touch_Area__Initializer(context);
}

void Ft_Esd_TouchScrollLogic_TouchUpdate_Then(Ft_Esd_TouchScrollLogic *context);
void Ft_Esd_TouchScrollLogic_Check_X_acceleration_Then(Ft_Esd_TouchScrollLogic *context);
void Ft_Esd_TouchScrollLogic_Check_Y_acceleration_Then(Ft_Esd_TouchScrollLogic *context);

void Ft_Esd_TouchScrollLogic_Start(Ft_Esd_TouchScrollLogic *context)
{
	void *owner = context->Owner;
	int set_x_default = context->DefaultX(owner);
	context->offsetX = set_x_default;
	int set_y_default = context->DefaultY(owner);
	context->offsetY = set_y_default;
}

void Ft_Esd_TouchScrollLogic_Update(Ft_Esd_TouchScrollLogic *context)
{
	void *owner = context->Owner;
	Ft_Esd_TouchArea_Update(&context->Touch_Area);
	ft_bool_t resetischanged = 0;
	context->isTouchChanged = resetischanged;
	ft_bool_t left = context->Touch_Area.Touching;
	ft_bool_t right = context->IsTouched;
	int if_1 = left && right;
	if (if_1)
	{
		Ft_Esd_TouchScrollLogic_TouchUpdate_Then(context);
	}
	else
	{
		double left_1 = context->speedXAvg;
		int right_1 = 0L;
		int if_2 = left_1 != right_1;
		if (if_2)
		{
			Ft_Esd_TouchScrollLogic_Check_X_acceleration_Then(context);
		}
		else
		{
		}
		double left_2 = context->speedYAvg;
		int right_2 = 0L;
		int if_3 = left_2 != right_2;
		if (if_3)
		{
			Ft_Esd_TouchScrollLogic_Check_Y_acceleration_Then(context);
		}
		else
		{
		}
	}
	ft_bool_t if_4 = context->isTouchChanged;
	if (if_4)
	{
		context->TouchScrolled(owner);
	}
	else
	{
	}
}

double Ft_Esd_TouchScrollLogic_DeltaY(Ft_Esd_TouchScrollLogic *context)
{
	void *owner = context->Owner;
	double value = context->dY;
	return -value;
}

double Ft_Esd_TouchScrollLogic_DeltaX(Ft_Esd_TouchScrollLogic *context)
{
	void *owner = context->Owner;
	double value_1 = context->dX;
	return -value_1;
}

int Ft_Esd_TouchScrollLogic_ScrolledY(Ft_Esd_TouchScrollLogic *context)
{
	void *owner = context->Owner;
	return context->offsetY;
}

int Ft_Esd_TouchScrollLogic_ScrolledX(Ft_Esd_TouchScrollLogic *context)
{
	void *owner = context->Owner;
	return context->offsetX;
}

int Ft_Esd_TouchScrollLogic_Touch_Area_X__Property(void *c)
{
	Ft_Esd_TouchScrollLogic *context = (Ft_Esd_TouchScrollLogic *)c;
	void *owner = context->Owner;
	return context->X(owner);
}

int Ft_Esd_TouchScrollLogic_Touch_Area_Y__Property(void *c)
{
	Ft_Esd_TouchScrollLogic *context = (Ft_Esd_TouchScrollLogic *)c;
	void *owner = context->Owner;
	return context->Y(owner);
}

int Ft_Esd_TouchScrollLogic_Touch_Area_Width__Property(void *c)
{
	Ft_Esd_TouchScrollLogic *context = (Ft_Esd_TouchScrollLogic *)c;
	void *owner = context->Owner;
	return context->Width(owner);
}

int Ft_Esd_TouchScrollLogic_Touch_Area_Height__Property(void *c)
{
	Ft_Esd_TouchScrollLogic *context = (Ft_Esd_TouchScrollLogic *)c;
	void *owner = context->Owner;
	return context->Height(owner);
}

void Ft_Esd_TouchScrollLogic_Touch_Area_Up__Signal(void *c)
{
	Ft_Esd_TouchScrollLogic *context = (Ft_Esd_TouchScrollLogic *)c;
	void *owner = context->Owner;
	ft_bool_t unset_istouchscroll = 0;
	context->IsTouched = unset_istouchscroll;
}

void Ft_Esd_TouchScrollLogic_Touch_Area_Down__Signal(void *c)
{
	Ft_Esd_TouchScrollLogic *context = (Ft_Esd_TouchScrollLogic *)c;
	void *owner = context->Owner;
	ft_bool_t if_5 = Ft_Esd_TouchArea_Inside(&context->Touch_Area);
	if (if_5)
	{
		ft_bool_t left_3 = context->EnableXScroll(owner);
		ft_bool_t right_3 = context->EnableYScroll(owner);
		ft_bool_t set_istouchscroll = left_3 | right_3;
		context->IsTouched = set_istouchscroll;
		ft_int16_t set_lastx = Ft_Esd_TouchArea_TouchX(&context->Touch_Area);
		context->lastX = (int)set_lastx;
		int set_lastoffsetx = context->offsetX;
		context->lastOffsetX = (int)set_lastoffsetx;
		double resetdx = 0.0;
		context->dX = resetdx;
		context->OldDx = resetdx;
		ft_int16_t set_lasty = Ft_Esd_TouchArea_TouchY(&context->Touch_Area);
		context->lastY = (int)set_lasty;
		int set_last_offsety = context->offsetY;
		context->lastOffsetY = (int)set_last_offsety;
		double resetdy = 0.0;
		context->dY = resetdy;
		context->OldDy = resetdy;
	}
	else
	{
	}
}


/* end of file */
